### ISSUE TITLE
Support 'duplicate and rotate'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1002]
Similar to the current 'rotate' feature, but duplicates the object before rotating it.
![image](https://cloud.githubusercontent.com/assets/1673303/14566125/c45af4aa-0360-11e6-808f-7b2c3623d6f7.png)

**Comment by damithc** [comment]
@Dawnlord don't put `fixes NNNN` in every commit. As you can see above, it spams the issue thread.

**Comment by Dawnlord** [comment]
Okay, next time I will pay attention.

**Comment by damithc** [comment]
@Dawnlord close this if done (including updates to the user docs)
