### ISSUE TITLE
Support 'rotate slightly' feature

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1003]
Similar to the current rotate feature but each click rotate the object by one degree clockwise or anti-clockwise, w.r.t. the reference object. 

![image](https://cloud.githubusercontent.com/assets/1673303/14566341/cc2f774a-0361-11e6-8117-a24ab657c158.png)

**Comment by damithc** [comment]
@Dawnlord can create icons for positions lab (he's done a few already :-)

**Comment by Dawnlord** [comment]
![-1](https://cloud.githubusercontent.com/assets/10655859/15497180/f7cf7cd2-21cb-11e6-9fb3-014aea89bc10.png)

Is this one okay?
@damithc @fionachang

**Comment by damithc** [comment]
Put circle in the middle of the arrow? Try both and see which one looks better at the actual size.

**Comment by Dawnlord** [comment]
![rotateslightlyicon2](https://cloud.githubusercontent.com/assets/10655859/15497617/202b6a18-21ce-11e6-8830-ee0152a19a2d.png)
![rotateslightlyicon](https://cloud.githubusercontent.com/assets/10655859/15497618/2031ed52-21ce-11e6-8dcc-4b2e5c102e4f.png)
![qq 20160524163924](https://cloud.githubusercontent.com/assets/10655859/15497616/202b88a4-21ce-11e6-8133-417fb13f54b0.png)

How about this?

**Comment by damithc** [comment]
As discussed, this need not be a separate feature, just an additional behavior for existing rotate functions. i.e. When a rotate function is 'active' arrow keys will rotate by one degree.

**Comment by damithc** [comment]
@Dawnlord is this done? Documentation updated?

**Comment by Dawnlord** [comment]
This function is being worked by @fionachang . I just try to help add icon.

**Comment by fionachang** [comment]
Waiting for merge. There is no doc for positions lab.

**Comment by damithc** [comment]
Documentation still in GoogleDoc form. I've shared it with the two of you just now.

**Comment by youthinkk** [comment]
Implemented and merged.
