### ISSUE TITLE
Refine the 'snap away' icon

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1004]
The current one has details that are too small to see
![image](https://cloud.githubusercontent.com/assets/1673303/14566456/44476364-0362-11e6-92c3-261223b6b936.png)

**Comment by IanTeo** [comment]
Can I do do this?

**Comment by damithc** [comment]
Sure, give it a try.

**Comment by damithc** [comment]
Seems to be fixed
