### ISSUE TITLE
Error while launching PSL

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1013]
![image](https://cloud.githubusercontent.com/assets/1673303/14766234/7c29d586-0a34-11e6-989c-097097852343.png)

**Comment by kai33** [comment]
duplicate #991 will fix soon

**Comment by damithc** [comment]
Looks like it happens when the slide layout is not the default layout.

**Comment by kai33** [comment]
sir can you attach the sample slide here?

**Comment by damithc** [comment]
[PSL launch error.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/233340/PSL.launch.error.pptx)

**Comment by kai33** [comment]
Fixed by #991
