### ISSUE TITLE
Picture Slides Lab should stay inside screen at low resolution

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1017]
When the resolution is low (e.g. forced lower resolution when connected to projector), PSL window goes out of screen and PSL becomes unusable.

**Comment by Dawnlord** [comment]
![2016513-175858](https://cloud.githubusercontent.com/assets/10655859/15279327/b572d0ea-1b55-11e6-863c-ee9b160e5ef4.jpg)

It can fit the screen even 800 * 600.
