### ISSUE TITLE
Fail to pass QuickPropertyTest()

### ISSUE THREAD

**Issue by Dawnlord** [PowerPointLabs/PowerPointLabs#1027]
Test Name:  FT_QuickPropertyTest
Test FullName:  Test.FunctionalTest.QuickPropertyTest.FT_QuickPropertyTest
Test Source:    D:\PPtLab\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\QuickPropertyTest.cs : line 19
Test Outcome:   Failed
Test Duration:  0:00:08.9981001

Result StackTrace:   Test.FunctionalTest.QuickPropertyTest.FT_QuickPropertyTest()  D:\PPtLab\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\QuickPropertyTest.cs: line 50
Result Message: Assert.AreNotEqual failed. Expected any value except:<0>. Actual:<0>. Failed to find Property handle.

Is this also because of system language ?

**Comment by kai33** [comment]
Can be.
ref: https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/Test/FunctionalTest/QuickPropertyTest.cs#L49

it tries to find a window with title `Format Object`

**Comment by kai33** [comment]
You can use Spy++ to look into the window handles

**Comment by damithc** [comment]
Old issue. closing.
