### ISSUE TITLE
Allow custom formatting for generated captions

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1029]
Some users may want to use their own formatting for the generated captions e.g. left align

**Comment by leeyh20** [comment]
Seems like a very useful feature that makes captions lab much more useful! I wanted to suggest this... Shall we work on this too?

**Comment by damithc** [comment]
> Seems like a very useful feature that makes captions lab much more useful! I wanted to suggest this... Shall we work on this too?

Sure.

**Comment by blewjy** [comment]
I will be taking on this issue. 

My current plan is to add a settings menu to captions lab and to allow the user to change how the generated captions should look. Attributes that user can change include:
- Text Color
- Background Color
- Text Alignment
- Text Style (Bold, Italic, Underline, Strikethrough, etc.)

**Comment by damithc** [comment]
@blewjy best not to take this issue. Captions and Narrations Labs will be subsumed into an eLarningLab currently being developed by Xiaowei

**Comment by blewjy** [comment]
@damithc, ok noted. I'll work on something else in that case. Thanks!
