### ISSUE TITLE
Add indezine blog post to reviews

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1042]
Add this to the reviews page
http://blog.indezine.com/2016/06/picture-slides-lab-conversation-with.html

**Comment by damithc** [comment]
Here's another one (in Spanish) http://www.alejandraavila.com/powerpoint-labs-el-secreto-mejor-guardado/

**Comment by damithc** [comment]
Another one https://nutsandboltsspeedtraining.com/best-powerpoint-addins/

**Comment by IanTeo** [comment]
@damithc can I do this?

**Comment by damithc** [comment]
Sure.
