### ISSUE TITLE
Write Test for Rotate or Duplicate and Rotate function

### ISSUE THREAD

**Issue by Dawnlord** [PowerPointLabs/PowerPointLabs#1053]
I have meet the problems of simulation a button clicking in the WPF Pane. Therefore, I still cannot complete the unit test of them.

**Comment by IanTeo** [comment]
Can I try to do this? I think I can do it, however, I will be doing a FT instead of UT, as we need to simulate dragging and dropping.

**Comment by damithc** [comment]
Sure @IanTeo give it a try

**Comment by kai33** [comment]
Merged. @IanTeo may I know how's the codes coverage (by line) for the new test?
