### ISSUE TITLE
Cleanup of Tutorial.pptx

### ISSUE THREAD

**Issue by vhazali** [PowerPointLabs/PowerPointLabs#1068]
### Things to do 
- Need to clean up grammar throughout the file
- Numbering in Effects Lab section
- Numerous typos within file
 - Slide 17
- Standardise the whole powerpoint
 - Terms used
 - Numbering

**Comment by initialshl** [comment]
Thanks @vhazali , we referred to this issue when cleaning up Tutorial.pptx for public-release-4.0.0.0.
A new issue may be created if there are anymore errors.
Closing this issue.
