### ISSUE TITLE
Adopt a C# coding standard 

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1070]
Contribute a C# coding standard to [oss-generic](https://github.com/oss-generic/process/blob/master/docs/CodingStandards.md) and adopt it.

**Comment by AngShiYa** [comment]
Can I take this up?

**Comment by damithc** [comment]
Sure @AngShiYa Propose one first and we can get feedback from others before adopting it. It's better if we reuse an existing one from some other established project/company.

**Comment by AngShiYa** [comment]
hi @damithc this is the initial draft that I made
https://github.com/AngShiYa/process/blob/master/codingStandards/CodingStandards-C%23.md

**Comment by acjh** [comment]
@AngShiYa Please submit as a PR to facilitate review comments :)

Most notably, [Line 158](https://github.com/AngShiYa/process/blame/master/codingStandards/CodingStandards-C%23.md#L158) should be a `</table>` instead of `<table>`,
which might be the cause of code in backticks getting messed up.

**Comment by damithc** [comment]
@AngShiYa 

1. I prefer if we can pick one existing standard and then extract out the basic stuff to our document if the parent standard is too detailed for beginners. In that case, give the parent standard at the top. Users can refer to parent standard for all non-basic stuff.
2. Regarding good/bad examples, follow the formatting of this doc instead https://github.com/oss-generic/process/blob/master/codingStandards/CodingStandard-Css.md

**Comment by AngShiYa** [comment]
Made some changes and submitted as a [PR](https://github.com/oss-generic/process/pull/22).

**Comment by damithc** [comment]
@AngShiYa May be update PowerPointLabs documentation to point to the coding standard at oss-generic?

**Comment by AngShiYa** [comment]
@damithc There already is in CONTRIBUTING.md under [Coding Standards](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/doc/CONTRIBUTING.md#coding-standards). Or do you mean to add it in other parts of the documentation?

**Comment by damithc** [comment]
> @damithc There already is in CONTRIBUTING.md under Coding Standards. Or do you mean to add it in other parts of the documentation?

I see. Then no need.
