### ISSUE TITLE
Clean up Acknowledgement Slide

### ISSUE THREAD

**Issue by Skaty** [PowerPointLabs/PowerPointLabs#1072]
The acknowledgement slide currently looks like this:
![image](https://cloud.githubusercontent.com/assets/978676/22107826/17d395be-de8b-11e6-8a86-cbb9b7159447.png)

However, I believe that the slide could be better designed, maybe to one that is professional looking and makes use of our branding.

**Comment by damithc** [comment]
The stretching happens on widescreen format only. But yes, it can be improved in any case.

**Comment by Skaty** [comment]
@damithc I've found a fix for the stretching. Should I PR that fix first?

**Comment by damithc** [comment]
> Should I PR that fix first?

Sure.
