### ISSUE TITLE
Animation Lab: Animate does not take into account shape flipping

### ISSUE THREAD

**Issue by Skaty** [PowerPointLabs/PowerPointLabs#1075]
This problem only occurs when shapes are modified using the flip tool or resized such that it flips. It is present on both `Add Animation Slide` and `Animate In Slide`.

**Current Behaviour**

![actual](https://i.imgur.com/0JZb7ki.gif)

**Expected Behaviour**

![expected](https://i.imgur.com/0nvgCwj.gif)

**Comment by jamos-tay** [comment]
Is anyone working on this? I might have a fix

**Comment by damithc** [comment]
This too is related to Auto-animate feature which is no longer actively developed. But if you have a fix for this, can go ahead.

**Comment by Ohohcakester** [comment]
I think I should point out that flipping is not equivalent to a 180 degree
rotation.
Try doing the same with the letter F.

**Comment by Skaty** [comment]
My bad. But the actual animation is still quite bad.
