### ISSUE TITLE
User docs: order labs alphabetically

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1093]
Our list of Labs is getting longer. Perhaps it is time to order by name?

![image](https://cloud.githubusercontent.com/assets/1673303/22426732/59015766-e73b-11e6-9e48-0b2a0965b097.png)

**Comment by Skaty** [comment]
I believe an alphabetical sorting is good. I also believe that the lab icons should be placed beside every lab.

**Comment by AngShiYa** [comment]
I second that. However some labs does not have an icon.

For example, the agenda lab have an icon with the border rounded at the bottom left. 
![agendalab](https://cloud.githubusercontent.com/assets/12497234/22456426/50d2cb0a-e7cd-11e6-8999-7453d263c7cc.png)

But some labs like highlight lab, captions lab, crop lab, etc only have icons for the features in the lab.

Another thing I noticed while I was typing is the naming of the labs are not standardised. Some labs like narrations and captions have 's', while animation, zoom, crop and highlight does not. Maybe we should standardised the naming too?

**Comment by damithc** [comment]
> Another thing I noticed while I was typing is the naming of the labs are not standardised. Some labs like narrations and captions have 's', while animation, zoom, crop and highlight does not. Maybe we should standardised the naming too?

Yes, we should do that. Perhaps not in the middle of the semester though, as it requires lot of changes including screenshots, tutorial files, etc.

**Comment by damithc** [comment]
> second that. However some labs does not have an icon.
> For example, the agenda lab have an icon with the border rounded at the bottom left.

If we want to add icons for menu items, we might have to create a different set of uniform-looking and smaller icons for each lab. Can be left as an open issue for now.
