### ISSUE TITLE
Update AboutUs page

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1101]
1. Xie Kai : Project Lead --> Mentor
2. Min Oo --> Project Lead
3. Yu Ting --> Co-Lead
4. Victor --> crop/resize photo to match face size of other photos
5. Add new members
6. Move Oswell to past members

**Comment by damithc** [comment]
Just realized @Dawnlord is missing in that page. @Dawnlord can you add a suitable photo here so that it can be added to the page? 

`Liu Hanyang` to be added to the core members section.

**Comment by Dawnlord** [comment]
![hanyang](https://cloud.githubusercontent.com/assets/10655859/22537870/0a28297a-e949-11e6-9fab-de36fa0e80b3.png)
