### ISSUE TITLE
Update feature leads in README

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1102]
Update the README.md with feature leads

It would be good to have a feature lead and a co-lead for all legacy/new features, except perhaps deprecated features.

**Comment by Skaty** [comment]
Wouldn't we need at least a lead for the deprecated features, so that any bugs can be resolved?

**Comment by damithc** [comment]
> Wouldn't we need at least a lead for the deprecated features, so that any bugs can be resolved?

Yes, it's good to have at least a lead for deprecated features.
