### ISSUE TITLE
Add resize lab gif to the landing page

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1104]
The gif is already in the repo but the blurb is missing from the landing page.
![resizelab](https://cloud.githubusercontent.com/assets/1673303/22506091/91576ab8-e8b9-11e6-9b0d-e5f0429dd0e9.gif)

**Comment by Skaty** [comment]
Should we put this after the other blurbs?

**Comment by damithc** [comment]
The page doesn't have a specific order other than we want to keep stronger features near the top. You can decide where to insert this one.
