### ISSUE TITLE
Add missing icons for minimized groups in ribbon

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1105]
When the window is shrunk, icons for minimized groups aren't defined so Powerpoint uses placeholders:

![image](https://cloud.githubusercontent.com/assets/19278089/22509690/14c3d638-e8ca-11e6-90f1-1bd81fb45442.png)

**Comment by damithc** [comment]
I didn't realize those can be defined by us :-)

**Comment by Skaty** [comment]
I believe they can be defined.

@jamos-tay are you working on it? If not, I can work on this. :)

**Comment by jamos-tay** [comment]
Sure, I experimented with this a little but ran into problems, the icons appear but they render really small for some reason:

![image](https://cloud.githubusercontent.com/assets/19278089/22510566/714f7972-e8cd-11e6-8f35-df2d7c8ea297.png)

You can work on this if you like.

**Comment by Skaty** [comment]
#1098 might be relevant to this issue.

**Comment by Kenneth-LJS** [comment]
I can design the icons for #1098 and #1105

**Comment by Kenneth-LJS** [comment]
I believe this issue should be closed.

**Comment by damithc** [comment]
> I believe this issue should be closed.

You should have put `Fixes #...` in the PR description. :-p
