### ISSUE TITLE
Highlight Lab: Add 'Remove Highlight' functionality

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1107]
Currently, if the user wants to remove highlighting that has been applied to a slide, he has to manually delete the animations from the animation pane and delete all the created highlight shapes:

![image](https://cloud.githubusercontent.com/assets/19278089/22619099/ace8a9b6-eb27-11e6-9200-b2d2754cd890.png)

Similar to the 'Remove Agenda' option, we should have an option that allows the user to strip all highlighting from the current slide.

![image](https://cloud.githubusercontent.com/assets/19278089/22619114/f5b85290-eb27-11e6-9170-2304fd2003ed.png)

**Comment by jamos-tay** [comment]
Can I work on this?

**Comment by Skaty** [comment]
@jamos-tay I've assign it. :)
