### ISSUE TITLE
Effects Lab: Blur/recolor all except selected changes original slide

### ISSUE THREAD

**Issue by AngShiYa** [PowerPointLabs/PowerPointLabs#1108]
When the selected  shape is not at the top, it will be placed at the top after applying the effects.

Example: select the red shape and apply blur all except selected in this slide
![original slide](https://cloud.githubusercontent.com/assets/12497234/22620442/33d6be62-eb47-11e6-84fa-d6dbc8bcec65.png)

Actual:
![actual](https://cloud.githubusercontent.com/assets/12497234/22620421/87dd001c-eb46-11e6-90b4-7a1c50d9784f.png)

Expected:
![expected](https://cloud.githubusercontent.com/assets/12497234/22620422/8afe6af6-eb46-11e6-8f38-7da3e460e060.png)

The same goes for recolor all except selected.

**Comment by AngShiYa** [comment]
If it is ok, I would like to work on this issue

**Comment by damithc** [comment]
> If it is ok, I would like to work on this issue

Go ahead @AngShiYa
