### ISSUE TITLE
Deploy Guidance

### ISSUE THREAD

**Issue by Dawnlord** [PowerPointLabs/PowerPointLabs#1140]
1. Prepare Documents For the new features
2. Upload these documents to `/~pptlabs/dev` and checked by seniors
3. Prepare new features and UT in `dev` branch 
4. After checked by seniors, merge `dev` branch to `release-standalone/web branch`
5. Update version information in  these two branches
6. Upload new version website
7. Set up deploy helper from [here](https://github.com/PowerPointLabs/DeployHelper)
8. Follow the deployment guideline to deploy both offline and online version(details [here](https://github.com/PowerPointLabs/DeployHelper) and Google docs)
9. After deployment, reopen the PPtlabs on your computer for two times to check whether it is updated.

**Comment by initialshl** [comment]
Thanks @Dawnlord for this guide.

These steps are now documented in Google Drive -> How To Deploy -> "How To Deploy PowerPointLabs", section "Steps for Public Release".

Closing issue.
