### ISSUE TITLE
Add to reviews

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1153]
https://intexpliki.wordpress.com/2016/08/13/powerpointlabs-add-in/
~~https://nutsandboltsspeedtraining.com/best-powerpoint-addins/~~ (EDIT: already included)

We can also add a few more quotes taken from the reviews.

**Comment by jamos-tay** [comment]
I think the second one is already included by this PR: PowerPointLabs/PowerPointLabs-Website#44

**Comment by damithc** [comment]
> I think the second one is already included by this PR: PowerPointLabs/PowerPointLabs-Website#44

Removed. Thanks @jamos-tay

**Comment by damithc** [comment]
Also can add  http://powerpointlabs.software.informer.com/ ?
