### ISSUE TITLE
Colors Lab: Selected color shifts to a certain brightness/saturation

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1162]
If you hold the color picker on the color display panel, 
the selected color will shift by 1 unit until a certain point in brightness/saturation.

<img src="https://cloud.githubusercontent.com/assets/19281538/23309053/32fea4a4-fae8-11e6-9e93-bc2d63b49b75.gif" width="400">
(ignore the slider image burn, it's caused by the gif maker)

**Comment by IanTeo** [comment]
@initialshl If PR fixes this issue, could you close it? I don't know why it didn't close even though you added the fixes tag..

**Comment by acjh** [comment]
PR didn't close this issue because it was merged into `dev-release` rather than `master` branch.
This is also the case for several past PRs (including #1159), so someone needs to go close those.
