### ISSUE TITLE
Help button redirecting to old docs site

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1165]
The help button in the Ribbon currently redirects to the old docs html:

http://www.comp.nus.edu.sg/~pptlabs//docs.html

This should be the correct one:

http://www.comp.nus.edu.sg/~pptlabs/docs/

**Comment by damithc** [comment]
What's the behavior for the published version? If it's also broken for the published version, we need to fix it immediately. e.g. put a page in the offending URL to redirect to the correct location.

**Comment by Skaty** [comment]
@damithc Let's do the redirection anyways, since there might be users who have bookmarked the old docs.
