### ISSUE TITLE
Some Captions Lab improvements

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1169]
Currently, when a slide has no notes and the Captions Lab button is clicked, nothing happens. This might be confusing for the user.

I suggest the following improvements:

If the Speaker Notes window is minimized, open it (since some users may not know where to find this also)
If there are no notes and the button is clicked, inform the user with a messagebox

**Comment by Kenneth-LJS** [comment]
Makes sense, are you working on this?

**Comment by jamos-tay** [comment]
Not yet, but you can work on it if you want 👍
