### ISSUE TITLE
Update documentation with new features

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1171]
Several PRs merged since the start of the semester have introduced functionality that is not documented on the docs site (powerpointlabs.info):

[User can see a moving magnifier near the tip of the eyedropper #511](https://github.com/PowerPointLabs/PowerPointLabs/pull/1118): Gifs need updating
[Provide a way to prevent revealing future agenda items #695](https://github.com/PowerPointLabs/PowerPointLabs/pull/1092): Document use of empty bullet point
[Highlight Lab: Add 'Remove Highlight' functionality #1107](https://github.com/PowerPointLabs/PowerPointLabs/pull/1121): Document remove highlight functionality
[Provide a way to have hierarchical agendas](https://github.com/PowerPointLabs/PowerPointLabs/pull/1160): Document use of indented bullet points

We should document them so the user is aware that the new functionality exists.

Also feel free to add on if I've missed out any PRs

**Comment by jamos-tay** [comment]
I can probably handle the my own ones (#695 and #1107)

**Comment by initialshl** [comment]
I will handle the ones i did (#511)
