### ISSUE TITLE
Paste to fill slide: should cover entire slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1177]
1. Option can be renamed to `Paste to fill slide`
2. It should fill entire slide, not just width (this may result in image getting bigger than slide -- we can consider auto-cropping for such cases). 
3. Can/should we give `Paste to fill slide width` and `Paste to fill slide height` options too?

**Comment by Skaty** [comment]
Can you provide me with an example for point 2 (current and expected behaviour)?

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/23793936/a6bae282-05c8-11e7-9d55-5dabc26e0611.png)
Top one is the actual, which doesn't actually fill the entire slide.

**Comment by Skaty** [comment]
@damithc Aspect ratio preserved right?

**Comment by damithc** [comment]
Yes.

**Comment by initialshl** [comment]
Closing issue: this issue is fixed and merged into dev-release. #1200
