### ISSUE TITLE
'Terms of Use' page redirecting to staging files

### ISSUE THREAD

**Issue by jamos-tay** [PowerPointLabs/PowerPointLabs#1190]
All the links in the navbar under [this page](http://www.comp.nus.edu.sg/~pptlabs/terms-of-use.html) in the website are redirecting to links in the `staging` folder, as opposed to the main folder. All the files in `staging` redirect to files within the `staging` folder, so the user actually ends up on a site with different content entirely.

Some of the `staging` files contain changes that are not ready to be released, so we should correct these links to redirect to the main folder.

**Comment by Skaty** [comment]
It was a deployment issue. Fixed.
