### ISSUE TITLE
Sync Labs: Sync line fill not working

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1194]
There is currently a bug where sync line fill is not syncing the line fill

**Comment by damithc** [comment]
I noticed that in the current alpha verison line style syncing doesn't work. FYI.

**Comment by IanTeo** [comment]
![image](https://cloud.githubusercontent.com/assets/12381148/23940422/c8846020-099f-11e7-9c42-79eadfffc896.png)

@damithc could you elaborate more? I think it is the problem of different views of what "Line Style" is. Maybe we can come up with a better name for the option or add more options.

So in this case, "Line Style" is actually referring to "Compound Type" only and not "Dash Type" or others. This is because the codes somehow specify "Compound Type" as style..

I am unsure how we should handle this. On one hand, having more options for the user is good. But on the other, I feel that the panel will become very cluttered if we allow customization of every small detail.

**Comment by damithc** [comment]
I was trying to copy green outline from rectangle to the pentagon. The 'paste' action did nothing to the pentagon.
![image](https://cloud.githubusercontent.com/assets/1673303/23940785/354143e4-09a1-11e7-969a-1d696ac8ad53.png)

**Comment by IanTeo** [comment]
Ok. I will try to fix it.

**Comment by IanTeo** [comment]
@damithc Wait.. so you mean the Fill Color is not syncing right? That is what I was saying in this issue.

**Comment by IanTeo** [comment]
As in the Line Fill Color

**Comment by damithc** [comment]
> you mean the Fill Color is not syncing right?

The line width is not syncing either.

![image](https://cloud.githubusercontent.com/assets/1673303/23945127/4bd26f20-09b0-11e7-87b0-7e8156d99ea9.png)

**Comment by IanTeo** [comment]
Strange, Line width is syncing properly for my on 2013. You are testing it on 2010 right?

**Comment by damithc** [comment]
> You are testing it on 2010 right?

Yes, 2010 on Win7
