### ISSUE TITLE
Context menu: Crop To Shape has no icon

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1203]
<img src="https://cloud.githubusercontent.com/assets/19281538/23981785/414a9dea-0a44-11e7-9f64-3fe9225a0588.PNG" width="350">

In alpha-release

**Comment by damithc** [comment]
This is an old context menu item right? In that case there should be a blue icon for it already.

**Comment by initialshl** [comment]
Yes, the icon was accidentally de-referenced in alpha-release when moving crop lab to action framework. Fixed in the PR above.
