### ISSUE TITLE
Sync Lab: Improve Text Sync

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1209]
Positioning 
See TextFrame.Orientation
- [ ] Add support for Text Orientation 

See TextFrame.TextRange.ParagraphFormat
- [ ] Add support for Alignment (Alignment)
- [ ] Add support for Line Spacing (LineRuleBefore/After/Within, SpaceBefore/After/Within)

Misc
- [ ] Add support for Strike through (not adding support, low value as user is unlikely to want all text to be striked through)

**Comment by alexfjw** [comment]
Some of the items here are likely to be more difficult than expected. MSO is likely to give the wrong output when mixed styles/settings are used, just like for color. See #1617
