### ISSUE TITLE
Sync Lab: Add support for Shape Effects

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1213]
Effects
- [x] Add support for Shadow
- [x] Add support for Reflection
- [x] Add support for Glow
- [x] Add support for Soft Edges
- [x] Add support for Bevel
- [x] Add support for 3D-rotation

**Comment by alexfjw** [comment]
Mostly completed, but there are some labs that can be split into smaller components
Respective issues have been created for those labs.
