### ISSUE TITLE
Line color not syncing

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1217]
v 2017.3.16.1

I'm unable to sync line fill color of a shape

![image](https://cloud.githubusercontent.com/assets/1673303/24078369/89829a18-0ca6-11e7-903e-d3360b958a5b.png)

**Comment by IanTeo** [comment]
I am not sure why it is not sync-ing. Maybe the patch is not deployed yet. Could you test it again after @Skaty deploys the version?

**Comment by damithc** [comment]
OK, will try again after I get the next version.

**Comment by IanTeo** [comment]
@damithc could you test it again? I think it should be working for this version

**Comment by damithc** [comment]
I can't test unless it's in alpha release. :-p

**Comment by IanTeo** [comment]
@damithc yes, I mean that it should be already in alpha release since last Thursday

**Comment by damithc** [comment]
Yes, it's working now.
