### ISSUE TITLE
Crop to same dimensions: give options for anchor points

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1220]
When cropping based on another model object, the result can vary on where we consider the 'anchor point'.
In this example, the crop window in anchored to the center.
![image](https://cloud.githubusercontent.com/assets/1673303/24078844/f0c84e9a-0cb3-11e7-8d06-0b7d2fe9812c.png)
Similarly, it can be anchored to 8 other points.
![image](https://cloud.githubusercontent.com/assets/1673303/24078847/0fa2dfa6-0cb4-11e7-923d-345bbb6d11a1.png)
Perhaps we can provide 9 sub-menu options for each of these anchor points?

**Comment by initialshl** [comment]
Closing issue: fix has been merged into dev-release
