### ISSUE TITLE
Add 'fill slide' in the right-click menu

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1246]
We can also allow users to right-click on an image and choose 'Fill slide' (similar to the `Paste to fill slide` feature of the PasteLab)

**Comment by junkiattan** [comment]
@initialshl 

Is this issue still valid? If the closed reference issue addressed this then perhaps we can close this

**Comment by initialshl** [comment]
This means right clicking a picture already existing on the slide, and "fill slide" with that image

**Comment by junkiattan** [comment]
@initialshl 

Does this function apply for both shapes and pictures? Or only pictures?

**Comment by initialshl** [comment]
May have to consult @damithc or UX designer for your questions

**Comment by junkiattan** [comment]
@initialshl @damithc 

I have already consulted with prof just now. The decision is to make the function applicable to both pictures and shapes and for it to only work on one shape/picture at a time
