### ISSUE TITLE
Reorganise context menu

### ISSUE THREAD

**Issue by Skaty** [PowerPointLabs/PowerPointLabs#1247]
It will get cluttered once SyncLab and PasteLab are implemented.

We could group features based on their labs, instead of having one PowerPointLabs group.

**Comment by damithc** [comment]
Be careful of polluting the normal context menu with too many of our features. In the current design our context menu has minimal impact on the default context menu (i.e. only one extra item in the menu) when the user is not using PowerPointLabs features.

**Comment by IanTeo** [comment]
![image](https://user-images.githubusercontent.com/12381148/26962941-4bbfbe3e-4d1c-11e7-8542-8957505a8360.png)
@damithc what do you think about this context menu? Unfortunately, I currently cannot find a way to make the paste lab like PowerPoint's paste on the context menu. I called the second section "Shortcuts" for the lack of a better name. @initialshl was saying that we should have paste at the top, similar to how PowerPoint puts the paste on its context menu. If we put paste below, we can avoid putting a header for "Shortcuts" though.
