### ISSUE TITLE
Exception while 'paste to original position'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1259]
Win 7, PPT 2010 v2017.3.30.1
Steps:
* Copy image
* Choose `Paste to original position`

![image](https://cloud.githubusercontent.com/assets/1673303/24500458/14e71ba4-1578-11e7-8b80-e7bda814b7f9.png)

**Comment by initialshl** [comment]
I cant reproduce this bug on WIn 10 PPT 2016. Does this always occur?

**Comment by damithc** [comment]
Yes. Happening in most recent alpha 2017.3.31.1
I can use other options (e.g. `paste to cursor`) for the same copied image, but this specific option throws an exception.
