### ISSUE TITLE
Crop to same dimension: anchor points are not honored

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1262]
Win7, PPT2010 v2017.3.30.1

![image](https://cloud.githubusercontent.com/assets/1673303/24500880/daa9f874-1579-11e7-9654-1b7d32182b8c.png)

Original : actual : expected

![image](https://cloud.githubusercontent.com/assets/1673303/24500849/bcc6acbc-1579-11e7-9631-8681b078b09c.png)

**Comment by jamos-tay** [comment]
Just to clarify, do you mean the image should be moved so the images line up?

**Comment by damithc** [comment]
> Just to clarify, do you mean the image should be moved so the images line up?

No, this is my expectations based on the selected anchor point.
![image](https://cloud.githubusercontent.com/assets/1673303/24586455/dc40ca62-17d3-11e7-8e86-708f545d60d8.png)

Similarly, if I choose the bottom middle anchor point, it should be like this:
![image](https://cloud.githubusercontent.com/assets/1673303/24586466/2cc7d232-17d4-11e7-8715-0f54d1b95564.png)

BTW, the image should not move at all.

**Comment by jamos-tay** [comment]
Hang on, are you on the alpha-release branch? The anchor points support hasn't been added in yet, it's still awaiting merge: https://github.com/PowerPointLabs/PowerPointLabs/pull/1265

The other branch gives the expected result:

![image](https://cloud.githubusercontent.com/assets/19278089/24586835/1f73dfc4-17dc-11e7-8b03-456bf922270e.png)


![image](https://cloud.githubusercontent.com/assets/19278089/24586833/f1de9b80-17db-11e7-9be0-8695a3771939.png)

![image](https://cloud.githubusercontent.com/assets/19278089/24586834/01f7adae-17dc-11e7-999b-a200b84a64ae.png)

**Comment by damithc** [comment]
Yes, I'm on the alpha channel. I thought it is supported because the settings UI is already there :-p

**Comment by initialshl** [comment]
This issue has bee fixed and merged into dev-release. #1265
