### ISSUE TITLE
Error message for shapes that cannot be copied

### ISSUE THREAD

**Issue by Kenneth-LJS** [PowerPointLabs/PowerPointLabs#1275]
Certain shapes cannot be pasted. When SyncLab tries to copy them, it throws an uncaught exception.

To reproduce:
1) Create a new powerpoint presentation.
2) Select the "Title", which is a textbox created by default on new presentations.
3) Open sync labs and click "Copy"
4) Click "Ok" on the format dialog.

The exception should be caught, and a meaningful error message should be shown.

**Comment by damithc** [comment]
I think "Title" is a special type of a shape called 'placeholders' with special behaviors. For example, they cannot be grouped either.

**Comment by Kenneth-LJS** [comment]
@damithc Makes sense. I'm now catching it so that users will not see the raw exception.
