### ISSUE TITLE
Add links to reviews

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1301]
Add these to our list of reviews if they are not in the list already
https://www.softzsolutions.com/blog/6-cool-powerpoint-slide-design-tools
https://www.ronapresentasi.com/add-ins-powerpoint-gratis/
https://www.td.org/Publications/Blogs/L-and-D-Blog/2017/03/Best-of-2017-the-Top-7-Powerpoint-Downloads
http://www.homeppt.com/ru/articles/powerpoint-labs-highlight-slide-content-using-spotlight-animations.html
http://www.presentasi.net/aplikasi-presentasi-powerpoint/
https://www.td.org/Publications/Blogs/L-and-D-Blog/2017/03/Best-of-2017-the-Top-7-Powerpoint-Downloads

**Comment by kai33** [comment]
Cool, our user base is so international

**Comment by damithc** [comment]
https://myelearningworld.com/11-free-powerpoint-add-ins-and-plugins/

**Comment by VamsiSangam** [comment]
Can I work on this?
