### ISSUE TITLE
About dialog: make text selectable

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1303]
![image](https://cloud.githubusercontent.com/assets/1673303/25778145/e3da86a4-3327-11e7-8da7-d4250fe66b60.png)

Suggested: make the test select-able
Justification: Easier to copy-paste version when reporting bugs

**Comment by IanTeo** [comment]
If I am not wrong, we can just use ctrl-c to copy the text while the dialog is selected

**Comment by damithc** [comment]
I didn't realize that. Even then, I'd rather select the version number and copy it rather than copy the entire text. Plus, other users might not realize the text could be copied in the current way (I didn't :-p)
