### ISSUE TITLE
Progress for public release

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1319]
Documentation (in Google Drive):
- [x] Positions Lab - Last edited: 30 May 2017
- [x] Resize Lab (Requesting for reviews) - Last edited: 11 May 2017
- [x] Sync Lab  - Last edited: 30 May 2017
- [x] Crop Lab - Last edited: 29 May 2017
- [x] Paste Lab - Last edited: 23 May 2017
- [x] Timer Lab - Last edited: 29 May 2017
- [x] Shortcuts Lab (context menu) - Last edited: 26 May 2017

Tutorials (in Google Drive):
- [x] Positions Lab - Last edited: 25 May 2017
- [x] Resize Lab - Last edited: 25 May 2017
- [x] Sync Lab - Last edited: 25 May 2017
- [x] Crop Lab - Last edited: 25 May 2017
- [x] Paste Lab - Last edited: 25 May 2017
- [x] Timer Lab - Last edited: 25 May 2017

Unit/Functional Tests:
- [x] Positions Lab
- [x] Resize Lab
- [x] Sync Lab - #1344 
- [x] Crop Lab
- [x] Paste Lab - #1361 
- [x] Timer Lab - #1347 

Icons:
- [x] Positions Lab
- [x] Resize Lab
- [x] Sync Lab - #1376 
- [x] Crop Lab
- [x] Paste Lab - #1369 
- [x] Timer Lab

**Comment by IanTeo** [comment]
@AngShiYa Could you do a review for the Timer Lab documentation?
@Skaty Could you do a review for the Paste Lab documentation?
@jamos-tay Could you do a review for the Crop Lab documentation?

**Comment by jamos-tay** [comment]
@IanTeo Okay have looked through and made corrections. Just a minor detail which I added as a comment.

**Comment by AngShiYa** [comment]
@IanTeo Sure. It looks good. Added a comment for the timer's position.

**Comment by IanTeo** [comment]
@Kenneth-LJS Could you do a review for the Sync Lab documentation?

**Comment by IanTeo** [comment]
Thanks for the review @jamos-tay @AngShiYa

**Comment by initialshl** [comment]
@jamos-tay Thanks! Do you still have the slides for the documentation?
