### ISSUE TITLE
Paste To Fill Slide does not maintain aspect ratio and crop to slide

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1325]
For Paste To Fill Slide, the result should maintain its aspect ratio (not stretched) and areas which exceed the slide boundaries should be cropped away.

For one picture:
Test:
![1](https://cloud.githubusercontent.com/assets/19281538/25931489/24bc19b6-363f-11e7-9c35-8a89f461bc8f.PNG)
Expected:
![2 5](https://cloud.githubusercontent.com/assets/19281538/25931550/78980dec-363f-11e7-87ba-913ee60dae0f.PNG)
Actual (not cropped to slide):
![2](https://cloud.githubusercontent.com/assets/19281538/25931537/6ca0ca42-363f-11e7-865a-2519dccd23dd.PNG)

For a group:
Test:
![3](https://cloud.githubusercontent.com/assets/19281538/25931574/90cde828-363f-11e7-9747-339ef00099cc.PNG)
Expected:
![4 5](https://cloud.githubusercontent.com/assets/19281538/25931626/f9508a36-363f-11e7-866b-fdc478753e23.PNG)
Actual (aspect ratio not maintained):
![4](https://cloud.githubusercontent.com/assets/19281538/25931579/9c477dea-363f-11e7-9b8a-b802809cc87b.PNG)

For multiple pictures:
Test:
![1](https://cloud.githubusercontent.com/assets/19281538/25932142/c913882a-3642-11e7-9121-aa9b88dbc55b.PNG)
Expected:
![3](https://cloud.githubusercontent.com/assets/19281538/25932143/cd1b30bc-3642-11e7-972b-b329e71a21c6.PNG)
Actual:
![2](https://cloud.githubusercontent.com/assets/19281538/25932145/d24ab864-3642-11e7-8ca5-f9b808414db5.PNG)

**Comment by IanTeo** [comment]
@damithc what do you think about cropping the image automatically when user uses "paste to fill slide"? I think that it is better than stretching the image to fill the slide.

**Comment by damithc** [comment]
Yes, cropping is fine if it's not permanent (i.e. user can adjust later).
