### ISSUE TITLE
Timer Lab: Recreated timer does not update timer properties

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1332]
Steps to reproduce:
1. Create timer
1. Drag timer body and click `Create`
1. Message says only one timer is allowed, and the timer is resized to the timer body

Expected: The properties Width and Height should update to the new value
Actual: The properties Width and Height values remain the same

<img src="https://cloud.githubusercontent.com/assets/19281538/26040532/ca2fb170-3958-11e7-978b-3065a9bbaa71.PNG" width="400">

<img src="https://cloud.githubusercontent.com/assets/19281538/26040538/d8a27c24-3958-11e7-9502-b00be4c2dfeb.PNG" width="400">

<img src="https://cloud.githubusercontent.com/assets/19281538/26040539/d9ab35ac-3958-11e7-93fc-8a22503ecafb.PNG" width="300">

**Comment by damithc** [comment]
On a related note, may be the dialog should allow user to choose whether to keep the existing timer (and abort the add opreation) or go ahead and add a new timer.
