### ISSUE TITLE
Crop Lab: Add "Follow First Picture" for CropToAspectRatio

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1342]
Enhancement suggested on Crop Lab Documentation:

"Crops all remaining pictures to match aspect ratio of the reference (first selected) picture".

**Comment by initialshl** [comment]
@damithc Do you think it might be better to autofill the `Custom` aspect ratio inputs with the aspect ratio of the first selected object?

**Comment by damithc** [comment]
Yes, that works too.
