### ISSUE TITLE
Paste Lab: Merge Into Group design considerations

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1345]
"Merge into Group" (Paste Lab) does not do any pasting, should it be moved out of Paste Lab? It should be more closely related to "Convert To Picture" type of features. 

I think it should be moved out so that it is clearer for the user and makes the Paste Lab code more consistent.

**Comment by initialshl** [comment]
@damithc Can i have your comments on this?

**Comment by damithc** [comment]
Sure.
