### ISSUE TITLE
Paste Lab: Exception when merging object and group

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1352]
When using `Merge Into One Group`, an uncaught exception occurs when I select an object, followed by a group and use `Merge Into One Group`. No exception happens when I select 2 groups, 2 objects or a group followed by an object

**Comment by IanTeo** [comment]
It seems that this bug only occurs after triggering the bug for issue #1354

**Comment by damithc** [comment]
Similar thing happened to me. Here's the error message. Win7, PPT2010
![image](https://cloud.githubusercontent.com/assets/1673303/26300972/4ded99f0-3f12-11e7-8575-ae9bc11981f3.png)

**Comment by damithc** [comment]
I get a similar error when I copy an image from Chrome and try to `Paste into group`
