### ISSUE TITLE
Paste Lab exception when clipboard has Slide objects

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1380]
When the clipboard has an entire slide copied, using Paste Lab features will cause an exception.

![capture](https://cloud.githubusercontent.com/assets/19281538/26485919/76379d4a-422b-11e7-89ce-65110729620e.PNG)

**Comment by damithc** [comment]
It would be cool if we an use the 'picture' version of the slide in this case (i.e. what you get if you use PowerPoint's  'paste as picture' option), but not strictly necessary.

**Comment by IanTeo** [comment]
But what if the user copies multiple slides? I think PowerPoint only pastes the first slide as a picture

**Comment by damithc** [comment]
> But what if the user copies multiple slides? I think PowerPoint only pastes the first slide as a picture

We can follow what PowerPoint does. In any case, it can be a separate issue.

**Comment by initialshl** [comment]
I wonder what the best behavior should be.

I tried to implement pasting a copied slide as a picture, but it seems to be a little slow, especially for Paste To Fill Slide which takes about 5 seconds. 

Having multiple slides copied will cause exception, even when calling the Office API Paste() function, so it can only be caught and do nothing, or give a warning.

PowerPoint's `ctrl+v` by default pastes the copied slides as separate slides, leaving the current slide objects unmodified.

**Comment by blewjy** [comment]
Tested on PPT2016, seems like this is resolved. Closing issue.
