### ISSUE TITLE
Tweaks to user docs

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1397]
Few minor things I noticed from a quick skim

1. References to PPT features: format consistently?
![image](https://cloud.githubusercontent.com/assets/1673303/26662441/6e2f063a-46b6-11e7-8909-a2d33f76562e.png)

2. As discussed, revise the first example of the Paste Lab to mention copying pictures from elsewhere.

3. We use `ctrl-click` but `ctrl+c`. Should be make it consistent?

4. Use `code formatting` or _italics_ when we refer to a feature/text in the software? If we use the normal formatting, the sentence become harder to read.
![image](https://cloud.githubusercontent.com/assets/1673303/26663328/925641e4-46bc-11e7-9882-4cc5a85208c5.png)

5. I would use the same formatting for option value as well as option name.
![image](https://cloud.githubusercontent.com/assets/1673303/26663475/7a0ca410-46bd-11e7-9680-87b16fa7db90.png)

6. If you have the source slides, you can add light blue dotted lines to show the angles we are talking about here. Also, show a screenshot of the options being referred to?
![image](https://cloud.githubusercontent.com/assets/1673303/26663559/1e104ef4-46be-11e7-8f1f-346b9f690f27.png)

7. Make these two same size?
![image](https://cloud.githubusercontent.com/assets/1673303/26665678/f40b1fca-46cd-11e7-9b70-ddaa8006c806.png)

8. Consider giving a step-by-step explanation in tandem with the pictures. On a related note, may be we should rename the button to `CREATE/UPDATE` (in a future release)?
![image](https://cloud.githubusercontent.com/assets/1673303/26665806/aa1e08d6-46ce-11e7-8531-dc8877efe059.png)

**Comment by initialshl** [comment]
Discussion with @IanTeo :

1. Italicize powerpoint's native feature

3. ctrl-anything

4. Bold all

5. `Code` all since they are radio button text

6. new screenshots

7. add trasparent padding to the left "Rotate" button
