### ISSUE TITLE
Ribbon button not enabled for ppt 2010

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1398]
Zoom lab and create spotlight do not become enabled on ppt 2010 after selecting the appropriate shapes

**Comment by damithc** [comment]
Seem to work for me for Version 2.9.1.1 [Release date: 25 May 2017]
Note that zoom lab requires rectangles.

![image](https://cloud.githubusercontent.com/assets/1673303/26668648/43100216-46dd-11e7-978d-f990e31fe38a.png)

**Comment by YuPeiHenry** [comment]
Unable to reproduce bug. Seems to work for me on PPT2010 as well. @damithc Should the issue be closed, or further investigation is required?

**Comment by damithc** [comment]
Can close if cannot reproduce.
