### ISSUE TITLE
Animate In Slide has weird behaviors when applying multiple times

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1400]
For objects A, B, and C,
select A, select B, deselect A, select C, and click `Animate In Slide`.

Without undoing,
repeat the steps and click `Animate In Slide`. 

This results in weird behaviors for animations.
This also occurs for `Zoom To Area`.

The desired behavior has to be discussed.

**Comment by blewjy** [comment]
Hi @initialshl, I am unable to reproduce this on Windows 10, PPT2016. Could you confirm if this bug is still present on the latest `dev-release`? Also, what are the 'weird behaviours' that you noticed? Thank you!

**Comment by initialshl** [comment]
Hi @blewjy, it seems to be fixed for me too. I will close this issue. Thanks.
