### ISSUE TITLE
Suggested new feature: Paste To Fit Slide

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1403]
As discussed today (for a future version):

A feature of Paste Lab. 
Paste the clipboard so that it fits the slide, similar to Paste To Fill Slide without the cropping.

**Comment by junkiattan** [comment]
@initialshl ,

when you mention without cropping, do you mean it is allow to exceed the size of the slide? or will it fill up as best as it can wile maintaining aspect ratio without exceeding the boundaries of the slide?

Note: for the latter case, I think the results would be more obvious for images orginally smaller then the slide

**Comment by initialshl** [comment]
It should be the latter
