### ISSUE TITLE
Remove tutorial from the installer

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1409]
In the interest of reducing the size of the installer/updater, we can exclude the tutorial file from the installer. Instead, we can popup a dialog with a link to the tutorial file. In addition, we can make that link available from our ribbon too.

**Comment by IanTeo** [comment]
I believe the current installer uses a link to the tutorial, instead of putting the actual tutorial in the file. So the size should not be an issue

**Comment by damithc** [comment]
I see. See if there is anything else we can do to reduce the size of the installer.
