### ISSUE TITLE
Shapes Lab context menu not dismissed when pane is closed

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1410]
1. Open Shapes Lab pane
1. Right-click on an empty area on the pane
1. Close the Shapes Lab pane

Actual: The context menu is still on the screen. 
Expected: It should be dismissed.

**Comment by yuhongherald** [comment]
The bug is no longer reproducible after porting PPL to use WPF over Winforms (unable to close the pane without dismissing the context menu) so I will be closing the issue.
