### ISSUE TITLE
Messages to user are not consistent

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1412]
Error message when there is no selection, from Effects Lab -> Blur Selected:
![capture](https://cloud.githubusercontent.com/assets/19281538/26715728/584de518-47a9-11e7-9cb5-0e221523aaa3.PNG)
(also has typo: two spaces before "required")

Error message when there is no selection, from Effects Lab -> Blur Remainder:
![asd](https://cloud.githubusercontent.com/assets/19281538/26715739/63a407da-47a9-11e7-94d4-592c36421315.PNG)
(also missing full stop)

**Comment by junkiattan** [comment]
Ill start working on this! @initialshl

**Comment by initialshl** [comment]
Ok

**Comment by junkiattan** [comment]
hey @initialshl ,

can I just double check with you whether this issue is just for EffectsLab? or for all the other error messages and strings in general?

**Comment by initialshl** [comment]
It should be consistent across all labs, we did some of them before i think, so just see if any of it requires changes
