### ISSUE TITLE
Design icons for new UI

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1420]
For PPTLabs 4.0.0.0, all buttons on the ribbon will be collapsed into their respective labs.
We will need to design new icons.

- [x] Animation Lab
- [x] Zoom Lab
- [x] Narrations Lab
  - [x] Generate Audio Automatically
  - [x] Record Audio Manually
- [x] Captions Lab
- [x] Highlight Lab
- [x] Paste Lab
    - [x] Paste To Fill Slide
    - [x] Paste At Cursor Position
    - [x] Paste At Original Position
    - [x] Replace With Clipboard
    - [x] Paste Into Group
- [x] Help
  - [x] User Guide
  - [x] Tutorial
  - [x] Report Issues / Submit Feedback
  - [x] About

**Comment by initialshl** [comment]
For Animations Lab icon: (not sure which one is better)
<img src="https://cloud.githubusercontent.com/assets/19281538/26811564/3eff9fda-4aa5-11e7-89c9-5b3e0bfffeae.png" width="300">

**Comment by damithc** [comment]
Most of the animations we target are about movement, so I prefer the 2nd one that gives a hint of movement.

**Comment by initialshl** [comment]
For Zoom Lab:
<img src="https://cloud.githubusercontent.com/assets/19281538/26812345/bc95d9ba-4aa9-11e7-8b6c-7a4af7af2711.png" width="320">

**Comment by initialshl** [comment]
<img src="https://cloud.githubusercontent.com/assets/19281538/26814977/f6f37db2-4abb-11e7-92f4-1b38f8d5da97.png" width="350">
<img src="https://cloud.githubusercontent.com/assets/19281538/26814976/f6f25dba-4abb-11e7-872f-8912938da14c.PNG" width="280">

**Comment by initialshl** [comment]
![123](https://cloud.githubusercontent.com/assets/19281538/26815495/412cb26a-4abf-11e7-8247-f74094cb1d23.PNG)

**Comment by initialshl** [comment]
![1](https://cloud.githubusercontent.com/assets/19281538/26816781/0a954d0a-4ac6-11e7-85e8-6e355140e80d.PNG)

**Comment by initialshl** [comment]
![wqdq](https://cloud.githubusercontent.com/assets/19281538/26818161/2f3aac4e-4acc-11e7-9995-609299f539a8.PNG)

**Comment by initialshl** [comment]
![123](https://user-images.githubusercontent.com/19281538/26869492-37d0cc66-4b9f-11e7-8bee-5d4c7a3f5bc3.PNG)

**Comment by initialshl** [comment]
![111](https://user-images.githubusercontent.com/19281538/26873006-0ce573e2-4bab-11e7-8274-084470107b2f.PNG)
