### ISSUE TITLE
Improve error message for Effects Lab

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1422]
Using magnify on a picture results in the following error message:

![image](https://cloud.githubusercontent.com/assets/12381148/26817893/039c0c00-4acb-11e7-8fc6-bc439f871213.png)

We should improve the error message so that the user knows that he should not use magnify on an image.

**Comment by initialshl** [comment]
Duplicate of #1412 
Closing issue.
