### ISSUE TITLE
Fit To Height/Width on the context menu should belong to Resize Lab

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1436]
Before Positions Lab was created, there was a Fit To Height/Width command on the context menu. 
Now, with Positions Lab, the Fit To Height/Width feature is obsolete, as it is a lot less powerful than the Positions Lab's version.

I can think of 2 possible solutions:
- Call Positions Lab's version of the command from the context menu instead
- Remove this feature from the context menu

Personally, I think that the latter is better, as the user will not have control of the anchor point from the context menu. @damithc @initialshl what do you think?

**Comment by damithc** [comment]
OK to remove
