### ISSUE TITLE
Standardize english in code base

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1469]
Different versions of the same word are used within the code base. We should stick to one version of the word. I propose we use American English for our code base.

We should fix the following:
- [x] Synchronise -> Synchronize
- [x]  Colour -> Color
- [x] Grey -> Gray

If anyone spots any other discrepancies in the code base, feel free to make a comment here

**Comment by damithc** [comment]
Yes, American English preferred

**Comment by yuhongherald** [comment]
In `EffectsDesignerTest`, there is a reference of grey from the metadata which cannot be removed
