### ISSUE TITLE
Update PowerPointLabs website front page

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1473]
The website's front page should be updated with the new features, and categorized into their respective labs.

**Comment by initialshl** [comment]
Timer Lab:
![timerlab-gif](https://user-images.githubusercontent.com/19281538/27573515-cc109258-5b44-11e7-9800-0135080c9975.gif)

Sync Lab:
![synclab-gif](https://user-images.githubusercontent.com/19281538/27573541-f0aff216-5b44-11e7-8f63-46b0280d0ae5.gif)

Paste Lab:
![pastelab-gif](https://user-images.githubusercontent.com/19281538/27573571-148d8d92-5b45-11e7-9b0c-24b2300783b8.gif)

**Comment by damithc** [comment]
To be consistent, use the limited color palette used by the other gifs. 
I used this tool to cover to gif https://free_video_to_gif_converter.en.softonic.com/ if it helps
