### ISSUE TITLE
Replace FitToSlide with ResizeLab version

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1494]
FitToSlide has been removed as the ResizeLab version of the feature is more robust.
However, FitToSlide cannot be removed as the code base still has some other features that are using FitToSlide. We should replace all these instances with the ResizeLab version and remove FitToSlide.

**Comment by AlexFJW** [comment]
If I'm not wrong, ResizeLab uses FitToSlide internally. ResizeLab's functions act on ShapeRange objects while FitToSlide's functions act on Shape objects. Am I'm missing something here?

**Comment by yuhongherald** [comment]
ResizeLab itself depends on `FitToHeight` and `FitToWidth` from `FitToSlide` as well. I think it is better that they stay separate, as ResizeLab's methods are for `ShapeRange` while `FitToSlide` methods are for `Shape`s as alex has pointed out.
