### ISSUE TITLE
Embedded slide causes bugs

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1507]
1. Open Office Word
1. Insert -> Object -> PowerPoint Slide
1. Add objects on the slide
1. Close PPT
1. Right-click embedded slide on Word -> Open
1. Continue...

Alternatively:
1. Open Office Word
1. Insert -> Object -> PowerPoint Slide
1. Make sure PowerPoint ribbon is shown (in Word) by selecting/double-clicking the embedded slide
1. Continue...

a) Shapes Lab does not open properly on PPT 2016 (worked on PPT 2013):
![a1](https://user-images.githubusercontent.com/19281538/28001407-ca199804-655e-11e7-9878-71b66305de08.PNG)

b) ReplaceWithClipboard/PasteAtOriginalPosition/PasteIntoGroup causes exception:
![a2](https://user-images.githubusercontent.com/19281538/28001408-cb45f7e0-655e-11e7-9462-ac44d4132354.PNG)

c) Some other features may not work too, needs more testing.

**Comment by ChesterSng** [comment]
Testing using tutorial.pptx, opened it from microsoft word and a.) and b.) works. (Office 365 / Powerpoint 2016)

**Comment by initialshl** [comment]
Can anyone else verify/try it on other ppt versions?

**Comment by damithc** [comment]
> Testing using tutorial.pptx, opened it from microsoft word and a.) and b.) works. (Office 365 / Powerpoint 2016)

I don't think it requires an existing pptx file. It's about embedding a slide, not a pptx file.

> Can anyone else verify or try it on other ppt versions?

No error in PPT 2016

**Comment by damithc** [comment]
tried on PPT 2013. Cannot reproduce.

**Comment by initialshl** [comment]
Cannot reproduce on my ppt 2016 as well. 
Not sure what fixed it.
Issue closed.
