### ISSUE TITLE
Refactoring: TextCollection should be organized into their respective labs

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1514]
Also needs to consider whether the text classes should be put into their respective labs folder, or a textcollection folder.
e.g. CropLab/CropLabText.cs or TextCollection/CropLabText.cs

A few options:

- Use a namespace 
```
namespace PowerPointLabs.TextCollection
{
    internal static class CropLabText { ... }
}
using PowerPointLabs.TextCollection;
string str = CropLabText.CropToShapeTooltip;
```
Pros: Separate TextCollection class for each lab, more readable when using the strings
Cons: 

- Use partial class
```
TextCollection.CropLabText.cs
internal static partial class TextCollection
{
    public static string CropLabCropToShapeTooltip = "";
}
string str = TextCollection.CropLabCropToShapeTooltip;
```
Pros: A single class for all text
Cons: Needs to prefix the lab into the variable names, little difference from now other than file organization

**Comment by IanTeo** [comment]
I think we should go with the first one (Use a namespace)
