### ISSUE TITLE
Testing: Implement a way to get WPF control handles

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1525]
We currently have ways to get WinForm handles (Test.Util.MessageBoxUtil.ExpectMessageBoxWillPopUp()), but our UI have been converted into WPF. 

We need a way to get the WPF control handles so that we can send message (such as clicking the OK button) to Settings Dialogs and other WPF dialogs.

**Comment by leeyh20** [comment]
@initialshl  I saw this existing code in SyncLabController,
```
UIThreadExecutor.Execute(() =>
                {
                    _pane.SyncPaneWPF1.Dialog.okButton.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));
                });
```
Does this already solve the problem of getting the WPF control handles?

**Comment by initialshl** [comment]
Hm maybe @IanTeo can answer this

**Comment by yuhongherald** [comment]
I noted that all windows created are derived from System.Windows.Window from my PR on #1902 . Will be looking deeper into the code.
