### ISSUE TITLE
Convert to picture for shapes in a group

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1531]
Currently, we a shape in a group is selected for convert to picture, the entire group is converted to picture. We should convert the selected shape(s) only, instead of the entire group.

We can use EditName as a reference for this implementation. It might be difficult as we have to regroup the items

**Comment by junkiattan** [comment]
@IanTeo 

I do not understand how to replicate this situation. After I group shapes, I can no longer select the individual shapes to convert to picture. If I were to group shapes together and convert to picture, I would expect all to be converted. Perhaps you can elaborate a little on how to select individual shapes?

**Comment by yuhongherald** [comment]
I also don't seem to be able to replicate the situation. Closing the issue.

**Comment by damithc** [comment]
I can reproduce the issue.
1. Group a bunch of shapes
2. Select one of the shapes. This requires clicking on the group and then clicking on the specific shape again.
  ![image](https://user-images.githubusercontent.com/1673303/60800632-1dea9000-a1a8-11e9-8917-ca434c8700a3.png)

3. Right-click on the selected shape and select 'Convert to picture'. The whole group is converted to a picture, not just the selected image.

**Comment by yuhongherald** [comment]
Ok noted. Will take a look
