### ISSUE TITLE
Create Spotlight does not work on Placeholder objects

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1536]
![capture](https://user-images.githubusercontent.com/19281538/28601106-dfd2d9ee-71e8-11e7-8987-ea35e1b947f9.PNG)

If it cannot be fixed, it should be disabled when a Placeholder is selected (similarly to many other features that do not work with Placeholders).

**Comment by damithc** [comment]
Disable or give error message? Otherwise users might be confused as to why. Also, a possibility is to simply to create a duplicate box that matches the placeholder size and then use that for the spotlight feature.

**Comment by yuhongherald** [comment]
#1915 adds a method to past placeholders as lookalikes, `SafeCopyPlaceholder`
