### ISSUE TITLE
PPTLabs does not install on computer with both PPT 2007 and PPT 2016

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1537]
A user with PPT 2007 and PPT 2016 installed on his computer was unable to install PPTLabs.
Upon completion of installation, Tutorial.pptx was opened in PPT 2007 and PPTLabs does not exist on either versions.

This is most probably related to the registry key on which version of PPT is the user's default.

**Comment by damithc** [comment]
Problem too rare to worth fixing. Closing.
