### ISSUE TITLE
Cannot open PPTLabs on PPT 2010

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1539]
A user was unable to use PPTLabs, as he encounters an error upon opening PowerPoint 2010.

```
The error occurs 100% of the times upon opening PowerPoint.
After this error, the menu of Labs is shown, but it does nothing (seems that it affects hooking to your code?)
The error is caused after installing all the latest packs, via the “Microsoft Office Configuration analyser” tool… which basically gets al updates released.
```

![image001](https://user-images.githubusercontent.com/19281538/28608105-a757d74e-7211-11e7-80a6-b10a549d6a2f.png)
![image002](https://user-images.githubusercontent.com/19281538/28608108-a9683c9a-7211-11e7-9612-b2ebed639253.png)

**Comment by kai33** [comment]
may be related to this:
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/Ribbon1.xml#L534

ref:
http://suyamasoft.blue.coocan.jp/WordVBA/Ribbon/ContextMenuID/index.html
no ContextMenuVideo

**Comment by kai33** [comment]
this issue requires an analysis to find out which menu item is likely not supported by Office10

**Comment by initialshl** [comment]
@IanTeo Do u mind debugging this on your PPT 2010?

**Comment by IanTeo** [comment]
I tested it on my version of ppt 2010 and it works fine

**Comment by initialshl** [comment]
Does it break anything if we just delete that block of code?

**Comment by IanTeo** [comment]
I tried the offline installer, online installer and building from visual studio. All of them can compile and have the context menu for video

**Comment by IanTeo** [comment]
Nothing really, just that we won't have a context menu for video objects. Also, we cannot be certain that deleting that line of code will solve the problem since we cannot recreate the problem to test

**Comment by IanTeo** [comment]
The error message seems to point to ContextMenuVideo.. but the line number it pointed out is for ContextMenuFrame.. This seems weird to me. Any thoughts on that? @initialshl @kai33

**Comment by initialshl** [comment]
The line number is correct at this history: https://github.com/PowerPointLabs/PowerPointLabs/blob/fdc6d5a4f575cd66485cb50f7b56304ae3d7515a/PowerPointLabs/PowerPointLabs/Ribbon1.xml

**Comment by initialshl** [comment]
> ref:
> http://suyamasoft.blue.coocan.jp/WordVBA/Ribbon/ContextMenuID/index.html
> no ContextMenuVideo

The user's error is "Failed to find Office control by ID: ContextMenuVideo"

Since ContextMenuVideo (and maybe some others) are not supported in some PPT 2010, we can either do a check for 2010 and add/remove the XML (somehow) or just remove them if they are unused?

**Comment by IanTeo** [comment]
i think as a temporary measure, lets remove the codes first and figure out how to do the check. Should we push directly to master and release or put it in dev first?

**Comment by initialshl** [comment]
PR to dev i guess, we wouldn't want dev to be behind master

**Comment by IanTeo** [comment]
@kai33 this source says that ContextMenuVideo exists for 2010. http://youpresent.co.uk/idmso-control-list-powerpoint-2013-2010/

Also, I am having no issues with my ppt 2010.. I have my doubts that removing that menu item will fix the users problem too. Should we just try to remove it and ask the user to check? (Since I cannot test it)

**Comment by initialshl** [comment]
> this source says that ContextMenuVideo exists for 2010. http://youpresent.co.uk/idmso-control-list-powerpoint-2013-2010/

It says '0' for Exists column under PPT 2010, i think it doesnt?

**Comment by IanTeo** [comment]
Ok will remove it and push to master as a temp fix
