### ISSUE TITLE
Spotlight Enabled causing exception on presentation open

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1543]
SpotlightEnabled function causes exception when opening a PowerPoint document.

```
System.Runtime.InteropServices.COMExceptionApplication (unknown member) : Invalid request.  
There is no currently active document window.
Stack Trace:   
at Microsoft.Office.Interop.PowerPoint._Application.get_ActiveWindow()   
at PowerPointLabs.Models.PowerPointCurrentPresentationInfo.get_CurrentSelection()   
at PowerPointLabs.ActionFramework.Common.Extension.ActionFrameworkExtensions.GetCurrentSelection()   
at PowerPointLabs.ActionFramework.Common.Extension.BaseHandlerExtensions.GetCurrentSelection(BaseHandler handler)   
at PowerPointLabs.ActionFramework.EffectsLab.AddSpotlightEnabledHandler.GetEnabled(String ribbonId)   
at PowerPointLabs.ActionFramework.Common.Interface.EnabledHandler.Get(String ribbonId)
```
Occurs at https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ActionFramework/EffectsLab/Spotlight/AddSpotlight/AddSpotlightEnabledHandler.cs#L16, we may need to debug whether this happens for all enabledhandlers, and handle exceptions in a helper method when nothing is selected (for all enabled handlers).

https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/ThisAddIn.cs#L955 also seems to have duplicate Ribbon.RefreshRibbonControl("AddSpotlight") and Ribbon.RefreshRibbonControl("AddSpotlightButton"), the unused one should be removed.

**Comment by junkiattan** [comment]
hey @initialshl 

I have removed duplicate Ribbon.RefreshRibbonControl("AddSpotlight").

However with regards to the other problem, I cannot replicate the exception you are reporting. I have tried to open a powerpoint document

**Comment by initialshl** [comment]
Not sure how or on what environment/OS this exception occurs, may need to follow-up with the user on support forum.

**Comment by junkiattan** [comment]
@initialshl 

I have emailed the person who submitted the error report to ask for more details. Will act on his reply

**Comment by leeyh20** [comment]
Might want to see this https://support.microsoft.com/en-hk/help/285472/run-time-error--2147188160-on-activewindow-or-activepresentation-call

**Comment by leeyh20** [comment]
It might also occur when powerpoint is in slideshow mode https://stackoverflow.com/questions/30877027/powerpoint-vba-no-currently-active-document-window
