### ISSUE TITLE
Copy operation made the text disappear

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1544]
PPT 2013, Win 10, PL Version 4.1.1.2
Steps:
1. Select shape given below and click on the `copy` button
2. The text in the box disappeared (possibly changed to black color?)
3. After completing the copy operation,  I was able to get the text back with one `Ctrl+Z` without losing the copied styles

![image](https://user-images.githubusercontent.com/1673303/29395805-34ebd002-8346-11e7-9067-d47ff5d4f4a0.png)

**Comment by IanTeo** [comment]
I think the problem is that we are unable to detect different colors in a single textbox. In this case, where the textbox has yellow and white, I think the color returned by the API is black. (Anytime there is a mixture of colors they return black if I am not mistaken)

**Comment by IanTeo** [comment]
For the built in format painter of powerpoint, I think they follow the color of the first letter. Maybe we could do the same if we are unable to detect the color of each "section"

**Comment by damithc** [comment]
To be clear, the color of the _original_ text changes to black as soon as I hit the copy button (to open the style picker dialog). As a user, it's quite expected to see a copy operation modify the source :-)
