### ISSUE TITLE
SyncLab: support placeholder objects

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1554]
Currently does not work for placeholder objects such as the slide title. Works only for normal objects.

**Comment by AlexFJW** [comment]
Not sure we can support placeholder objects, as programmatic copy/paste of placeholders doesn't seem to work. This breaks SyncLab's shape storage mechanism, which is crucial for SyncLab.

**Comment by damithc** [comment]
> I'll try to see if I can work around this.

Git it a try. We _do_ use a lot on workarounds. :-p In the worst case we should at least inform the user why it doesn't work e.g. error message when a user tries to use synclab with a placeholder.
