### ISSUE TITLE
Show a bigger logo in the landing page

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1555]
It just occurred to me that our website landing page doesn't show the product name 'PowerPoint Labs' in any eye catching form :-p

**Comment by junkiattan** [comment]
Hey @damithc ,

just some clarification, when you meant bigger logo in the landing page, were you referring to 1 or 2?
<img width="946" alt="capture" src="https://user-images.githubusercontent.com/16800272/35159071-136d2fc2-fd74-11e7-8446-c74f98ca2a24.PNG">

**Comment by damithc** [comment]
> just some clarification, when you meant bigger logo in the landing page, were you referring to 1 or 2?

1
2 is of right size but it doesn't contain the product name.
