### ISSUE TITLE
Refactor "global" variables in RibbonUI

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1559]
Some variables are put in Ribbon1.cs for legacy reasons and accessed using this.GetRibbonUI().HighlightBulletsEnabled, but this should be changed into their own labs.

Refer to https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/Ribbon1.cs#L122

**Comment by leeyh20** [comment]
Will start on this!
