### ISSUE TITLE
SyncLab: Design Decisions & Documentation

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1564]
The code in Format.cs & related FormatTypes (FIllFormat.cs etc) files are somewhat unconventional, and a little hard to understand since there's a lack of documentation. FormatTypes are written as static utility classes rather than something more OOP and its not quite clear why this was done. We lose out on type safety which comes with an OOP approach.

@initialshl 
Could you share your thought process while writing the code? I'm guessing something related to performance, but I can't quite tell from the code alone.

//Edit
Aside from design decisions, the code could do with some documentation as well. There are implicit assumptions present that only become clear after grokking the code. Making these explicit will help reduce bugs in the long run.

**Comment by initialshl** [comment]
I agree. Not sure why this was done, you may have to ask @ianteo

**Comment by alexfjw** [comment]
https://github.com/PowerPointLabs/PowerPointLabs/blob/083412594031515704fcafa133980b57b4635792/PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/FillFormat.cs#L12-L18

I can't figure out why FillFormat duplicates the object in the `CanCopy(..)` function and then syncs to check if copying is possible, while other format files do so without duplicating the object. 
Again, I'm guessing its to do with safety but I can't tell what the exact issue is. I'd like to add some documentation or perhaps a note for future investigation if time permits.

@IanTeo Any clue?

**Comment by alexfjw** [comment]
Refactoring was completed in #1618.
Duplicating is done for convenience. 

Closing as most issues have been addressed.
