### ISSUE TITLE
Design Decision: SyncLab has no persistent data while ShapesLab will save shapes

### ISSUE THREAD

**Issue by leeyh20** [PowerPointLabs/PowerPointLabs#1567]
I believe it could be worth it to allow SyncLab have persistent data just like ShapesLab especially if #1501 Generic Storage Framework is done. 

Was there a reason why SyncLab is only temporary?

**Comment by IanTeo** [comment]
We were actually questioning if persistent data was needed, as persistent data would mean that the user needs additional space on their disk. Of course, if you can see the potential use of having persistent storage, you are free to propose and implement it.

**Comment by yuhongherald** [comment]
Since there is no new functionality for SyncLab that requires persistent data, the issue will be closed for now
