### ISSUE TITLE
Support syncing properties of pictures

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1569]
Can the sync lab support syncing properties of pictures e.g. size, position ?

**Comment by alexfjw** [comment]
Probably a good idea to clearly document what sync lab can and cannot support.
I'll work on this concurrently with #1554

**Comment by IanTeo** [comment]
I believe sync lab supports syncing position and size properties for pictures, but nothing else.

**Comment by damithc** [comment]
> I believe sync lab supports syncing position and size properties for pictures, but nothing else.

I tried with a picture selected and it gave an error message when I clicked the 'copy' button.

**Comment by alexfjw** [comment]
> I tried with a picture selected and it gave an error message when I clicked the 'copy' button.
Copying was set only to work with lines, auto-shapes and textboxes.

**Comment by alexfjw** [comment]
Looks like pictures don't have much unique settings to sync.
Alongside ensuring that position works, I'll be only adding ColorType (the type of color transformation applied to the picture).

The more commonly used settings with pictures are shape effects. Shape effects apply to all shapes. They have been listed out in #1213. 

Picture specific settings that I don't think we should support:
- Brightness
- Contrast
- Crop details
- TransparencyColor (which color to set transparent)
