### ISSUE TITLE
UX for ZoomLab

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1575]
As of now, the user has to add a shape into the powerpoint and select it, before any of the zoom buttons are available. 

It is something you can get used to, but it doesn't really feel right on first use, going against the flow of wanting to add zoom. This might not leave a good first impression to users.

Would changing the UX help here? Perhaps automatically creating a zoom box (a rectangle shape) for the user when he selects "Zoom to Area", or something along those lines. We can add text into the zoom box to provide usage instructions as well.

![screen shot 2018-01-25 at 10 11 32 am](https://user-images.githubusercontent.com/11351531/35367216-41f41ef8-01b8-11e8-8cbc-d262408c1361.png)

**Comment by damithc** [comment]
This concern applies to other features as well. Our method is to disable a feature unless the prerequisite for that feature is fulfilled. Users can see a description of the prerequisite from the tool tip of the feature. 
Alternatives:
1. Keep the feature enabled, but give an explanatory error message when clicked if the prereqs are not fulfilled. If we do that, we have to do that for all features, to be consistent.
2. Generate some sort of default upon clicking (as you have suggested). This is extra work for us and sometimes extra work for the user. For example, in this case the user has to adjust the generated box to match his need, delete the generated zoom slides, and reapply the zoom feature.
Admittedly, the current way is not exactly noob-friendly, but PPL is not exactly for noobs either. :-p So, although not exactly ideal, the current way is less work and consistent across the features.

**Comment by alexfjw** [comment]
Thanks for the clarification @damithc. 
Just a thought, would there be value in adding a "create zoom box" button? (really just a shortcut to create box, so the user doesn't have to spend 2 or 3 clicks to create one ) 

The crux of the suggestion above was to make zoomlab more localized, in the sense that the user can get everything she needs from the zoomlab drop down menu alone. Thinking of wanting to zoom, a user may instinctively click the zoomlab ribbon, only to remember that you need to create a box first.

The gains for adding the above button aren't that great if we weigh costs involved (generating new screenshots for docs) so maybe this can be postponed till we make more changes to zoomlab. Or we could scrap this altogether 😋

**Comment by junkiattan** [comment]
Refer to #1577
