### ISSUE TITLE
FT_ColorsLabTest failing for PowerPoint 2016

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1582]
@leeyh20 @alexfjw 

There seems to be some trouble with FT_ColorsLabTest on my version of PowerPoint (2016). Do you guys have any issues with this?

> Test Name: FT_ColorsLabTest
> Test FullName: Test.FunctionalTest.ColorsLabTest.FT_ColorsLabTest
> Test Source: C:\Users\Jun Kiat Tan\Documents\GitHub\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ColorsLabTest.cs : line 23
> Test Outcome: Failed
> Test Duration: 0:00:24.5598684
> 
> Result StackTrace:
> at Test.FunctionalTest.ColorsLabTest.AssertEqual(Color exp, Color actual) in C:\Users\Jun Kiat Tan\Documents\GitHub\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ColorsLabTest.cs:line 157
> at Test.FunctionalTest.ColorsLabTest.TestFavoriteColors(IColorsLabController colorsLab) in C:\Users\Jun Kiat Tan\Documents\GitHub\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ColorsLabTest.cs:line 72
> at Test.FunctionalTest.ColorsLabTest.FT_ColorsLabTest() in C:\Users\Jun Kiat Tan\Documents\GitHub\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ColorsLabTest.cs:line 31
> 
> Result Message: Assert.IsTrue failed. diff color R, exp 165, actual 255
> 

This occurs whenever I run this test, even for the dev-release version. May need to look into it and rectify the test itself.

**Comment by initialshl** [comment]
Would recommend fixing this early, before more PRs are merged and it will become harder to find the source of error

**Comment by leeyh20** [comment]
That's weird, this test has never failed for me...

**Comment by alexfjw** [comment]
Same as leeyh20 here, no problems.

**Comment by junkiattan** [comment]
Okie. Apparently the error only occurs on my laptop.

I have asked @leeyh20 and @alexfjw to checkout my files (dev-release and my fix for #1412) and they both mentioned that the test is passing on their computers. However on my com, the dev-release is failing.

I will close this issue now because it only applies to my computer. Moving forward, any test that is color-related would have to be reviewed extensively by the others
