### ISSUE TITLE
Update Contributions.md to branch out from dev release instead of master for PRs

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1585]
@initialshl @IanTeo 

Referencing the [Contributions](https://github.com/PowerPointLabs/powerpointlabs/blob/master/.github/CONTRIBUTING.md) document, 

> git checkout master
git pull upstream master

The team and I were considering the pros and cons of branching from dev release instead of master when creating a branch for PRs. We think there would be less time solving merge conflicts this way.

For example, in the issue where all the dynamic data types is changed throughout the project, if we were to branch from master for subsequent issues, and modify certain lines, it would conflict with the solutions for other earlier issues.

@alexfjw @leeyh20

**Comment by initialshl** [comment]
Yes, i think we should branch from dev-release, that's what i do. Could consider updating Contributions.md
