### ISSUE TITLE
Captions Lab: Add ‘callouts’ support for the Audio Lab / Captions Lab

### ISSUE THREAD

**Issue by leeyh20** [PowerPointLabs/PowerPointLabs#1586]
Currently, captions are added to the bottom of the slide. Give an option to add them as callouts instead. The user can then resize/reposition them. We also need to honor those positions/sizes when regenerating callouts later, though we might not need storage for this. 

![image](https://user-images.githubusercontent.com/7023320/35680215-ab2249e0-0794-11e8-9ec6-b83cf570453a.png)

**Comment by leeyh20** [comment]
@damithc Sorry Prof Damith, didn't have time to finish this

**Comment by damithc** [comment]
> @damithc Sorry Prof Damith, I didn't have time to finish this

No worries. this is not urgent.
