### ISSUE TITLE
SyncLab: Error when opening on PPT2013

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1592]
Can't seem to open SyncLab on PPT2013, throws an error. 
Hope I can get some help verifying this. 
@leeyh20 @junkiattan 

![image](https://user-images.githubusercontent.com/11351531/35842418-ee2234fc-0b3c-11e8-805b-f5458e219be1.png)

**Comment by damithc** [comment]
Can open SyncLab on my Win10/PPT2013

**Comment by alexfjw** [comment]
Thanks Prof, could be my installation then. I'll try to figure it out.

**Comment by alexfjw** [comment]
Looks like it was a bad installer. Thanks for the help!
