### ISSUE TITLE
Error in Positions Lab tutorial

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1601]
> The Horizontal Distribution tutorial didn’t work correctly. It created duplicates as opposed to distributing by the order given in the tutorial.

Bug report from a user

**Comment by alexfjw** [comment]
@junkiattan Think this belongs in your department ;)

**Comment by leeyh20** [comment]
There's another bug report that was just submitted with the exact same problem.

> 
> I followed the tutorial and found some errors in Positions Lab. Objects are being duplicated. This occurs mainly in the Aling Horizontal and Distribute Horizontal buttons.
> 
> I am using Windows 10 x64 and Office Professional Plus 2016 (both in Portuguese - Brazil).

**Comment by junkiattan** [comment]
@alexfjw 

I have checked on 2013 and 2016 versions. There does not seem to be an error in the Align operations, only in the Distribute Horizontal buttons.

Will look into it

**Comment by damithc** [comment]
This one has similar problems (PPT2013)
![image](https://user-images.githubusercontent.com/1673303/36463164-f91b6442-1702-11e8-9f80-aa300730b093.png)
