### ISSUE TITLE
Paste Lab Error: PPT2013 PasteShapeFromClipboard method does not work

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1606]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/16800272/36188237-c1764660-1185-11e8-9c89-0a5ae7fd6dc9.png">

Steps to replicate:
1. Run PowerPoint 2013
2. Copy any image from the browser
3. Right-click and try to activate any PasteLab function

Exceptions:
Upon some tinkering, it was found that if you follow steps 1 & 2, but then instead of using PPTLabs directly, you default-copy into the slide first, copy/cut that image again, and then use the PasteLab functions, it will work.

I think it when the image is copied from the browser, the image is not registered in the clipboard or not read properly from the code. Only works for me when I re-copy/cut the image from inside PPT2013 again.

No problems for PPT2016 though.

@alexfjw @leeyh20 would need your help to check if this is the case on your versions of PPT2013 as well.

**Comment by alexfjw** [comment]
Actually, it seems to work for me on 13, but not on 10.

**Comment by leeyh20** [comment]
I think for mine, an error happened when I copied certain Twitter profile pictures but it did not happen when I randomly copied pictures from Youtube.

**Comment by leeyh20** [comment]
I might have a solution for this which is related to what I am doing for #1580. Let me test it more thoroughly and I might do a PR for this.

**Comment by leeyh20** [comment]
Could I try this issue since it is related to #1580?
