### ISSUE TITLE
Default templates for PRs

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1611]
It is possible to set the default text of PRs (and issues) in Github. See [link](https://github.com/blog/2111-issue-and-pull-request-templates).
We can use this feature to remind contributors to test their code on before creating a PR and also to enforce usage of github keywords so issues will automatically be closed when PRs are merged.

A bunch of OSS use this feature, was wondering if we should try it out as well.

**Comment by damithc** [comment]
Can try. We use that in TEAMMATES; some people still don't follow, but better than nothing :-p

**Comment by Skaty** [comment]
Relevant issue #1205/

**Comment by alexfjw** [comment]
Thanks, didn't notice we had that. Moving over there instead.
