### ISSUE TITLE
Investigate a way to use native Clipboard methods

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1624]
As mentioned in [Clipboard.Clear Method Documentation](https://msdn.microsoft.com/en-us/library/system.windows.forms.clipboard.clear(v=vs.110).aspx),

There are a few pre-requisites to be met in order to utilize the method, however this is worth looking into because having access to Clipboard methods would make implementation for future functions easier. One that comes to mind would be the function that restores clipboard after cut/copy operations.

**Comment by yuhongherald** [comment]
#1915 uses the existing `ClipboardUtil` together with `PPLClipboard` to provide exclusive access to the clipboard and restoring its contents
