### ISSUE TITLE
SyncLab: Artistic Effect Fails to Sync, 2013

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1644]
We cannot sync artistic effect of pictures on 2013.
This problem does not occur on 2016.
I'm guessing this is due to the copying / saving mechanism for SyncLab. 
It could be that the copied shape has it's artistic effect set to permanent in 2013.

We will probably have to look into different ways of saving shapes in SyncLab to work around this.

**Comment by alexfjw** [comment]
Have thought of a fix for this, will put it in after #1645 is merged.

Approach:
Sync artistic effect after SyncLab's storage mechanism copies the shape.
We will be transferring the artistic effect direct to the saved shape. 
This way, it will not be missed.

Note to avoid edge cases:
Manually clear the artistic effect of the copied object before syncing.
Add this as a function in PictureEffectsFormat.cs

**Comment by leeyh20** [comment]
That's weird, it seems to work on PPT 2010... why does it happen in 2013?

**Comment by alexfjw** [comment]
Exactly. Its fine on 2016 as well. No idea what's different in 2013
