### ISSUE TITLE
Unknown Office control ID: PictureCropToolsMenu

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1650]
![image](https://user-images.githubusercontent.com/11351531/37873142-c35ae210-3048-11e8-8a64-e83ed017a33f.png)

As above.

The second comment in this link seems to give a fix, but it's not trivial to implement. Probably needs a bit of planning to be done well.
https://stackoverflow.com/questions/9935539/outlook-addin-has-failed-to-find-office-control-by-id

**Comment by junkiattan** [comment]
@alexfjw I believe this to be an isolated issue and upon further digging, I think that drastic changes to the xml file would not be needed.

Have found some links for specific to the error code. Perhaps Ill refer the person to them
1. https://support.microsoft.com/en-sg/help/914232/you-may-receive-error-code-0x80004005-or-other-error-codes-when-you-tr
1. https://errorcodespro.com/fix-error-code-0x80004005-windows-7-10/

**Comment by alexfjw** [comment]
Seems like the error code refers to 'unspecified error'. Maybe we can follow up with some guiding questions as well.
One of the links seems to mention: `This problem occurs because there are some error codes in a third-party program.` Might be due to pptlabs in the end.

**Comment by leeyh20** [comment]
https://www.google.com.sg/search?client=firefox-b-ab&dcr=0&ei=4by3WvW4Jsz2vASO9ZSIAw&q=picturecroptoolsmenu+mso&oq=picturecroptoolsmenu+mso&gs_l=psy-ab.3..33i160k1l2.6082.6344.0.6522.3.3.0.0.0.0.136.334.1j2.3.0....0...1c.1.64.psy-ab..0.3.332...33i21k1.0.-q4Yd0mPkUA

http://youpresent.co.uk/idmso-control-list-powerpoint-2013-2010/ Does PictureCropToolsMenu iso id exist in powerpoint 2013? This website seems to claim that in 2013, it's called PictureCropTools instead.

**Comment by junkiattan** [comment]
Yeah it was purposely done so that default crop features can cater to both, since it was also hard to detect the PPT versions in the xml files.

The workaround is simply to disable the "Show add-in user interface errors" option in the Options -> Advanced settings. This should solve the error.

I have already replied to Erik on the support mail.
