### ISSUE TITLE
Consider adding Technical Troubleshooting FAQs to the User Guide

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1651]
FAQs related to how users can easily solve problems can be posted on the website so that users can refer to it if they have any questions.

This could potentially help to solve many of problems in a more time-efficient manner.

**Comment by junkiattan** [comment]
@damithc I would like to seek your opinion on this issue. If agreed upon, I can tried to reformat some of the existing FAQ solutions we have to better suit public viewing

**Comment by damithc** [comment]
> @damithc I would like to seek your opinion on this issue.

Yes, it is a good idea. Go ahead.

**Comment by junkiattan** [comment]
Note to self: there is a need to update the faq.md file for the website to remove unneeded FAQs and link to technical troubleshooting guide.
