### ISSUE TITLE
Timeline for second release of PowerPointLabs

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1659]
As discussed with @damithc @leeyh20 @alexfjw ,

We are planning for a second release before STePS on **18th April 2018**. 

Things are must be accomplished in preparation for the event:
1. Event poster (showcase SaveLab, PasteLab, SynLab, AgendaLab)
1. Documentation
1. Actual release

Time allocated for all would be 1.5 weeks, meaning that production would halt by the **end of Wk 11 (8th April 2018)**

**Comment by alexfjw** [comment]
Done 😀
