### ISSUE TITLE
Theme of the template slide is not synchronized into other agenda slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1662]
![image](https://user-images.githubusercontent.com/1673303/38161646-a0663504-3505-11e8-9eaa-9ecc226ecb43.png)
 
#### Environment
PPT2013, Win10

#### Steps to replicate

1. Generate text agenda 
1. Change the design theme of the template slide 
1. Synchronize agenda slides

#### Expected behavior

All agenda slides should be changed to the theme used by the template slide

#### Actual behavior

Agenda slides remains the same (default) theme

**Comment by leeyh20** [comment]
It used to work previously in a previous powerpoint version?

**Comment by leeyh20** [comment]
@damithc I mean previous PPT Labs version*

**Comment by damithc** [comment]
> @damithc I mean previous PPT Labs version*

Yes, it used to work in previous PPT Labs versions and back then I was using PPT 2010.

**Comment by leeyh20** [comment]
@damithc Not sure why it used to work in previous PPT Labs versions but I hope the latest fix will work for you!
