### ISSUE TITLE
Resize Lab: Unexpected results from Tutorial

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1663]
## Bug Report  
 
Bug Report from user
"Or when doing proportional resize of the giraffes, my middle giraffe is expand downwards, and when trying to Align them all to bottom it the middle giraffe doesn’t move, even though it was selected as second. I do get a copy of the giraffe for each operations… "

This issue might be resolved in our recent update.

#### Environment (e.g. version of Microsoft PowerPoint)
Unknown

#### Steps to replicate
- To be added after investigation
#### Expected behavior
- To be added after investigation
#### Actual behavior
- To be added after investigation

**Comment by YuPeiHenry** [comment]
@alexfjw I can confirm that the resize did not work well for the giraffes in the tutorial, for PPT2016. The giraffes are scaled correctly, but the anchor position is not correct. Tested on dev branch.

However, alignment worked for me (might need to confirm this). Let me know what you think.

**Comment by alexfjw** [comment]
Sounds really similar to https://github.com/PowerPointLabs/PowerPointLabs/issues/1601
We had extra image copies in that bug as well.
@junkiattan Do you remember what caused them?

**Comment by junkiattan** [comment]
hey guys. It was a problem with the DuplicateShapes function. 

#1707 managed to produce an acceptable fix to the issue! Check it out and see if the same thing can be applied to this issue;)

**Comment by yuhongherald** [comment]
For the tutorial, where is the expected anchors for the objects. @YuPeiHenry

**Comment by yuhongherald** [comment]
Closing the issue as
