### ISSUE TITLE
Standardize line endings for project 

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1680]
#### Description of feature
Standarize line endings for the project

#### Justification
Standardizing line endings helps reduce merge conflicts.
We've been seeing this quite a bit for the csproj file.

Since PPTLabs works only on windows, I suggest standardizing to CR LF.
This can be done by adding an entry to the .gitattributes file. 

See https://help.github.com/articles/dealing-with-line-endings/

**Comment by leeyh20** [comment]
https://docs.microsoft.com/en-us/sql/ssms/menu-help/advanced-save-options
This will ensure Visual Studio will save with the correct line endings.

**Comment by EliasRojasC** [comment]
Also, I know that the method Environment.newline returns the specific newline for the environment you are on no matter if on windows. A possible option in case you want to move to any other platform in the future.
