### ISSUE TITLE
Format Tab gets focus even when maintain tab focus tab is ticked

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1691]
PPT2013, Win10

Steps:
1. Tick the 'maintain tab focus' box
2. insert a new shape

Expected: PowerPointLabs tab retains focus
Actual: Format tab gets focus

**Comment by junkiattan** [comment]
@damithc I have check the latest dev-release versions and the function seem to work well on PPT2013/2016. I have followed the steps as instructed but cannot replicate the error. 

Is the version of powerpointlabs you are using 4.3.0.0?

**Comment by damithc** [comment]
If I see the feature, I must be using the right version, no? This feature was not available in previous versions as far as I remember.

**Comment by damithc** [comment]
I managed to reproduce the problem in my other computer too.
Try opening multiple pptx files and then ticking and unticking the option while adding more shapes. At one point the meaning of the tick box reverses itself. i.e., the tab stays on top when the tick box is NOT ticked.
