### ISSUE TITLE
Syncing of glow changes glow color

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1692]
Win10, PPT2013

Steps:
* Add a glow to a shape (choose one of the default glow options)
![image](https://user-images.githubusercontent.com/1673303/38858947-94dc3320-425f-11e8-8a3c-932f6087abc5.png)

* copy the glow effect to sync lab
![image](https://user-images.githubusercontent.com/1673303/38858990-aefebcb4-425f-11e8-82ea-afcd7f8c3906.png)

* apply it to a new shape
![image](https://user-images.githubusercontent.com/1673303/38859029-c01119ac-425f-11e8-9053-f1c2b990d778.png)

Problem: the color of the glow is different from the source

**Comment by damithc** [comment]
The issue applies to fill color as well. see how the source and target differs in fill color.
![image](https://user-images.githubusercontent.com/1673303/38859712-362eb81e-4261-11e8-943b-6661df00fb65.png)

**Comment by alexfjw** [comment]
The problem seems to be unique to 2013. When we store a copy of the shape to use as a template, the colors of the shape changes. I'll try to work out a fix.
