### ISSUE TITLE
Narration Lab: Dictionary Access Error 

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1703]
#### Environment (e.g. version of Microsoft PowerPoint)
Office 365

#### Steps to replicate
Quoting the bug report,
> Use narration option (probably generating narrations)

#### Expected behavior
Audio is generated

#### Actual behavior
Error encountered:

>System.Collections.Generic.KeyNotFoundException
The provided key was not present in the dictionary.
Stack Trace:
    at System.Collections.Generic.Dictionary`2.get_Item (TKey key)
    in PowerPointLabs.ThisAddIn.GetActiveWindowTempName ()
    in PowerPointLabs.NarrationsLab.NotesToAudio.get_TempFolderName ()
    in PowerPointLabs.NarrationsLab.NotesToAudio.EmbedSlideNotes (PowerPointSlide slide)
    in PowerPointLabs.NarrationsLab.NotesToAudio.EmbedSelectedSlideNotes ()
    in PowerPointLabs.ActionFramework.NarrationsLab.AddNarrationsActionHandler.ExecuteAction (String ribbonId)
    in PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute (String ribbonId)
 
#### Extra notes
Seems to be an error obtaining the active window name from a dictionary of slides, or something along those lines. More investigation is required.

**Comment by tankztz** [comment]
I can not reproduce this issue in Office 365

**Comment by damithc** [comment]
closing as the lab is being phased out.
