### ISSUE TITLE
<Running error----  I installed VS2017, and so office tools 2017 also. but running the project by clicking F5 the powerpoint app get running but VS project die. You said if there is powerpointLabs installed already, uninstall that and rebuild solution! How can I uninstall that one!>

### ISSUE THREAD

**Issue by slekinpiao** [PowerPointLabs/PowerPointLabs#1709]

**Comment by YuPeiHenry** [comment]
@slekinpiao Hi, thank you for your bug report! Unfortunately, your report is not clear. Please try to follow the [guide for bug reports](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/.github/CONTRIBUTING.md) and use the bug report template provided. You may update the bug report and reopen the issue should you wish to pursue the issue further.
