### ISSUE TITLE
Error creating Visual Agenda with many slides

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1711]
#### Environment (e.g. version of Microsoft PowerPoint)
Not specified

#### Steps to replicate
Create a Visual Agenda of deck with a large number of slides (~2000)

#### Expected behavior
Creates a visual agenda

#### Actual behavior

Exception thrown:
>System.NullReferenceExceptionObject reference not set to an instance of an object.Stack Trace:   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded)

#### Preliminary Analysis
Could be an issue with Zoom Lab as well, given the exception thrown

**Comment by damithc** [comment]
Are we sure this is related to the size of the deck? The error message doesn't sound like it's related to the size of the deck.

**Comment by alexfjw** [comment]
Had the impression it would be best to include all details before verifying the core issue. I'll add a clarifying note above.

**Comment by yuhongherald** [comment]
#1915 fixes the underlying problem for ZoomLab
