### ISSUE TITLE
Tutorial file does not open after installation

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1721]
PowerPointLabs gives an error message when trying to open the tutorial file immediately after installation.

**Comment by damithc** [comment]
Note: this problem only started after SoC started auto-redirecting http links to https a few months ago.

**Comment by leeyh20** [comment]
@damithc Hi Prof Damith, has this issue been fully fixed for all new users?

**Comment by damithc** [comment]
I haven't any complaints about it in recent times 👍
