### ISSUE TITLE
Convert to Picture: Unsupported Object

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1737]
## Bug Report  
![image](https://user-images.githubusercontent.com/40821389/51422674-91deaf00-1bed-11e9-8a6a-0ef8371d28c5.png)

#### Environment (e.g. version of Microsoft PowerPoint)
Powerpoint 2016, WIndows 10
#### Steps to replicate
1. Insert any shape (rectangle in this example)
2. Open shapes lab.
3. Add shape to shapes lab.
#### Expected behavior
No error message.
#### Actual behavior
Error message: "Convert to Picture only supports Shapes and Charts."
#### Additional information
`Convert to picture` works fine on the above tested shapes.
Error seems to be caused by `ConvertAndSave` under `ConvertToPicture.cs`.

Edit: The line `if (!ShapeUtil.IsSelectionShapeOrText(selection))` from `CustomShapePane.cs` conflicts with `if (ShapeUtil.IsShapeRangeShapeOrText(selectedShapes))` from `ConvertToPicture.cs`. This seems to be the cause.

**Comment by ChesterSng** [comment]
Hi @YuPeiHenry I am unable to reproduce this issue sometimes... and actually I don't think the two statements contradict each other... both have the logic that:
If the selection is not a shape or text then throw error.

**Comment by YuPeiHenry** [comment]
From `CustomShapePane: AddShapeFromSelection(Selection selection, ThisAddIn addIn)`:
`            // Check this so that it is the same requirements as ConvertToPicture which is used when adding shapes
            if (!ShapeUtil.IsSelectionShapeOrText(selection))
            {
                MessageBox.Show(ShapesLabText.ErrorAddSelectionInvalid, ShapesLabText.ErrorDialogTitle);
                return;
            }`

From `ConvertToPicture: ConvertAndSave(ShapeRange selectedShapes, string fileName)`:
`            if (ShapeUtil.IsShapeRangeShapeOrText(selectedShapes))
            {
                MessageBox.Show(ShortcutsLabText.ErrorTypeNotSupported, ShortcutsLabText.ErrorWindowTitle);
                return false;
            }`

They look contradicting to me.

**Comment by ChesterSng** [comment]
Hi @YuPeiHenry confirmed that I was looking at the `master` branch instead of `dev-release` branch, yes there seems to be contradiction!
