### ISSUE TITLE
Unable to set up dev environment for website

### ISSUE THREAD

**Issue by blewjy** [PowerPointLabs/PowerPointLabs#1743]
#### Environment (e.g. version of Microsoft PowerPoint)
Windows 10
#### Steps to replicate
Follow the steps documented on the [website repo](https://github.com/PowerPointLabs/PowerPointLabs-Website) to set up the environment for developing the website locally.
#### Expected behavior
Able to set up locally and build the jekyll website
#### Actual behavior
Build fails mid-way due to multiple different errors, including a newer version of ruby required and a `Syck` dependency error.

I believe this is due to the differing versions of tools used in the past and now, thus resulting in a bunch of errors during the build.

**Comment by blewjy** [comment]
I will be submitting a PR to fix this

**Comment by alexfjw** [comment]
Actually, another option would be to ditch the VM altogether and use WSL (Windows Subsystem for Linux). Might be less clunky than the vm.

**Comment by blewjy** [comment]
@alexfjw similar to #1619 ?
I'll see if I can find a reliable and concise way to get it to build without the use of a vm and PR the alternative instructions if possible!
