### ISSUE TITLE
ColorsLab FT does not work correctly

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1744]
## Bug Report  
![image](https://user-images.githubusercontent.com/40821389/51675548-f2675500-200e-11e9-9799-d4c1ed7d6694.png)
Normal screen (13")

![image](https://user-images.githubusercontent.com/40821389/51675562-fdba8080-200e-11e9-9ea2-6a072eb2172e.png)
Wide screen (14.7")

#### Environment
PowerPoint 2016, Windows 10 (13" screen will cause it to not work correctly, 14.7" works correctly)

#### Steps to replicate
Run the ColorsLab FT on PPT2016, Windows 10 environment with a 13" screen (think any non-wide screen will do).

#### Expected behavior
Test should run correctly without throwing any assertion fails.

#### Actual behavior
Test throws assertion fail for `TestFavoriteColors(colorsLab)` as the favorite color panel is off the screen (for 13" screen, if screen is 14.7" it works fine).

**Comment by blewjy** [comment]
@YuPeiHenry our ColorLab has been updated recently, could you check if this is still a problem? Works fine on my 13" screen

**Comment by YuPeiHenry** [comment]
@blewjy Works fine for me now. Closing the issue.
