### ISSUE TITLE
Limit the maximum number of open labs panes

### ISSUE THREAD

**Issue by amrut-prabhu** [PowerPointLabs/PowerPointLabs#1745]
#### Environment (e.g. version of Microsoft PowerPoint)
Microsoft PowerPoint 2019 (not supported technically, but I'm assuming this is applicable to MS Powerpoint 2016 as well)

#### Steps to replicate
- Open Powerpoint Labs Tab
- Click on multiple labs that open up panes (eg. Positions, Resize, Colors, Sync, Timer)

#### Expected behavior
One of the existing panes is replaced. 

#### Actual behavior
Panes are added and cover up the entire workspace.
Clicking on a new lab opens it up in place of or behind one of the existing panes (see clicks on Timer Lab in linked video), depending on the relative order of "importance" of the lab (?).

https://drive.google.com/open?id=1xnPV8I-53HTqQ3e6Jj1LKOrNU6dPLU7h

<img width="960" alt="2019-01-25_20h07_38" src="https://user-images.githubusercontent.com/29021586/51745120-e0ec7e80-20dc-11e9-953f-8d22c3d628b6.png">

#### Existing similar features, alternatives & their shortcomings
When I tried this with some native PowerPoint panes (Animation pane, Format plot area, Format background), a maximum of 2 were allowed.  I don't know if this is consistently followed by Microsoft. For example, Comments can still be opened, resulting in 3 panes.

#### Justification
Having the lab pane open is pointless (in this scenario) since you cannot click on items in your slide to use the lab on.

**Comment by YuPeiHenry** [comment]
Hi @amrut-prabhu , this has indeed been an issue. Does this problem affect your usage greatly?

**Comment by amrut-prabhu** [comment]
Hi @YuPeiHenry , no, not really. Given the current options in Powerpoint Labs, I would say that it happens quite rarely. So, it's a low priority issue, I guess.

**Comment by YuPeiHenry** [comment]
@amrut-prabhu Noted. Thanks for your contribution!
