### ISSUE TITLE
Empty presentation throws NullReferenceException in PictureSlidesLab

### ISSUE THREAD

**Issue by blewjy** [PowerPointLabs/PowerPointLabs#1755]
#### Environment (e.g. version of Microsoft PowerPoint)
Windows 10, PowerPoint 2013
#### Steps to replicate
1. Delete all slides from presentation
2. Open picture slides lab.
3. Try to add a picture or apply existing picture to a slide. 
#### Expected behavior
Expected behaviour should be either error message informing the user that there are no slides to edit or to disable the button completely. I believe user should still be able to add a picture to the lab, but we can disable the button to apply the picture to the slide.
#### Actual behavior
Exception thrown.
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=PowerPointLabs
  StackTrace:
   at PowerPointLabs.PictureSlidesLab.Views.PictureSlidesLabWindow.ImageSelectionListBox_OnPreviewMouseDown(Object sender, MouseButtonEventArgs e) in C:\Users\Bryan\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\PictureSlidesLab\Views\PictureSlidesLabWindow.xaml.cs:line 688
```

**Comment by ChesterSng** [comment]
Hi @blewjy I believe the solution is here to gray out the button when there are no slides in the presentation like in `TimerLab`, will address this in a PR soon
