### ISSUE TITLE
Cloud voice: warn only once

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1770]
v4.4.0.0 Dev
PPT2016, Win 10

Suggestion: Warn about the English language only once (at least, once per session).

**Comment by damithc** [comment]
@LiXiaoooowei Do you remember what this is about? Was it fixed?

**Comment by LiXiaoooowei** [comment]
> @LiXiaoooowei Do you remember what this is about? Was it fixed?

There was a time when "support for English language only" message would pop up multiple times when user clicked on "azure voice" option for cloud voice generation, so we fixed the issue by showing "support for English language" message only once per click. This is a duplicated issue of #1881

**Comment by damithc** [comment]
Thx for checking @LiXiaoooowei 
Closing the issue.
