### ISSUE TITLE
Cloud voice: no preview

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1772]
v4.4.0.0 Dev
PPT2016, Win 10

Feedback: I had the 'Preview' ticked (in settings), but I did not hear a preview after generating the narration.

**Comment by LiXiaoooowei** [comment]
Yes I didn't implement Preview functionality for cloud voice. What should be the expected behavior for Preview in settings? Because user did not select any text for preview yet.

**Comment by damithc** [comment]
The original functionality was to auto-play the audio immediately after generating it.

**Comment by LiXiaoooowei** [comment]
In that case, what if user selected many slides for audio generation and it takes long time to generate all audios in those selected slides, shall we play the already generated audio piece immediately or after all audios have been successfully generated?

**Comment by damithc** [comment]
No need to preview if multiple slides are selected. Only applies to single-slide mode.
