### ISSUE TITLE
'Crop to shape' lowers image resolution

### ISSUE THREAD

**Issue by blewjy** [PowerPointLabs/PowerPointLabs#1797]
## Bug Report  
Bug report from user
#### Environment (e.g. version of Microsoft PowerPoint)
Not specified
#### Description
I'm currently using PowerPointLabs for some basic design work, and I've found that when using the 'crop to shape' feature, the image quality is significantly worsened.

Is there a way to use this feature without this occurring?

**Comment by blewjy** [comment]
I have tried to replicate this on PPT 2013. However, I can't seem to see any significant  drop in quality of the image after cropping. 

@YuPeiHenry @ChesterSng could you guys help to verify if there is any noticeable drop in image quality as reported by this user?

**Comment by damithc** [comment]
Note that designers work at ultra high resolution assets as their output is often used for printing. The drop in quality may not be visible to the naked eye. From what I remember, we decided to auto-reduce the resolution of images so as to keep the pptx file size reasonable. It was not supposed to affect the crop feature, but maybe it did. 
In any case, it would be good to be able to turn that 'auto-adjust resolution' feature off.
@alexfjw @junkiattan were you involved in that feature?

Also, feel free to contanct the user for more info.

**Comment by junkiattan** [comment]
Refer to #1667

I think it can be solved by simply updating the Ribbon1.xml to include a checkbox, and then determining whether to turn the auto image compression on/off in GraphicsUtil.cs. Any other methods can be used as well as long as it gives an option to the user.

Perhaps we can also turn it off by default, so that image quality remains high unless compression is needed for some cases

**Comment by damithc** [comment]
> Perhaps we can also turn it off by default, so that image quality remains high unless compression is needed for some cases

Sounds good.

**Comment by blewjy** [comment]
Hey @junkiattan, thanks for the references! I realised that the image I was using was a low resolution one, hence I could not tell the difference after the crop. Using your doge and ice cream picture indeed resulted in a cropped shape with poor resolution.

I believe the auto image compression you are talking about is referring to the `CompressImageInShape()` method in `GraphicsUtil`. However, this method is not called during the `Crop to Shape` feature. It seems to be only used in `Paste to Fill Slide` and `Paste to Fit Slide`.

I did manage to find the culprit that was causing the lower resolution images -- one of our methods in `GraphicsUtil` exported the slide at 96dpi. Changing this value to something higher like 220/330dpi gave me much better results.

PowerPoint has this option for saving images in the slide, and PowerPoint will automatically scale down the resolution of the image depending on the setting. If you go to **"File - Options - Advanced"** and look under **"Image Size and Quality"**, you should see that PowerPoint compresses the images to whatever value is set as the default output target. In PPT2010 and PPT2013, this is 220ppi by default. In PPT2016, this is set to "High Fidelity" by default, which basically doesn't compress the image. PPT2016 also adds an extra 330ppi option.

Currently, I'm unable to retrieve this option programatically - I'm not sure if PowerPoint even allows us to do that. As such, I'm proposing that we bump our export resolution to 330ppi to account for the extra option in PPT2016. We can add a checkbox at the top of the ribbon `Compress Images` to allow user to choose if he wants to compress them or not. If `Compress Images` is checked, then we will revert to the original 96ppi.

@damithc Prof, any concerns with this suggestion?

**Comment by blewjy** [comment]
This is where the checkbox will be:
![ribbon-checkbox](https://user-images.githubusercontent.com/39292809/53654051-ba93a300-3c87-11e9-9d5b-9980ed5648f5.PNG)

**Comment by damithc** [comment]
> Currently, I'm unable to retrieve this option programatically - I'm not sure if PowerPoint even allows us to do that. As such, I'm proposing that we bump our export resolution to 330ppi to account for the extra option in PPT2016. We can add a checkbox at the top of the ribbon `Compress Images` to allow user to choose if he wants to compress them or not. If `Compress Images` is checked, then we will revert to the original 96ppi.
> 
> @damithc Prof, any concerns with this suggestion?

Sounds good.

**Comment by ChesterSng** [comment]
@blewjy we can close this issue right?

**Comment by blewjy** [comment]
Yup, closing
