### ISSUE TITLE
eLearningLab disappears after opening another slide deck

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1801]
steps:
1. Open a slide deck, open eLL
2. Open another slide deck
3. Click on the first slide deck

actual: eLL disappears

Is this expected?

**Comment by damithc** [comment]
Win10, PPT 2016

In fact, the `eLearningLab` menu option gets disabled after that i.e., can't open it again. Went back to normal after restarting PowerPoint.

**Comment by LiXiaoooowei** [comment]
When there isn't any slide selected, `elearninglab` menu option will be greyed. And any active elearning taskpane will also disappear. However, if there is a slide under selection, then `elearninglab` menu option should be enabled again. 


> Win10, PPT 2016
> 
> In fact, the `eLearningLab` menu option gets disabled after that i.e., can't open it again. Went back to normal after restarting PowerPoint.

In this case, is `elearninglab` option enabled again when a slide is selected?

**Comment by damithc** [comment]
Selecting slides did not help. It was this option that was greyed out:
![image](https://user-images.githubusercontent.com/1673303/53728042-aa104200-3eac-11e9-88de-8425ef7f0bfd.png)

**Comment by damithc** [comment]
Can't seem to reproduce it though. I'll report back if it happens again.

**Comment by damithc** [comment]
Closing. Will reopen if it happens again.
