### ISSUE TITLE
Open e-learning lab settings window causes exception 

### ISSUE THREAD

**Issue by LiXiaoooowei** [PowerPointLabs/PowerPointLabs#1807]
An exception will be thrown during run time when e-learning lab settings window is open if audio preview window opens in the background. This happens because audio preview window uses the same dialog window frame as that of e-learning lab settings. 

## Bug Report  
<img width="301" alt="Capture" src="https://user-images.githubusercontent.com/17466278/54122030-f45a6b80-4436-11e9-8134-618f3c237eab.PNG">

#### Environment (e.g. version of Microsoft PowerPoint)
PPT 2016
#### Steps to replicate
1. Open e-learning lab
2. Create a self-explanation item with audio checked
3. Click on `Audio Preview` button. `Audio Preview Window` will show up. 
4. Click somewhere else to bring `Audio Preview Window` to the background.
5. Open e-learning lab settings window
#### Expected behavior
E-learning lab settings window should appear normally
#### Actual behavior
An exception is shown

**Comment by ChesterSng** [comment]
Step 5: Open Audio Preview Window from same self-explanation item will also not work

**Comment by LiXiaoooowei** [comment]
> Step 5: Opening Audio Preview Window from same self-explanation item will also not work

Yes thanks for adding that.

**Comment by LiXiaoooowei** [comment]
Closed because this issue is already fixed in version 3.
