### ISSUE TITLE
Highlight points: wrong colors used

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1810]
Dev version 4.6.0.0

![image](https://user-images.githubusercontent.com/1673303/54260062-da3d9c00-45a2-11e9-8147-f7d0288414a1.png)
![image](https://user-images.githubusercontent.com/1673303/54260110-f9d4c480-45a2-11e9-9901-3cb3d3d7c1cb.png)

I've set the highlight color to yellow and activated the 'Highlight points' feature for bullet points in a slide, but the points were highlighted using orange.
It started working correctly after changing the colors (in settings) for the second time.

**Comment by YuPeiHenry** [comment]
I cannot replicate the bug on PowerPoint 2010 and 2016. Is there a step that I might be missing out (eg. opening an existing presentation)?

**Comment by damithc** [comment]
I'm unable to reproduce it either, although this has happened to me a few times before. :-p

**Comment by damithc** [comment]
Closing for now. Will reopen if it happens again.
