### ISSUE TITLE
Tooltips Lab: Change default callout and trigger shape styles

### ISSUE THREAD

**Issue by blewjy** [PowerPointLabs/PowerPointLabs#1815]
Currently, the callouts and trigger shapes are generated with just the default blue styling. Let's change it to have a default styling like in this screenshot:
![TooltipsLab-default-styles](https://user-images.githubusercontent.com/39292809/54352126-e0f40e00-468b-11e9-8712-6966bea7ba99.png)

The same styling for callout are being used in Elearning Lab, can take reference from there as well.

**Comment by damithc** [comment]
Also note the styling for the default trigger, with the question mark as the default text.
