### ISSUE TITLE
remove all captions/audio: some are not removed

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1838]
The features that remove all captions/audio don't seem to remove all captions/audio in all/selected slides. This feature used to work earlier.

**Comment by LiXiaoooowei** [comment]
It seems to work fine for me. Captions/Narrations Lab only remove captions/narrations generated by Captions/Narrations Lab, i.e. shapes prefixed with "PowerPointLabs". Shapes prefixed by "PPTL" are generated by e-learning lab and those are not removed by Captions/Narrations Lab.

**Comment by LiXiaoooowei** [comment]
However, after some testing, I do find a problem with Narrations Lab. That is, suppose I have narrations generated by NarrationsLab on multiple slides. Select one slide with narrations generated and click on `Remove Audio` will remove audios on selected slide. However, `Remove Audio` button will be disabled thereafter for other slides with narrations unless `generate audio automatically` button is clicked again for some slide.

**Comment by damithc** [comment]
> However, after some testing, I do find a problem with Narrations Lab. That is, suppose I have narrations generated by NarrationsLab on multiple slides. Select one slide with narrations generated and click on `Remove Audio` will remove audios on selected slide. However, `Remove Audio` button will be disabled thereafter for other slides with narrations unless `generate audio automatically` button is clicked again for some slide.

That's what happened in my case.
