### ISSUE TITLE
Reserved Names for Windows Files can be used in ShapesLab

### ISSUE THREAD

**Issue by ChesterSng** [PowerPointLabs/PowerPointLabs#1844]
Refer to this [link](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#naming-conventions) for a list of reserved names for windows files. 

Currently ShapesLab lets users choose their own category name which in turn will create a folder with the same category name. Since the creation of the folder is not done by the default "Create a Folder" by windows, reserved names can be entered into the category name and cause ShapesLab to stop working. 

**We should ban reserved words to be used as category names, an example will be "COM1" , when entered will cause an error to be thrown.**

The category is added, however the directory cannot be created. Whenever users try to access the category "COM1" subsequently, an error will be thrown. 

I did a check on the other labs and no other labs have a similar workflow that can cause this problem. 

This post on [StackOverflow](https://stackoverflow.com/questions/62771/how-do-i-check-if-a-given-string-is-a-legal-valid-file-name-under-windows) can help.

Another way is to create the directory first, then catch the exception.

**Comment by leeyh20** [comment]
Interesting issue!

**Comment by EliasRojasC** [comment]
I'd like to give this a shot. Could you give me a place to start? I'm new to the project.
