### ISSUE TITLE
Zoom Lab: Step back does not account for fading animations

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1855]
#### Description of feature
Currently Zoom Lab creates an image of a slide without accounting for fade animations when using step back. Drill Down does some accounting for animations.

Slide with fade animations:
![animation](https://user-images.githubusercontent.com/40821389/55686854-ea297f80-5998-11e9-81ad-611225409511.gif)

Slide with step back:
![animation2](https://user-images.githubusercontent.com/40821389/55686858-f31a5100-5998-11e9-9534-de2f642a21b2.gif)

#### Justification
The slide transition will not be smooth if extra effort is not placed in.

**Comment by ChesterSng** [comment]
Hi @YuPeiHenry, need more information on what you mean, can you provide maybe some pictures or gifs?

**Comment by YuPeiHenry** [comment]
@ChesterSng I have added the GIFs. I think the problem is pretty apparent.

**Comment by ChesterSng** [comment]
Should the title of the issue be fade animations or images?
