### ISSUE TITLE
ResizeLab changes orientation of text in shape

### ISSUE THREAD

**Issue by ChesterSng** [PowerPointLabs/PowerPointLabs#1856]
## Bug Report  
 
Before using ResizeLab:
![image](https://user-images.githubusercontent.com/39242483/55706385-ade73500-5a13-11e9-9b6b-bd3a2e854c88.png)
After using ResizeLab:
![image](https://user-images.githubusercontent.com/39242483/55706404-bc355100-5a13-11e9-996c-7a8d2207aa50.png)

#### Environment (e.g. version of Microsoft PowerPoint)
PowerPoint 2016, Windows 10
#### Steps to replicate
Use any function in `ResizeLab` and this will change the orientation of the text to horizontal.

**Comment by yuhongherald** [comment]
I think the code responsible for the text rotation is PPShape.
