### ISSUE TITLE
Unnecessary file in project: UpgradeLog.htm

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1859]
## Extra Project File
It seems that there is a htm file that was probably generated by Visual Studio when the project was upgraded, and was unintentionally staged at some point of time. This file should be removed as it is not required by the project.

#### Work to be done
Remove and ignore the file. Need to confirm if this file is redundant.

**Comment by yuhongherald** [comment]
The migration report does not contain any useful information, and is generated from migration. I think it can be removed safely.
