### ISSUE TITLE
English language support alert shows up multiple times

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1881]
When the Azure option is chosen, 'We support English only' message shows up 2-3 times.
![image](https://user-images.githubusercontent.com/1673303/56116863-750e0980-5f99-11e9-94c7-9b97a1c5e0eb.png)

On a related note, perhaps show it as a text in the settings page itself, rather than pop up an alert?

**Comment by damithc** [comment]
This is not serious enough to stop the public release but should be fixed soon, in the subsequent patch.

**Comment by LiXiaoooowei** [comment]
The current behavior is that, `support only English` message will pop up once every time `Azure` option is checked. So I shall fix it to pop up once ONLY across the entire presentation.

**Comment by damithc** [comment]
> The current behavior is that, `support only English` message will pop up once every time `Azure` option is checked. So I shall fix it to pop up once ONLY across the entire presentation.

The bug is that it pops up three time for _one_ click on the radio button. When you click `OK`, it pops up again.

**Comment by LiXiaoooowei** [comment]
> The bug is that it pops up three time for _one_ click on the radio button. When you click `OK`, it pops up again.

It pops up only once on my machine though. But I believe that the fix could handle it well.
