### ISSUE TITLE
GitHub Link in PowerPointLabs Website points to wrong repo 

### ISSUE THREAD

**Issue by ChesterSng** [PowerPointLabs/PowerPointLabs#1883]
The github logo in the PowerPointLabs website currently pointing to the website repo instead of PowerPointLabs Repo.

https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/71a35b5891dd1074d231bddd012dc00f9261212d/_includes/navbar.html#L14

**Comment by LiXiaoooowei** [comment]
It seems like that's a home button for the website?

**Comment by YuPeiHenry** [comment]
See:
https://github.com/PowerPointLabs/PowerPointLabs-Website/pull/94
