### ISSUE TITLE
PowerPointLabs website: GitHub icon too large on navigation bar

### ISSUE THREAD

**Issue by LiXiaoooowei** [PowerPointLabs/PowerPointLabs#1895]
## Bug Report  
GitHub icon is too large on the navigation bar for PowerPointLabs website. As a result, the title for each web page can be hardly seen. 
<img width="940" alt="Capture" src="https://user-images.githubusercontent.com/17466278/56256858-fdf18600-60fc-11e9-9f7d-c916de7a35a6.PNG">

#### Environment
This behavior happens on laptop version of Chrome. The size of GitHub icon works fine on mobile. 
#### Steps to replicate
Go to PowerPointLabs website on Chrome browser using a laptop.
#### Expected behavior
Height of GitHub icon should be almost the same as the other navigation bar items.

**Comment by ChesterSng** [comment]
It should be because your browser has the old .css cached. Try clearing your cache for the website!

**Comment by LiXiaoooowei** [comment]
> It should be because your browser has the old .css cached. Try clearing your cache for the website!

Indeed! Closing this issue.
