### ISSUE TITLE
 insert a website into the ppt?

### ISSUE THREAD

**Issue by yoyomule** [PowerPointLabs/PowerPointLabs#1897]
This is a great project, thank you.
Can you consider adding a function to insert a website into the ppt?

**Comment by damithc** [comment]
Glad to hear you liked PowerPointLabs @yoyomule 
Thanks for the suggestion. We'll consider that in future updates.

**Comment by yuhongherald** [comment]
There is an existing free add-in for powerpoint that does this. There is a tutorial [here](https://www.howtogeek.com/howto/25946/how-to-add-live-web-pages-to-a-powerpoint-presentation/) for using it. I think we should focus on other features that are not available to powerpoint users.
