### ISSUE TITLE
eLearningLab: Click number and trigger type of explanation items do not load correctly

### ISSUE THREAD

**Issue by LiXiaoooowei** [PowerPointLabs/PowerPointLabs#1911]
## Bug Report  
Currently, eLearningLab does not load click number and trigger type of explanation items correctly if there are no more custom animation items following after explanation items. In that case, the explanation item that follows will always be set to trigger with previous. 
#### Environment (e.g. version of Microsoft PowerPoint)
PowerPoint 2016
#### Steps to replicate
1. Create an explanation item and choose either callout/caption/voice, and change the item to start on click. 
2. Click sync to sync explanation item to the slide.
3. Switch to some other slide, eLL will reload.
4. Switch back to the previous slide where explanation item was created. Notice that the explanation item is set to trigger with previous and click number 0.  
#### Expected behavior
The same explanation item should be loaded, which was set to trigger on click and a click number of 1
#### Actual behavior
The explanation item was loaded to trigger with previous and click number 0

**Comment by YuPeiHenry** [comment]
Bug reproduced on PPT2010.
