### ISSUE TITLE
UI bug in E-Learning Lab: Text overflow cannot scroll

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1918]
![image](https://user-images.githubusercontent.com/28508438/58603155-425a6f00-82c2-11e9-9302-c712b949bebd.png)

PPT2016, Win10

The name for the audio does not display fully and cannot be scrolled.

Suggested fix:
Wrap the text when the name overflows.

**Comment by LiXiaoooowei** [comment]
@yuhongherald Thanks for testing! I am able to reproduce this bug on PPT2016. Perhaps the name should wrap if it overflows.

**Comment by YuPeiHenry** [comment]
> @yuhongherald Thanks for testing! I am able to reproduce this bug on PPT2016. Perhaps the name should wrap if it overflows.

Easy to implement fix, good suggestion.
