### ISSUE TITLE
Increase resolution of 'slide as image' conversion

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#195]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on February 15, 2014 14:14:26_

When we convert a slide to an image (e.g. zoom in), the resolution of the image determines the quality of the animation. saving the image as a file first and inserting that seems to give me a better quality than using the clipboard method 'paste as picture'
Apparently, the resolutions can be changed http://support.microsoft.com/kb/827745

_Original issue: http://code.google.com/p/powerpointlabs/issues/detail?id=195_

**Comment by alexfjw** [comment]
Would be good to check if auto image compression affects the quality here, when we go about implementing this. See #1712

If yes, we should add an alert for the user regarding auto image compression.

**Comment by damithc** [comment]
In fact, we can add a context menu option `save as picture` that appears when a slide is selected.
