### ISSUE TITLE
ZoomLab: Buttons greyed out depsite rectangle selected

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1963]
## Bug Report  
Another issue that cropped up in #1913:

PPT2016, Win10

In the attached slide, the zoom to area features work for only one of the rectangles:
![image](https://user-images.githubusercontent.com/1673303/58235333-30814500-7d73-11e9-9d8a-22d7c6906d9f.png)

![image](https://user-images.githubusercontent.com/1673303/58235406-53135e00-7d73-11e9-90ff-6b3e83e0314a.png)

[zoom to area error.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/3210891/zoom.to.area.error.pptx)

**Comment by yuhongherald** [comment]
The AutoshapeType says that the shape is a `msoShapeRectangle`, which is currently the reason why the shape is mistaken as not a rectangle.

**Comment by yuhongherald** [comment]
Alternatively, we can use the pre-existing CropLab to crop the previous slide to the shape of the shape.

**Comment by damithc** [comment]
Can we allow both? As far as the user is concerned, they are both rectangles.

**Comment by yuhongherald** [comment]
Yes I think we should allow both, in #1963 I have used visual similarity to make it more lenient for the shapes.
