### ISSUE TITLE
HighlightLab: Unhandled UnauthorizedAccessException

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1981]
Sent by a user. Details:

System.UnauthorizedAccessExceptionAccess is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))Stack Trace:   at Microsoft.Office.Core.TextRange2.TrimText()   at PowerPointLabs.ActionFramework.HighlightLab.HighlightTextEnabledHandler.GetEnabled(String ribbonId)   at PowerPointLabs.ActionFramework.Common.Interface.EnabledHandler.Get(String ribbonId)

**Comment by yuhongherald** [comment]
It seems that the upgrade of .NET version may have caused this

**Comment by damithc** [comment]
Inform the user it will be fixed in a future release.
On a related note, is it fixable easily? If yes, let's try to include it in the next public release.

**Comment by yuhongherald** [comment]
Ok. I will take a look
