### ISSUE TITLE
Show selection panel after editing name

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#26]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on November 23, 2013 13:56:13_

After editing the name of an object, we can show the 'selection pane' automatically, if it is not already being displayed. 
This way, the user get a visual confirmation of the action result.

_Original issue: http://code.google.com/p/powerpointlabs/issues/detail?id=26_

**Comment by kai33** [comment]
how to open selection panel
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/DrawingsLab/DrawingsLabMain.cs#L309
