### ISSUE TITLE
Auto-animate: step back does not consider animations in the start slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#286]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on April 03, 2014 11:04:54_

existing animations in the (n-1)th slide is not considered when doing a step back in the nth slide.

_Original issue: http://code.google.com/p/powerpointlabs/issues/detail?id=287_

**Comment by damithc** [comment]
@Ohohcakester can you check if this is fixed now. If yes, close the issue.

**Comment by Ohohcakester** [comment]
I've seen this issue before, but I can't figure out what it means.
What does being "considered" mean?
As far as I know, shapes with exit animations are removed in a step back, and shapes with entry animations are removed in a drill down.

**Comment by damithc** [comment]
Yes, that's what needs to be done. closing.
