### ISSUE TITLE
Disabled buttons mislead user

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#327]
In some cases, user may think disabled buttons are broken/not supported/not activated..

A more friendly solution can be:
* buttons are made enabled always (if cannot handle the case, pop up certain error msg to guide user)
* when a button is clicked for the first time, a window with how-to-use anime of this feature will be shown to user (although we have quick tuto, and it's opened after install, I'm afraid some ppl still don't try it at all..)

**Comment by damithc** [comment]
Disabling non-applicable buttons is the default PowerPoint behavior. Let's follow the same.
