### ISSUE TITLE
'Hide' option in context menu

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#56]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on December 10, 2013 13:04:23_

Hiding an object from view currently requires going to the selection pane. We can make it easier by adding a 'hide' option to the context menu.

_Original issue: http://code.google.com/p/powerpointlabs/issues/detail?id=56_

**Comment by LIUJIAHAOCS** [comment]
'Hide' option now is ready to use, waiting for icon design

**Comment by damithc** [comment]
I'll do the icon soon. In the meantime, you can use the last icon (an eye) in the icons.pptx file as a temporary placeholder.
