### ISSUE TITLE
PowerPointLabs got disabled after opening PowerPoint without Internet

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#582]
Not sure what happened. I opened PowerPoint without Internet. There was an attempt to connect to PowerPointLabs server. Later, I noticed that the add-in got disabled. I had to go and enable it manually. I remember something like this happened to another user.

**Comment by kai33** [comment]
likely this issue happened in web & online version (deprecated), not standalone & offline version of pptlabs.

1. Web & online version's update is totally handled by ClickOnce. I believe it is ClickOnce's (MS Office add-in installer) problem, then we may not be able to resolve it. Bcos it intercepts before pptlabs add-in starts.
2. For standalone & offline version, we're in charge of downloading new version of pptlabs and ClickOnce only helps to replace the old with the downloaded new one. now all possible exceptions (including network related ones) are caught, so standalone & offline version should be fine.
