### ISSUE TITLE
Text highlight is behind the text

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#592]
Highlight test does not work if the text box has a fill color. Perhaps in such cases the highlight should be in front of the text?

**Comment by LIUJIAHAOCS** [comment]
Fixed. now if any selected shape has background color, the text highlight will be shown in front.

**Comment by damithc** [comment]
Can post a screenshot?

**Comment by LIUJIAHAOCS** [comment]
![image](https://cloud.githubusercontent.com/assets/14244291/11492414/fa6e630a-9827-11e5-8d6f-ba5bfaa92c2b.png)
