### ISSUE TITLE
Organize context menu better

### ISSUE THREAD

**Issue by nevet** [PowerPointLabs/powerpointlabs#597]
Currently the context menu is too long (require scroll) for some kind of shapes, for example a simple rectangle (Auto Shape). I think we could group up some buttons into a secondary menu, or simply put every our button into a new menu "PowerPointLabs".

**Comment by kai33** [comment]
Some choices:
1. remove those menu items that are already in the pptlabs ribbon.
2. put menu items as sub-menu items to shorten the length.

**Comment by damithc** [comment]
I prefer 2. Otherwise the mouse has to travel between the slide and the ribbon a lot. A third option is to implement our own context menu.

**Comment by kai33** [comment]
like app launcher?

**Comment by damithc** [comment]
e.g. user selects object and press a keyboard combination (or click an item in the normal context menu) to pop up a special powerpointlabs context menu. It will have actions that the user is likely to need, but organized in a more intuitive way. Anyway, this option can be a whole major feature. For now, let's go with 2.

**Comment by kai33** [comment]
![re-org context menu](https://cloud.githubusercontent.com/assets/3591355/9308557/65485666-4537-11e5-8504-17beb1f8d08a.png)
