### ISSUE TITLE
Add effects lab to the tutorial

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#611]
To be done after exams

**Comment by nevet** [comment]
@jcheng31 I notice that in the latest commit 2561e41 we do not have Effects Lab included, are you doing it?

**Comment by damithc** [comment]
I added effects lab to the tutorial in my recent commit to master

**Comment by damithc** [comment]
Sorry, seems I forgot to push it. :-p Pushed just now.

**Comment by nevet** [comment]
the tutorial is pushed to server :)
