### ISSUE TITLE
Stand-alone installer not working under directory with special characters

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#618]
When ClickOnce accesses local data, it said the data (at file:///C:/blablabla) cannot be found.

**Comment by damithc** [comment]
We favor the standalone one right? Any way to make it work for those
folders?

**Comment by kai33** [comment]
The special characters only appear in the Windows username (thus it may affect those whose username is not fully in English char, eg French users).
Since we're not trusted publisher (no 3rd-party signed certificate), we cannot put our add-in into folders like c:\program files\.
And to have adequate permissions, the standalone install folder has to put under current user's.
So it seems unavoidable.

I can update standalone installer that when it detects special char, it will download and execute the online installer, which will work for the user

**Comment by damithc** [comment]
Let's try that then. But that means we have maintain both installers
indefinitely :-p

**Comment by kai33** [comment]
fixed by 3190158

**Comment by kai33** [comment]
@nevet  I've uploaded new installer UI into ggdrive,
under folder "How to deploy/offline/setup.exe".
please use it to replace the one in your folder "[your publish folder]/offline/setup.exe"

**Comment by damithc** [comment]
Don't do any dev releases on 7th (today) or tomorrow. I'm doing a demo
tomorrow and I don't want any last minute glitches :-)

**Comment by nevet** [comment]
@kai33 done :)
