### ISSUE TITLE
Optimize Magnify feature for picture

### ISSUE THREAD

**Issue by nevet** [PowerPointLabs/PowerPointLabs#631]
As mentioned in #607: If the zoom area is covered entirely by a picture, we can place an enlarged version of the picture in the end slide (to reduce pixelation).

**Comment by nevet** [comment]
which commit fixes this issue? and how about #607?

**Comment by damithc** [comment]
@Ohohcakester is this fixed?

**Comment by Ohohcakester** [comment]
I think this hasn't been done yet. I must have confused it with another zoom issue when I closed it earlier. (The autozoom issues aren't very descriptive)

**Comment by initialshl** [comment]
Can i work on this?

**Comment by damithc** [comment]
> Can i work on this?

Sure.
