### ISSUE TITLE
Shapes lab have weird behavior on new computer

### ISSUE THREAD

**Issue by nevet** [PowerPointLabs/powerpointlabs#634]
When shapes lab is opened on a new computer, it has some weird behaviors.

**Comment by damithc** [comment]
What kind of weird behavior?

**Comment by nevet** [comment]
Well, it's a bit complicated. When the first time click on Shapes Lab, it shows nothing, but it will show on the second time you click on it. However, the category is empty, and all functions broken unless you add a category to the Shapes Lab. It wont cause severe error, but looks weird.

**Comment by damithc** [comment]
I see. Better fix it :-)

**Comment by nevet** [comment]
I've found the bug, the latest commit 938bc77
