### ISSUE TITLE
Step back requires 2 clicks to step back

### ISSUE THREAD

**Issue by nevet** [PowerPointLabs/powerpointlabs#636]
I don't know how to produce this everytime, but for some slides, step back function works but require some time to respond, for some slides, it requires 2 clicks to step back.

**Comment by damithc** [comment]
Are you referring to creating drill down or using the created slides during slide show? If it is during the slide show, I have the same problem: it takes some time to respond. It is a PowerPoint performance problem. PowerPoint does some sort of preloading of animations per slide which can take some time.

**Comment by nevet** [comment]
Yes I'm referring to the the created slides during slide show. Since we are using it in Agenda Lab as well, I think we'd better come up with some means to reduce the respond time. I will try to find out some means to speed it up :P

**Comment by damithc** [comment]
Yes, it would be good to optimize it, but let's do it later.
