### ISSUE TITLE
Audio cannot be heard after pressing ESC when the audio is playing

### ISSUE THREAD

**Issue by nevet** [PowerPointLabs/PowerPointLabs#637]
Quote from the user:

> I add the audio and all seems to working. But, if I'm running the presentation and I press Escape (to come back to edition mode) before the audio is finish, then I cannot hear the audio anymore. Closing and openning PowerPoint again do not solve the problema. I need to restart the computer for hearing again the audio.

**Comment by nevet** [comment]
I cannot reproduce this bug, can anybody help me to try out on your machine? @jcheng31 @kai33 @damithc

**Comment by damithc** [comment]
I cannot reproduce. Looks like a problem specific to user's setup. Ask the user if the problem is reproducible (sometimes those problems go away after a restart) and if not, to send you a sample slide having the problem.
