### ISSUE TITLE
Follow design template used for the first agenda slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#644]
Note that the user might apply a different design template to agenda slides. Subsequent agenda slides should follow the design template used in the first one.

**Comment by nevet** [comment]
Oh this has been done already, I forgot to demo it yesterday :P

Basically, these things will be synced with the first slide:

1. Design;
2. Layout;
3. Transition;
4. Extra Shapes;
5. Shapes Position;
6. Title

I'm thinking to sync animations for bullet as well.

**Comment by damithc** [comment]
Good. Regarding transitions, see #645

**Comment by nevet** [comment]
Transition synchronization is temporarily disabled until #645 is resolved :)

**Comment by damithc** [comment]
The design template applied to the first agenda slide is not propagated to the rest.

**Comment by nevet** [comment]
This is a regression, I will fix it.

**Comment by nevet** [comment]
It's because the template is lost when the slide gets copy-pasted. More precisely, the slide will be applied the template that applies to all slides when it gets pasted.

**Comment by damithc** [comment]
That's not good. We need to preserve the template. The agenda slides often
need a different template than the regular slides.

**Comment by nevet** [comment]
The issue is fixed :)
