### ISSUE TITLE
Give option not to use bullets

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#646]
Some users may not want to use bullet points in the agenda slides. e.g. if the title already contain a number "1. Introduction". Alternatively, we can follow the numbering/bullet style applied in the first agenda slide.

**Comment by nevet** [comment]
This has been done, user can specify bullet type on the first slide and Sync function will apply this to all other agenda slides.

**Comment by damithc** [comment]
Hope it works even if the user removes bullets altogether, or use a
numbering style instead.

**Comment by nevet** [comment]
The user can specify the bullet style from Home Tab->Paragraph Group, and Sync will do its job :) Basically, all format in Home->Font and Home->Paragraph will be synced, and the unit for this Sync is per bullet, means that you are able to specify different bullet paragraph/font format for different bullet.
