### ISSUE TITLE
settings should be per agenda type

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#651]
I don't think we can have one settings dialog for all three agenda types.

**Comment by nevet** [comment]
How about a dialog with different tabs? And may I have your suggestions about the settings that are proper for Visual Type and Beam type agenda?

**Comment by damithc** [comment]
Another options is to give 'settings' as a sub menu.
I can't think of many settings for the other two types now. one example for
beamer type is whether the agenda appears at the top/bottom/left/right.
Another thing. Is it good to assume there will be only one agenda type in a
presentation? If the answer is 'no', then we should have 'remove' and
'regenerate' options for each type separately, may be as sub menus.
