### ISSUE TITLE
Retain list levels given in the first agenda slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#655]
This feature is to cater for hierarchical agendas. For example, if the user increased the list level of certain items (i.e. 2nd level agenda items), we should retain the list level in subsequent slides too. 
![image](https://cloud.githubusercontent.com/assets/1673303/5792800/674691d0-9f65-11e4-9af2-63dfdaf7d636.png)

**Comment by nevet** [comment]
This is a quite old issue, but how do we do this when template slide is provided, but not taking the first slide as template? The template slide contains only formatting information, so how should we specify additional information?

**Comment by nevet** [comment]
If this kind of hierarchical level only applies to section titles (i.e. #696), I think we could let user use special symbols (like suggested in #697) to indicate this information.
