### ISSUE TITLE
'cannot connect from your default location' error

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#659]
Error reported by user.
![image](https://cloud.githubusercontent.com/assets/1673303/5867266/b445a71a-a2d4-11e4-9189-f5d8d98f08a9.png)

**Comment by nevet** [comment]
We have tried quite a lot different methods, including reinstalling our add-in, delete shapeslab.config, etc., but had no luck. However, he's managed to solve the problem by creating another user on his computer and running as that user. But unfortunately he experienced some other defects:

> I managed to solve the issue! I created a new user on my computer and reinstalled PowerPontLabs on that user. So now, it finally works.

> Unfortunately I have some other issues while trying to load the shapes:
1. Slow loading of my shapes (~15-20 seconds). 
2. Powerpoint very slow when MyShapes is open. Does MyShape eat up a lot of memory?
3. Sometimes I receive errors (see below) when opening ShapesLab

> Overall feedback: great add-in. Look forward to having it even more seamlessly and more effectively integrated. Thanks a lot for your effort. Let me know when next version comes!

**Comment by damithc** [comment]
@Ohohcakester The performance issue of the shapes lab is now fixed, right?

**Comment by Ohohcakester** [comment]
The performance issue seems to be fixed, but, I don't know what the error above is.
