### ISSUE TITLE
user can blur slide background

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#660]
This is similar to 'blur remainder' but blurs the entire slide except the selected shape. Expected to be used in cases like the attached image

![image](https://cloud.githubusercontent.com/assets/1673303/5996074/44c05416-aadc-11e4-958a-4256f3d733cf.png)

**Comment by nevet** [comment]
I guess it would be useful if we make this apply to all "remainder" features. I currently add an Effects Lab Settings dialog to Effects Lab, in which you are allowed to config whether the selected shapes are covers or not (see screen shot below). If the checker box is ticked, then all remainders behave in the old way, else it will behave in the way you described above.
![image](https://cloud.githubusercontent.com/assets/6215274/6546596/edbdbc42-c5f4-11e4-809d-088ef46dd6f3.png)

Original slide:
![image](https://cloud.githubusercontent.com/assets/6215274/6546601/274dd4ba-c5f5-11e4-8e64-aa2ba0c40b0d.png)

Selection is cover turned off:
![image](https://cloud.githubusercontent.com/assets/6215274/6546604/498a0512-c5f5-11e4-80f4-f41f3070a8c2.png)
