### ISSUE TITLE
auto-animate doesn't consider line shapes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#661]
Lines and arrows are not auto-animated

**Comment by nevet** [comment]
Is this a regression, or it hasn't been tested before?

**Comment by damithc** [comment]
I'm not sure. May be it was never implemented.

**Comment by nevet** [comment]
Hmmm, could you send me the slide which goes wrong? I tried both ```Animation Slide``` and ```Animate In Slide``` with Line Shape and Arrow Shape, neither of them went wrong :S

**Comment by nevet** [comment]
Oh do you mean the two lines/arrows have different angle? In this case it went wrong, and seems like it's an unimplemented feature.

**Comment by damithc** [comment]
Yes, lines with different angles.

**Comment by nevet** [comment]
Ok noted, will fix that later.

**Comment by initialshl** [comment]
Can i work on this issue? I tried it and have some progress already, just some positioning left to be done.

**Comment by damithc** [comment]
@initialshl We have decided to not spend time on auto-animate feature, but I can make an exception for this issue.
