### ISSUE TITLE
Give a way to add to 'favorite colors'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#664]
as per title

**Comment by kai33** [comment]
in the context menu (will appear when right click the color panel), 
add a new menu item : Add to Favorites.

the selected color then will be added into fav color, and the last fav color will be removed

**Comment by damithc** [comment]
Did you mean the oldest favorite color will be removed? It should be a FIFO list.

**Comment by kai33** [comment]
yes, it is FIFO
