### ISSUE TITLE
Stuck at 'agenda is generating' dialog

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#672]
This happened the first time I used visual agenda. Some of the agenda slides were generaged, but it got stuck in the middle and the dialog box didn't go away.

**Comment by damithc** [comment]
Happened 2nd time too

**Comment by damithc** [comment]
Happened for agenda sidebar too

**Comment by nevet** [comment]
This bug may be related to #643.

**Comment by nevet** [comment]
I will find a way to ask the user to change the view rather than get stuck in the middle.

**Comment by nevet** [comment]
This is fixed in 26c0f2d.
