### ISSUE TITLE
Visual agenda slides do not have the same design when they are first generated

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#684]
When generated, they don't seem to follow the design template as the first agenda slide. However, it gets rectified after I synchronize once.

**Comment by nevet** [comment]
Could you explain more about this case? I'm a bit confused, what do you mean by "they don't seem to follow the design template as the first agenda slide"? Currently "Generate" will remove all old slides and re-generate a set of slides, "Sync" is the one that regenerate all slide with the format from the first slide.

**Comment by damithc** [comment]
They should all have the same slide design from the beginning, shouldn't
they? Right now, each agenda slide follows the design of the slide above
it. Instead, they should all have the same design as the first agenda slide.

**Comment by nevet** [comment]
bullet agenda has the same problem, but has been fixed in the latest commit dd13ebe
