### ISSUE TITLE
Items in the agenda should have hyperlinks to the relevant slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#685]
That way, a user can jump to a specific section from an agenda slide

**Comment by nevet** [comment]
I just realized that adding hyper links to text screwed up the text's color unless we modified the theme, but it doesn't seem to be a good solution. What I suggest is to put a no-fill shape above each of the bullet and add links to those transparent shapes. However this solution may be weird when a user wants to modify the content of bullet agenda, as in they'll realize there's something above it.

**Comment by nevet** [comment]
A tricky work around will be: hide those shapes in normal view, and only bring them up when user switches to slide show view.

**Comment by damithc** [comment]
This one is not urgent. We can discuss later what's the best way to do it.
