### ISSUE TITLE
'add captions' doesn't work unless I click on the slide thumbnail first

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#691]
For example, if I type a sentence in the slide notes and click on 'add captions', it does not add captions.  I have to click on the slide thumbnail (on the left) and then click on the 'add captions' for it to work. This was not the case earlier.

**Comment by nevet** [comment]
This is very interesting, I haven't modified any logic related to this since a few months ago :O any way, I fixed this issue, but not sure if any regressions would happen. Could @Ohohcakester help me run all tests that related to selected slides? Thanks so much :D

**Comment by kai33** [comment]
Cause:
currentSelection is type ppSelectionNone, but currentSelection.SlideRange has the selected slide.

so the condition for selectedSlide should be something like this:
if (CurrentSelection.Type == PpSelectionType.ppSelectionSlides ||
        CurrentSelection.SlideRange.Count > 0)

**Comment by nevet** [comment]
It sounds reasonable. But what if we selected nothing? In this case, ```CurrentSelection.Type == PpSelectionType.ppSelectionNone``` and ```CurrentSelection.SlideRange``` throws exception as well. Actually I mimic the implementation of ```CurrentSlide``` in ```PowerPointCurrentPresentationInfo```, that uses try-catch to handle invalid access to ```SlideRange```.

**Comment by damithc** [comment]
What's the status on this?

**Comment by Ohohcakester** [comment]
This was fixed in e03179bf488b4ca4a01b1c2ba9ae5213863814eb.
