### ISSUE TITLE
Follow transitions used in the first agenda slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#694]
Template slide is not useful in specifying a slide transition go to to/from agenda slides. Perhaps we can pick the transitions from the first agenda slide? Note that there are two transitions to pick.

**Comment by nevet** [comment]
I'm a bit confused here. So if the user specify a transition for a
specific agenda slide, but also a transition on the template slide, should
we use the transition of template, or keep the original transition of that
slide?

On Friday, April 24, 2015, Damith C. Rajapakse <notifications@github.com>
wrote:

> Template slide is not useful in specifying a slide transition go to
> to/from agenda slides. Perhaps we can pick the transitions from the first
> agenda slide? Note that there are two transitions to pick.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerPointLabs/powerpointlabs/issues/694>.
>


-- 
Best Regards,
Huang Da (Mr.)
National University of Singapore, Computer Engineering, Year 4
+65 86552730

**Comment by damithc** [comment]
First I thought we shouldn't expect the user to specify a transition from
template slide to the next slide (which is the first slide of the
presentation) because the template slide is hidden and the desired
transition may not work for the next slide. But it may be ok. So let's pick
the transition from the template slide, which is the neater way to do it.
But remember to pick both entry and exit transitions.

**Comment by nevet** [comment]
Hmm, I guess a user could only specify the entry transition? The exit
transition is actually the entry transition of the next slide, so the exit
transition of an agenda actually depends on the transition specified on the
next slide of that agenda slide, did I get anything wrong :S

Best Regards,
Huang Da (Mr.)
National University of Singapore, Computer Engineering, Year 4
+65 86552730

**Comment by damithc** [comment]
May be we can do just the entry transition. Users can specify the exit
transition manually, using the next slide.
