### ISSUE TITLE
Provide a way to prevent revealing future agenda items

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#695]
Currently, all agenda items are shown in the agenda slide. Some users might not want to reveal items not yet discussed.

**Comment by nevet** [comment]
ic. So how about we provide it as a setting? Or a simple checkbox?

On Friday, April 24, 2015, Damith C. Rajapakse <notifications@github.com>
wrote:

> Currently, all agenda items are shown in the agenda slide. Some users
> might not want to reveal items not yet discussed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerPointLabs/powerpointlabs/issues/695>.
>


-- 
Best Regards,
Huang Da (Mr.)
National University of Singapore, Computer Engineering, Year 4
+65 86552730

**Comment by damithc** [comment]
This is only useful for bullet point agenda right? May be add the setting
to the template slide?
e.g. "Reveal future agenda items? Yes"

**Comment by Ohohcakester** [comment]
A solution from user's perspective: start each section with a blank slide.
The slide won't be visible until after the zoom, but after the section and the step back to the agenda slide, the section will be visible.

**Comment by damithc** [comment]
To clarify, currently we show all topics in the agenda slides, even the
topics we have not discussed yet. Some users may not want to reveal
upcoming topics in advance, until they've reached the topic or even until
they've finished discussing the topic (to keep the audience in suspense).

e.g.
* Discussed topic 1
* Discussed topic 2
* Current topic
* .....
* ....

**Comment by Ohohcakester** [comment]
Oh, right. I was thinking of the visual agenda.

Well, a fix for the bullet points version would be to change the font colour of "unvisited" to white.
This assumes the background is white, though. Not sure if there is a transparent text option in powerpoint for cases where the background isn't a single colour.

**Comment by damithc** [comment]
There is a way to make text transparent, but no one except hardcore users
know it. May be better to give it as a visible option.

**Comment by damithc** [comment]
There is a manual way to achieve this: change the 'fill color' of the unvisited items to 'none'. However, it is better if we can provide a way for users to do this by simply setting a config value in Agenda Lab.

**Comment by jamos-tay** [comment]
Can I work on this?

**Comment by damithc** [comment]
@jamos-tay sure, what's your plan (in terms of UI)?

**Comment by jamos-tay** [comment]
I would probably use a menu option similar to other labs that opens a dialog for settings to be set:

![image](https://cloud.githubusercontent.com/assets/19278089/22405707/b79ad1a4-e681-11e6-8d87-f3519235d392.png)

This would require Agenda Labs to be moved out of the subgroup, though.

**Comment by damithc** [comment]
> I would probably use a menu option similar to other labs that opens a dialog for settings to be set:

I think that's a bit too big a change. It's better if we can stay within the same paradigm used to control other settings. Perhaps we allow the user the delete the text of the relevant bullet point in the template slide instead?

**Comment by jamos-tay** [comment]
> Perhaps we allow the user the delete the text of the relevant bullet point in the template slide instead?

Sure, I'll check if the bullet point is deleted.

**Comment by damithc** [comment]
It's even better if the mechanism is to replace the text in that bullet point with a space (see screenshot) instead of deleting the entire bullet point. That way, the user can change his mind later and add some text to make the future points visible again. 

![image](https://cloud.githubusercontent.com/assets/1673303/22412239/403fa312-e6e7-11e6-9c44-17d342e39800.png)

Furthermore, agenda slides we generate should show the bullet without the text so that the audience can see how many points are left without seeing what those points are, like so:
![image](https://cloud.githubusercontent.com/assets/1673303/22412261/85196590-e6e7-11e6-8994-3cf8d878b74c.png)
