### ISSUE TITLE
Renaming a section should not reorganize the agenda side bar

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#700]
Once the user has organized the items the sidebar, we should try to stick to that organization.

**Comment by damithc** [comment]
@Ohohcakester can anything be done about this?

**Comment by Ohohcakester** [comment]
Currently, the sidebar is reorganised when sections are added, deleted or renamed.
The reason why renaming sections also reorganises the sidebar is that renaming can change the width of the name. (e.g. if I renamed all sections from "Sect" to "VeryLongSectionName"). This changes the number of sections that can fit in one row of the beam, requiring the arrangement to be reconfigured.

**Comment by Ohohcakester** [comment]
Added it as an option in 6875a3bb847c6550b36ff3b27495a3f4942ba73a
