### ISSUE TITLE
Unhandled exceptions when switching views

### ISSUE THREAD

**Issue by Ohohcakester** [PowerPointLabs/PowerPointLabs#702]
Clicking these buttons under "View" cause exceptions:
1) Reading View
2) Handout Master
3) Notes Master

**Comment by nevet** [comment]
The cause of these exceptions are different.

Reading View: unexpected trigger of slideShowEnd event;

Handout View: unexpected trigger of slideChange event.

**Comment by Ohohcakester** [comment]
Yup, they are all different.

**Comment by damithc** [comment]
Clicking what buttons cause this exception? Is this related to a specific pptlabs feature (if yes, label accordingly).

**Comment by kai33** [comment]
All are related to RecorderTaskPane (feature: Record Audio).
Luckily, exception is caught by ppt application, so no error window will be shown. only developer will be notified in the Debug mode
