### ISSUE TITLE
Automation testing framework for PowerPointLabs

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#706]
Under construction...
---
#### Why need Automation Testing Framework
- Easy to use & test pptlabs
- Ensure correctness & prevent any regression
- More confident when we update/refactor legacy codes

#### Target state
- has the potential to achieve 100% line coverage of pptlabs code base
- able to auto test major features of pptlabs
- easy to write test cases for the newcomers

#### What is it about
It will consist of
##### Functional Testing (integration testing with PowerPoint, may not be a UI Testing).
- Unit Testing will highly rely on Dependency Injection to isolate the class under test. This class under test should only communicate with abstract classes or interfaces, so that its dependency can be easily substituted with our mocked ones. **BUT** after static analysis, the current code base is full of static/global calls, which is difficult to mock them all for Unit Testing (PS. solutions like JustMock & TypeMock is not free; Microsoft Fakes is OK to use, but requires some config; MOQ cannot mock static/private/sealed etc...) Certain refactoring is needed to make it more testable.
- As all of pptlabs features heavily depend on PowerPoint object model (shape, selection, shapes, slide..), this model should be mocked and shared as a class library for the ease of unit testing.
- Functional Testing requires the testing framework has the ability to communicate with pptlabs add-in within the PowerPoint sandbox and the ability to verify the object model in PowerPoint. This can be achieved through .NET inter-process communication.

#### Proposal
- **P1** Functional Testing should be done first, as it's easier to do compared to the other two, almost no refactoring is needed so no new bugs could come, and we already had some testing templates in doc/test folder that can be used for Functional Test.
![slide2](https://cloud.githubusercontent.com/assets/3591355/7941487/3a978e66-098a-11e5-88a3-173dfea77e09.png)
![slide1](https://cloud.githubusercontent.com/assets/3591355/7670884/79c5789e-fce9-11e4-8821-0bf9a979129d.jpg)
- **P2** After Function Testing part is there, certain refactoring can be started. The target of this refactoring is to ensure the testability is good enough for the upcoming Unit Testing, e.g. no static calls anymore, only communicate with abstract or interface...
- **P3** Mock Ppt Object Model & Unit Testing then can start after the testability of code base is good.
![slide3](https://cloud.githubusercontent.com/assets/3591355/7941808/5748fb2e-098c-11e5-9854-bf2b1277e127.png)
![slide4](https://cloud.githubusercontent.com/assets/3591355/7941809/579724c0-098c-11e5-86dc-37b44993e61e.png)
- **P4** Gradually improve the code coverage to ~80%

#### Timeline
...

**Comment by nevet** [comment]
could you explain more about your testing plan? and how could we help you build this framework up? Maybe you could post your design of this framework here before you started real coding :)

**Comment by kai33** [comment]
just updated some content. pls post here if anything unclear

**Comment by Ohohcakester** [comment]
What will you be using the build the Functional Testing framework?
Also, how will we verify that a test has passed? The results we want to achieve are ultimately visual.

I think we could also include a simple test that runs through the various sequences of buttons in powerpoint to make sure nothing triggers an exception.

**Comment by kai33** [comment]
Basically it's verifying ppt objects' properties. To a certain extent, we still need to verify the animations manually, and then prevent any regression automatically by the auto testing.
