### ISSUE TITLE
Text change to default color when trying to highlight bullets

### ISSUE THREAD

**Issue by Ohohcakester** [PowerPointLabs/PowerPointLabs#709]
I encountered a few bugs while trying to figure out the Highlight Bullets code.
1. Occasionally, highlight bullets changes all the text to orange (instead of red, then to black). I haven't figured out what exactly causes this issue.
2. When you have a text box containing all of these three, using highlight bullets while the text box (not the text) is selected will cause an exception:
   - lines with bullet points,
   - lines without bullet points
   - empty lines (no text)

**Comment by Ohohcakester** [comment]
I've fixed issue 2 in the Fixes-HighlightText branch, but I can't figure out how to fix issue 1.
Trying to set effect.EffectParameters.Color2.RGB in HighlightBulletsText.cs occasionally does nothing. Must be something going on behind the setter method.

A sequence of steps that reproduces bug 1:
 1. Select text on a slide and apply highlight bullets (not the one with the background)
 2. Undo the change.
 3. Ctrl+C, Ctrl+V on the slide to copy paste the **slide**.
 4. Select the same text on the same slide (not the copy)
 5. Apply highlight bullets on the text.

The text should turn to orange (default colour) instead of red/black. If this does not occur, undo and repeat step 5. It should be orange this time.

**Comment by damithc** [comment]
@Ohohcakester is this fixed?

**Comment by damithc** [comment]
Closing for now.
