### ISSUE TITLE
'Sync agenda' does not respect height of text box

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#713]
In this case, I've tweaked the height of some items (because the text is longer) like this:
![image](https://cloud.githubusercontent.com/assets/1673303/7787003/717c674c-0225-11e5-9f2d-28d2cd2c133b.png)

After the sync, it ended up like this:
![image](https://cloud.githubusercontent.com/assets/1673303/7786998/3724b9e6-0225-11e5-8123-7706d9d0064e.png)

**Comment by damithc** [comment]
Now the text box size is respected. But line indentation is not. 
![image](https://cloud.githubusercontent.com/assets/1673303/8568350/7ad5cc78-259f-11e5-8485-b6d0c7953a3f.png)

**Comment by damithc** [comment]
Check if this issue is still relevant. Some parts of AgendaLab was rewritten since the issue was posted.

**Comment by Kenneth-LJS** [comment]
![image](https://cloud.githubusercontent.com/assets/21071217/22234645/9f39f172-e234-11e6-81ed-604769626e75.png)

![image](https://cloud.githubusercontent.com/assets/21071217/22234651/a7a46d4c-e234-11e6-9faf-ce9f529d99a3.png)

Alignment isn't followed for highlighted agenda.

**Comment by damithc** [comment]
I see. Go ahead and try to fix it.

**Comment by damithc** [comment]
Seems the original issue is fixed. Closing.
