### ISSUE TITLE
'Sync agenda' got stuck while syncing agenda sidebar

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#714]
I generated agenda sidebar for the quick tutorial slides. Tweaked the sidebar to be on the left of the slide, and tried to sync. The process got stuck after regenerating a few slides and remained there forever. I may have clicked on on the slides while the syncing is going on though.

**Comment by Ohohcakester** [comment]
This issue no longer exists due to changing the way the agenda lab syncs.
