### ISSUE TITLE
Some visual agenda slides do not have the pptlabs logo

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#715]
![image](https://cloud.githubusercontent.com/assets/1673303/7787401/d8f60966-023c-11e5-8a8a-7f91286b5a51.png)

**Comment by nevet** [comment]
Is this an regression because of Auto-Zoom feature @Ohohcakester?

**Comment by Ohohcakester** [comment]
Just checked. It's not a regression from Auto-Zoom. It has always been like that, even before I made my first commit to this repository.

**Comment by Ohohcakester** [comment]
Fixed in 207ecf21c0b3b9bf88cec58dfd7c095bed933252
