### ISSUE TITLE
Give a better name for the auto-generated section

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#716]
Section name is visible to the user. May be give a more informative name? e.g. 'Section generated by PowerPointLabs - do not edit'
![image](https://cloud.githubusercontent.com/assets/1673303/7787403/fe832506-023c-11e5-8f44-9aff33af2a73.png)

**Comment by Ohohcakester** [comment]
Auto-generated section no longer exists.
