### ISSUE TITLE
Rename 'Highlight bullets' to 'Auto Highlight'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#720]
Auto Highlight is more consistent with the other names

**Comment by damithc** [comment]
May be we can move spotlight feature under 'auto highlight'?

**Comment by Ohohcakester** [comment]
I think spotlight might fit with auto crop better.
All of the three highlight bullets buttons operate on text boxes, while spotlight doesn't.

**Comment by damithc** [comment]
At a higher level, the three text highlighting and spotlight are all
'highlighting'  an area of the slide to draw attention to it. I prefer to
go by the intent rather than the mechanism :-)

**Comment by nevet** [comment]
I think we should put/ rename all features into some Labs eventually to be consistent with our brand name: PowerPointLabs.

**Comment by Ohohcakester** [comment]
Putting features in a lab increases the number of clicks required to access them, though.

**Comment by nevet** [comment]
True, but we could use split button, like Add Audio in the current version. We could put the most frequent used feature in the button, and put other features in the split menu.

**Comment by damithc** [comment]
Yes, i like the idea of naming everything as '* labs'.
