### ISSUE TITLE
Installer failed to install when VSTO runtime is not installed correctly

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#728]
Actual:
users clicks 'start installation' from installer UI, but nothing happens.

Expected:
should start install after the clicking.

Problem description:
0. VSTO is the runtime required by every office add-in. It's installed by Office by default.
1. when VSTO is installed correctly, just normal, everything can work fine. -- GOOD
2. when VSTO is not installed at all, our ClickOnce solution will guide the user to install VSTO (auto-download & auto-install later). -- GOOD
3. but when VSTO is not installed correctly (Microsoft's problem, no idea), there're 2 scenarios:
- a corrupted file exists and blocks the installing of office add-in. Our installer UI can detect this and inform the user how to handle it. -- OKAY
- everything related to VSTO is not working, and no error msg is displayed. -- That's the problem in this issue.

**Comment by kai33** [comment]
In the age of Web installer, we've encountered this issue.
Its behaviour is that, when start installation, it just shows a web page of xml.. re-install VSTO runtime will resolve it.

In current standalone installer, there will be no reaction at all, which is not friendly and confusing. It's better to provide a way to inform user to re-install VSTO runtime

**Comment by damithc** [comment]
Yes it seems to confuse some folks. What do you propose?

**Comment by kai33** [comment]
According to this add-in's guide:
http://support.dataeverywhere.com/article/48-error-the-value-of-the-property-type-cannot-be-parsed
They inform the user to rename the corrupted file + re-install VSTO runtime (may need Run as Admin).

I think we can follow this

**Comment by damithc** [comment]
@nevet @Ohohcakester any comments?

**Comment by cruzrincon** [comment]
There is absolutley NO way I can get to install this program. No matter what advice I follow. Must have reinstalled VSTO 1000 times. Renamed currupted files, Everything. The output is Error 0x80070002 "Installer General Error" for PowerPointLabs.vsto

**Comment by kai33** [comment]
@cruzrincon Hi, can you provide more information, like the error msg you encountered, any stacktrace?

**Comment by cruzrincon** [comment]
I'll show you a demonstration (Video duration aprox. 12 sec):

[![Demonstration](http://content.screencast.com/users/cruzrincon/folders/Snagit/media/ed7264a2-dd42-4010-949e-16f6ca3d51db/04.30.2016-08.52.png)](http://screencast.com/t/G9LdFyYT "Demonstration")

**Error translation:** "The following  Microsoft Office solution cannot be installed becasuse of an installer general error: PowerPointLabs.vsto - CODE: 0x80070002"

Windows 8.1 (Spanish 64bit)
Office 2016 (Spanish 32bit)
VSTO 2010 (Spanish Language Pack)

**Comment by kai33** [comment]
It's an issue from ClickOnce side.
does this help?
http://stackoverflow.com/a/21427009

**Comment by cruzrincon** [comment]
This didn't solve the issue

**Comment by cruzrincon** [comment]
Nevermind. I solved this issue on my own:

(1) Extracted the contents of 'setup.exe' with 7zip.
(2) Inside there was a 'data.zip' that I also proceeded to extract to this Directory >> `C:\Users\Username\AppData\Roaming\PowerPointLabs`
(3) Located VSTOInstaller.exe (`C:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0`)
(4) Installed the addin with the following command >> 
`VSTOInstaller.exe /i 'file:///C:/Users/Username/AppData/Roaming/PowerPointLabs/PowerPointLabs.vsto'`
(5) DONE

**Comment by kai33** [comment]
I'm not sure why it can be installed in this way but not for the normal way.
FYI, by doing this, pptlabs also lost the ability to auto-update itself, and you may have to manually update it
