### ISSUE TITLE
Text agenda: The first agenda slide should have all items as unvisited

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#735]
Currently, the first item is highlighted.

**Comment by Ohohcakester** [comment]
Is this what you mean?
![image1](https://cloud.githubusercontent.com/assets/5209333/8400379/06998062-1e50-11e5-8858-885992c3a6b6.png)

**Comment by damithc** [comment]
Yes.

**Comment by Ohohcakester** [comment]
okay.
fixed in c0a40f6c8a8570f56fcfee991e8a7bc8390e3873

**Comment by damithc** [comment]
Can you add another slide at the end where all items are marked as visited? That can be used as the Q&A slide.

**Comment by Ohohcakester** [comment]
Like this?
![image1](https://cloud.githubusercontent.com/assets/5209333/8402170/37d844fe-1e6b-11e5-80c6-e60d81d575a7.png)

**Comment by Ohohcakester** [comment]
Like this?
![image1](https://cloud.githubusercontent.com/assets/5209333/8402216/c4d3cffe-1e6b-11e5-9f64-80c234fc4e7e.png)

**Comment by damithc** [comment]
Yes, like that.

**Comment by Ohohcakester** [comment]
okay.
fixed in b1d11b04cdf9b217297501c877f22a194efc3647
