### ISSUE TITLE
Agenda sidebar: highlighted text overlaps with first agenda item

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#737]
This is not optimal. Is there a better way?
![image](https://cloud.githubusercontent.com/assets/1673303/8402979/354a0616-1e73-11e5-9aab-934f717899a6.png)

**Comment by Ohohcakester** [comment]
How about this?
![image1](https://cloud.githubusercontent.com/assets/5209333/8404170/7b3c477e-1e7d-11e5-9666-266d3a66cba3.png)

**Comment by damithc** [comment]
Should be fine.

**Comment by Ohohcakester** [comment]
commit ddd925a0224c224b01782e01880e8cb4c9d9f007
