### ISSUE TITLE
text agenda: all items marked as visited in last few agenda slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#740]
It seems the last three agenda slides have all items marked as visited. Only the last slide should be like that.

**Comment by damithc** [comment]
If confirmed as bug, try to add tests to cover it before fixing it.

**Comment by damithc** [comment]
I also ended up having empty agenda slides while syncing (I deleted agenda slides of last two sections and tried to sync again). 
![image](https://cloud.githubusercontent.com/assets/1673303/8447026/fa4e5ada-1fe4-11e5-819b-f005102c2a8c.png)

**Comment by damithc** [comment]
The cause may be that the slide deck had some agenda slides I duplicated manually. May be that confused the sync algo

**Comment by damithc** [comment]
Nope, things get messed up even if I didn't have duplicated agenda slides. Last few agenda slides look fine the first time I generate them but all items get marked as visited after I sync them.

**Comment by Ohohcakester** [comment]
I can't seem to reproduce this bug.

**Comment by Ohohcakester** [comment]
This is the same issue as #742 
Should be fixed in 03bd8f0.
