### ISSUE TITLE
text agenda: last bullet stricken off of visited style uses 'strike off'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#741]
An extra bullet point appears with the 'strike off' style if the 'strike off' is used as the 'visited' style
![image](https://cloud.githubusercontent.com/assets/1673303/8473477/7ed14400-20dc-11e5-860b-f49a80131fc0.png)

**Comment by Ohohcakester** [comment]
Fixed in bf2d3870db0c0503ec6a9a864e33d85a97545201
Though not in the public release yet.
