### ISSUE TITLE
Exception while importing individual shape

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#743]
Rightclick on shapes lab and choose 'import shapes', choose a file to import, and I get this error.
```
System.NullReferenceException
Object reference not set to an instance of an object.
Stack Trace:
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.CopyShape()
   at PowerPointLabs.CustomShapePane.ImportShapesFromSingleShape(PowerPointShapeGalleryPresentation importShapeGallery)
   at PowerPointLabs.CustomShapePane.ImportShapes(String importFilePath, Boolean fromLibrary)
```

**Comment by damithc** [comment]
This feature is buggy, so we might not want to release it at this time. I think the live site already contains shape galleries that correspond to this features, released by mistake by @nevet 
We should remove that too.

**Comment by kai33** [comment]
Bug cause:
_defaultCategory is null when import shape at
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/Models/PowerPointShapeGalleryPresentation.cs#L193

1. https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/CustomShapePane.cs#L347

the import shapes' file filter should be "pptlabsshape", but it uses filter "pptlabsshapes", which is for import library.

2. https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/Models/PowerPointShapeGalleryPresentation.cs#L265 
condition check should be > 0

3. other potential bugs for this variable:
_defaultCategory is set to null in some cases in PowerPointShapeGalleryPresentation.cs, which will result in similar exception errors.

**Comment by damithc** [comment]
@kai33 are you planning to fix this soon? This feature is almost done, so we can release it soon if this bug is fixed.

**Comment by kai33** [comment]
yes im fixing it

**Comment by kai33** [comment]
this issue's deployment requires an update in the website, at this page:
add our shared shapes 
http://www.comp.nus.edu.sg/~pptlabs/gallery.html
and likely some documents on import shapes for ShapesLab
http://www.comp.nus.edu.sg/~pptlabs/docs.html
@Ohohcakester can help?

**Comment by Ohohcakester** [comment]
Yeah, I had previously hidden the shapes gallery on request by @damithc. I've already restored it in my local build.
I'm writing the documentation too.
