### ISSUE TITLE
text agenda: slide background color of the template slide is not synchronized

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#744]
If I change the slide background color, it is not synced with other agenda slides

**Comment by Ohohcakester** [comment]
Did quite a bit of searching, but I can't seem to find any working API to set the slide background to be the same as another slide's.

**Comment by Ohohcakester** [comment]
Add sync for solid background colour only: 
2e66084659e66a784cbf9d14bc69cdd355fb80f7 and 0912c213cba4204a417fca42821c60e5a83e6b8e
