### ISSUE TITLE
agenda sidebar: if only one slide is selected, ask if intending to generate for entire deck

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#746]
In many occasions I ended up generating sidebar for only one when I intended to generate for entire deck. Reason: I though no slide is selected, but in fact one slide was auto selected (e.g. immediately after clicking 'remove agenda').
It is unlikely the user want to generate sidebar for only one slide. So we can pop up a dialog box to ask if the user intended to generate for the full deck or only for that slide.

**Comment by Ohohcakester** [comment]
Added in 1594c1bcdd6ddf162ef42a3a488eb28e7629507d
