### ISSUE TITLE
Rephrase agenda lab menu

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#760]
![image](https://cloud.githubusercontent.com/assets/1673303/8598262/4daad96c-268c-11e5-8978-7c68982b8933.png)
For consistency, it should be like this (starting with a verb)?
Generate text agenda slides
Generate visual agenda slides
Generate sidebar agenda
Remove ...
Synchronize ...

**Comment by damithc** [comment]
@Ohohcakester what do you think?

**Comment by Ohohcakester** [comment]
I also thought the phrasing for the first three was a little weird as well.
But "Generate text agenda slides" is a little long. We need something that will fit nicely.
Perhaps "Create Text Agenda, Create Visual Agenda, Create Sidebar Agenda, Remove Agenda, Synchronize Agenda"

**Comment by damithc** [comment]
Sure, that works too.

**Comment by damithc** [comment]
Can be done before next release? If yes, assign the milestone.

**Comment by Ohohcakester** [comment]
Fixed in c1d160f2ae2466f2b9abef12c4f1dd2f2d45c7a5
