### ISSUE TITLE
Mac PPT11: noticeable textbox displacement for AutoZoom in Visual Agenda

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#763]
I played the example slides (http://www.comp.nus.edu.sg/~pptlabs/samples/Agenda%20Lab%20Example%20-%20Visual%20Agenda.pptx) in Mac PowerPoint 2011, and it shows some noticeable textbox displacement in Visual Agenda's zooming. Not sure if it can be solved..

it looks fine in my Win PPT 2013.

some screenshots from Mac PPT:
![slide09](https://cloud.githubusercontent.com/assets/3591355/8610775/7be2948e-26e9-11e5-8594-ce54df865165.jpg)
![slide10](https://cloud.githubusercontent.com/assets/3591355/8610776/7c5bce80-26e9-11e5-80e4-52f28331625f.jpg)
![slide11](https://cloud.githubusercontent.com/assets/3591355/8610778/7c6af05e-26e9-11e5-8474-bc232c7d488c.jpg)
![slide12](https://cloud.githubusercontent.com/assets/3591355/8610777/7c610db4-26e9-11e5-8717-9725a147ad81.jpg)

**Comment by damithc** [comment]
By displacement, did you mean the content shift a bit at the end of the zoom animation?

**Comment by kai33** [comment]
yes

**Comment by damithc** [comment]
Let's say the behavior is not guaranteed on Macs
