### ISSUE TITLE
Add documents for developers

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#769]
Similar to https://github.com/TEAMMATES/repo/blob/master/devdocs/design.md

The reasons behind it:
pptlabs is 2 years old. Tech stacks already become huge to learn from the beginning, different conventions exist in the codebase so don't know which is correct to follow, features may be lack of documents to trace and refactor, etc. so we need a design document to
 
1. describe the project's architecture, so that developer grasps pptlabs project easier and won't do something like writing feature's logic in the UI layer.
2. describe the convention & tech we should follow. e.g. there will be more features require a UI interface (at the sidebar; we call it 'pane'), in this case WPF (UI tech) is preferred over Winform, since Winform is hard to customise and error-prone when customise it.
3. ...

**Comment by damithc** [comment]
Yup, this will be immensely useful. Thanks for volunteering :-)
