### ISSUE TITLE
Updating pptlabs may cause it to disappear

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#772]
I guess it's caused by changes of certificate. 

Our test certificate's only valid for 1 year. when certificate is changed and pptlabs is to update, the update  system (by MS ClickOnce) will ask user whether to trust & install/update this add-in (because certificate is add-in's identifier, if it's changed, ClickOnce will ask user whether to trust the new identity).

At this moment, if user clicks NO (don't trust new certificate), then our add-in will disappear from the ribbon.

Solution:
1. provide instructions page to guide user how to make it appear again.
2. modify our certificate to make it valid for a longer time.

**Comment by damithc** [comment]
Let's do what we can.

**Comment by kai33** [comment]
extended the validity of certificate for 5 years
