### ISSUE TITLE
Create a page for pptlabs reviews

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#778]

**Comment by kai33** [comment]
some reviews so far:
http://www.free-power-point-templates.com/articles/powerpoint-labs-highlight-slide-content-using-spotlight-animations/
http://www.brightcarbon.com/blog/review-of-powerpointlabs-add-on-for-powerpoint/
http://blog.indezine.com/2014/01/powerpointlabs-conversation-with-damith.html

**Comment by suheti** [comment]
Please check whether this seems OK. Thanks! @damithc 

<img width="1282" alt="screen shot 2015-10-14 at 3 49 00 pm" src="https://cloud.githubusercontent.com/assets/6445296/10477723/2986b6b4-728b-11e5-9112-1ba5625b9a01.png">

**Comment by damithc** [comment]
The second heading could be 'Reviews/articles'.
For the first part, put a few more quotes?

**Comment by suheti** [comment]
Would this do the job? @damithc 
<img width="1228" alt="screen shot 2015-10-14 at 5 07 54 pm" src="https://cloud.githubusercontent.com/assets/6445296/10479309/30ef62ec-7296-11e5-9892-aef3e4398255.png">

**Comment by damithc** [comment]
looks good.

**Comment by damithc** [comment]
Here's another http://www.ispringsolutions.com/blog/boost-your-powerpoint-7-free-powerpoint-add-ins/

**Comment by damithc** [comment]
Missed one review (see comment above). Open a new issue?
