### ISSUE TITLE
Update documents for shortened context menu

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#780]
parts that require to be updated in the document:
- auto animate (short sentence)
- auto narrate (screenshot)
- shapes lab (short sentence)
- shortcuts (short sentence)

to find the part to update, search for 'right-click' in the doc page; some 'right-click' isn't related to the office's context menu though.

#597

**Comment by damithc** [comment]
Also check the tutorial file.

**Comment by kai33** [comment]
checked, nothing related to context menu

**Comment by damithc** [comment]
Raising priority because need to fix before next release.
