### ISSUE TITLE
VSTO download link in Installer is outdated

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#783]
hardcoded link can be found here:
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabsInstallerUi/PowerPointLabsInstallerUi/Form1.cs#L16

it's better to:
1. replace that hardcoded link with a link to a webpage in our website
2. and that webpage will re-direct the user to the VSTO download link
3. so next time when VSTO download link has been changed by MS, we can just update the re-direct URL in the webpage, instead of re-deploy a whole new installer

**Comment by damithc** [comment]
What's the implication? older pptlabs does not auto-update anymore?

**Comment by kai33** [comment]
This VSTO download link is used, when the installer finds out that the user doesn't install VSTO runtime or its VSTO runtime is corrupted.

it happens before installation, so not related to auto-update

**Comment by damithc** [comment]
That's a relief. Still, better fix it.

**Comment by kai33** [comment]
uploaded redirect page contributed by Yan Xu here
http://www.comp.nus.edu.sg/~pptlabs/vsto-redirect.html

need to change the url link in the pptlabsInstallerUI
