### ISSUE TITLE
let Auto Animate throw unknown exception stacktrace

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#785]
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/AutoAnimate.cs#L45
and 
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/AutoAnimate.cs#L104

**Comment by damithc** [comment]
What's the solution?

**Comment by kai33** [comment]
No solution yet.
Looks like these values all become zero (point1x, point1y, point2x, point2y) when bug happens:
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/DefaultMotionAnimation.cs#L221

**Comment by kai33** [comment]
The user said she could reproduce the bug in another device (also Win10 + Office13).
2 new developers have the same environment, I'll ask them for help.

**Comment by kai33** [comment]
1 developer (Yan Xu) said no problem in his device.

**Comment by damithc** [comment]
From my experience, it happens randomly. Even that user says it works sometimes.
