### ISSUE TITLE
VSTO is corrupted, but still can install without renaming the corrupted file

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#791]
This issue is found on Yan Xu's win10 device.

1. VSTO is detected as 'corrupted'.
2. rename the file won't help install the add-in (it will re-download VSTO to install and recover the corrupted file).
3. instead, install it anyway without renaming the corrupted file will be successful.
Maybe MS did some changes for VSTO in win10..

Sol:
aft #784 is resolved, provide an instruction to tell user to 'install it anyway' for this case.

**Comment by damithc** [comment]
Let's fix these small issues that are pending and do another release while we wait for images lab feature to release.
