### ISSUE TITLE
Tidy up contact.html

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#792]
Give Xie Kai as team lead
Damith as Founder and mentor
Separate out past members (Raunak, Huang Da)
Add a contributors section.

**Comment by suheti** [comment]
Please check and feedback on this change. Thanks! @damithc 

<img width="1227" alt="screen shot 2015-10-14 at 4 49 45 pm" src="https://cloud.githubusercontent.com/assets/6445296/10478995/caa5ac28-7293-11e5-886c-3371a805b9a9.png">

**Comment by damithc** [comment]
Looks good. I want to add some more details, but we can do that later as a separate issue.
