### ISSUE TITLE
Show user testimonials in the web site 

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#798]
May be similar to how we do it in TEAMMATES?

Here are some we can show:

I downloaded the PowerPoint Labs plugin...this is great! I can see a lot of different ways how I can use this to make better presentations and videos! It really enhances my ability to visually communicate complex topics. -- Jeff 

I will just say that your product is awesome and has helped so much in delivering presentations that would realistically have taken so much longer to produce. -- Grant Roberts, UK

As I am a power user of PowerPoint, I truly appreciate those usable and powerful features that are provided with the plugin. --Simon, Singapore

Dear PowerpointLabs. Your add-in is so awesome. -- Phung, Vietnam

This looks fantastic - very impressive and relevant additional functionality -- Weir, New Zealand

This looks awesome - thanks for making it! --Tash, New Zealand

Thanks guys for this awesome add-in. I´m looking forward to create awesome presentations with this features that you just gave me. -Jarami

The magnifying glass alone is priceless. It's spot on as far as meeting a need. -- Lauren, New Zealand

The demo/activity slide deck was wonderful. ‘out of the box’ and working near instantly. -- Robert, Chicago

I want to thank you for developing such cool features for PowerPoint productivity. I already contacted a bunch of friends and encourage them to try it on. Specially, the Shapes Lab utility, it is one the greatest time savers I could find. -- Jimmy, Peru

While I have just started to run through the tutorial for your PowerPoint plug-in. It is very impressive. -- Dan, Australia

Awesome plug-in! Thank you so much. This really helps give PPT some of the features that Keynote shined at. (i.e. Magic Move, etc.) This will be a fantastic timesaver! -- Joe, Minneapolis

**Comment by damithc** [comment]
Another:
It looks fabulous, and you have done a wonderful job. --Walt, Nebraska

**Comment by damithc** [comment]
A True useful tool. Kudos to developers. --Mahesh, India

**Comment by damithc** [comment]
Just wanted to say this add on is absolutely fantastic and a real help when developing my eLearning materials.-- Ian, UK

**Comment by damithc** [comment]
I have to say, I'm very impressed with what I see in this so far. -- Ray, USA

**Comment by damithc** [comment]
Just discovered this plug-in, and i have fallen in love with it, only after the first 10 pages of the tutorial! --Migauel

**Comment by damithc** [comment]
Let's do this soon. It can help get more users. May be we can use the same javascript used by TEAMMATES

**Comment by damithc** [comment]
I've just tried out your software, and I must say it's a excellent idea to supercharge PowerPoint presentations. -- Lasith, Japan

**Comment by LIUJIAHAOCS** [comment]
OK, I will get it done soon.

**Comment by LIUJIAHAOCS** [comment]
<img width="1097" alt="screen shot 2015-12-04 at 3 46 41 pm" src="https://cloud.githubusercontent.com/assets/14244291/11584342/40e7f5ee-9a9e-11e5-8d0b-0beb6a628a78.png">
Does this good ok? I have selected some long ones as some are only one line.
