### ISSUE TITLE
Add more details when download image failed

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#799]
I'm using drag and drop from chrome. I got this several times
![image](https://cloud.githubusercontent.com/assets/1673303/10752404/d41b2028-7cc3-11e5-9edc-cd5ad8703557.png)
I suspect it happens when I drop more images while previous ones are still loading (but not sure)

**Comment by damithc** [comment]
It happened even when only one image was dropped. I retried with the same image and it worked the second time. So it is not something specific to a particular image.

**Comment by kai33** [comment]
Sir can you provide the image link? 
When drag 'an image' from google image search, it actually only drags its link. Then the program will parse the link to get image URL, download and display it.

Possible cases that produce this error msg:
1. Google updates its URL format that fails the parsing
2. Download failed (timeout or download incompletely caused by network)
3. Downloaded file is not a proper image. E.g. some websites will redirect the image URL to other HTML pages, which will be downloaded instead of the image.

**Comment by damithc** [comment]
Same image was downloaded when I tried a 2nd time. The failure rate was about 1/3. It was similar even for previous version. May be the error message can display more information about what happened?

**Comment by kai33** [comment]
I would need the link to analyse the problem because I cannot reproduce it for now.

e.g. I try keyword 'sea' and 'steve jobs' and drag and drop their first 10 images without problems

**Comment by damithc** [comment]
I cannot reproduce it now either. In any case, just add some more details to the error message in case it happens again. I suspect it is a timeout.

**Comment by damithc** [comment]
I didn't get it again so far. May be related to VSTO update?

**Comment by kai33** [comment]
umm i guess VSTO won't help this issue.
When next time the error window shows up, it will display more details telling what's the cause

**Comment by damithc** [comment]
Here's a link that always say image is corrupted http://www.google.com.sg/imgres?imgurl=http://migreat.files.wordpress.com/2014/07/istock_000038047046_large.jpg&imgrefurl=http://blog.migreat.com/2014/09/15/are-you-eligible-for-the-uk-internship-visa-tier-5-gae-visa/&h=1737&w=2829&tbnid=OfkdQxHk-AzMUM:&docid=kQ-VJN7nkANLzM&ei=NZ4xVrX1NcHYmAW56JWQAg&tbm=isch&ved=0CEAQMygQMBBqFQoTCPXj5uLp5sgCFUEspgodOXQFIg

**Comment by damithc** [comment]
BTW, when the loading failed, the 'loading' place holder remains permanently. 

Here's another one https://pbs.twimg.com/media/CSbLpacWoAARCX7.jpg:small

**Comment by kai33** [comment]
updates:
1. when fail to download, remove the 'loading' image
2. with new message content:
"Failed to load image. Please try again; or manually download the image and drag it to Images Lab."
