### ISSUE TITLE
Smoothen workflow when moving to a new slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#801]
Let's say I tweaked slide 2 and go to slide 3.

1. I prefer to stay in 'customize' stage rather than to start from 'style' stage again. I've already customized the style the way I wanted (when doing slide 2) so I would like to continue from there.

2. It should not show the same image as slide 2. That could be misleading. In almost all cases we will not be using the same image in two slides. Options: a. Load image from slide (if it already has one), b. Show slide without any image, c. Load the next image in the image collection

**Comment by kai33** [comment]
as discussed, comment:
no problem for this issue

**Comment by damithc** [comment]
I still prefer not to use the image from the previous slide as the default image on a new slide.

**Comment by kai33** [comment]
duplicate #887
