### ISSUE TITLE
Allow user to apply style of one slide to another

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#805]
e.g. 
1. Load style from one slide
2. Change slide
3. Load image from second slide
4. Apply style

For the above to work, we should have separate 'reload image' and 'reload style' options rather than a single 'reload'.

**Comment by kai33** [comment]
as discussed, comment:
separate current 'reload' into
'reload image only' and
'reload style and image',
without 'going to the slide'

**Comment by damithc** [comment]
The file picker button can be named 'Select images' and use 'Load' instead of 'Reload' here?
Do they have drop-down buttons (like in TEAMMATES)?
'Load from slide' can be the main button while sub buttons can be
'Load image from slide'
'Load style from slide'

Alternatively, the Load button can go to the slide picker and the two options can be given in the slide picker.
