### ISSUE TITLE
Remove 'load images' dropdown

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#806]
Can we get rid of this dropdown entirely? If we do that, we need to change the message too.
![image](https://cloud.githubusercontent.com/assets/1673303/10753327/45083350-7ccb-11e5-8663-bd2674b76ab6.png)

**Comment by kai33** [comment]
as discussed, comment:
remove download button and its binding textbox,
turn the Load Image button into normal button style
