### ISSUE TITLE
Use non-permanent cropping when adjusting image size 

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#807]
Currently, the cropping seems to be permanent.

**Comment by kai33** [comment]
as discussed, comment:
for now it's cropped permanently, but the cropped region can be recovered.

Solving this issue will be useful, if somehow the style & image info hidden in the slide is removed,
then the user still can restore the cropped parts

**Comment by damithc** [comment]
Seems to be fixed now
