### ISSUE TITLE
Color changed when changing text position

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#808]
I chose 'text position' from the dropdown. The text box color changed from black to yellow at the same time.
![image](https://cloud.githubusercontent.com/assets/1673303/10779991/4b50b112-7d73-11e5-8a04-d112ca92cd0a.png)

**Comment by kai33** [comment]
as discussed, comment:
looks like a random bug. cannot re-produce it for now

**Comment by kai33** [comment]
proved by ut, no problem now
