### ISSUE TITLE
Make drop-zone remember its position

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#809]
e.g. if I remove it my other window where I do the image search, I would like it to remain there (or appear at the same location) until I move it again.

**Comment by damithc** [comment]
Doesn't seem to be fixed. I dragged the drop zone to my other monitor. But it went back to original location next time.

**Comment by kai33** [comment]
Is the add-in updated to version 2.8.2.2?

If yes, could you paste the content of dialog settings file here? which can be found at "C:\Users\[USER_NAME]\Documents\pptlabs_imagesLab\quick-drop-dialog.xml"

**Comment by damithc** [comment]
Yes, I'm using the latest dev. Confirmed doesn't work in both my comps.
```xml
<?xml version="1.0" encoding="utf-8"?>
<WindowInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Left>1376</Left>
  <Top>850.40000000000009</Top>
  <Width>-1</Width>
  <Height>-1</Height>
</WindowInfo>
```

**Comment by damithc** [comment]
BTW, shouldn't we use `username\pptlabs\imageslab` as the folder?
