### ISSUE TITLE
More than one aspect changed when customizing

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#813]
![image](https://cloud.githubusercontent.com/assets/1673303/10780140/440221aa-7d75-11e5-9355-a2fc1c940b3a.png)

**Comment by kai33** [comment]
This is intended to support default variations of Direct Text style.

The first 2 variants' font has black color, because their brightness are 140% and 120% so that it looks better.

**Comment by damithc** [comment]
I guess it's better not to do that here. It's not consistent with how the feature usually works (i.e. vary only one aspect an any time). It's hard to determine the opposite color at times (we can switch black to white, but from blue to what?). And depending on the image, the outcome may not be good anyway (e.g. first column, 2nd pic).

**Comment by kai33** [comment]
I'll try to explain in the meeting

**Comment by kai33** [comment]
as discussed, comment:
the intended default font colors are provided, because
1. speed up the process of applying it, otherwise user needs to further tweak the font colors
2. make user feel that the variation 'makes sense', otherwise some font colors will be blended with textbox or banner colors
