### ISSUE TITLE
Show context menu disabled instead of hiding

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#819]
Currently, context menu items are hidden when not applicable. The whole menu is not shown at all if none of the item are applicable.
May be disable instead of hiding?

**Comment by kai33** [comment]
ref
http://homepage2.nifty.com/suyamsoft/PowerPoint/Ribbon/ContextMenuID2010/index.html
http://homepage2.nifty.com/suyamsoft/PowerPoint/Ribbon/ContextMenuID/index.html

**Comment by oswellchan** [comment]
Currently working on this
