### ISSUE TITLE
Add more reviews to the website

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#820]
http://www.smallbusinesscomputing.com/biztools/5-cool-powerpoint-slide-design-tools.html

**Comment by LIUJIAHAOCS** [comment]
Added

**Comment by damithc** [comment]
Is there a PR for this?

**Comment by LIUJIAHAOCS** [comment]
I send together with the testimonial issue.

**Comment by damithc** [comment]
Each PR should fix one thing only. Otherwise it is harder to undo a specific fix later.

**Comment by LIUJIAHAOCS** [comment]
Ok, I will send the PR separately later.
