### ISSUE TITLE
Update website homepage and documentation for Office2016 support

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#824]
homepage
> For PowerPoint 2010, 2013, and 2016 on Windows.

FAQ in documentation (how come there are duplicate 'Frequently Asked Questions' sections.. one need to be removed)
> PowerPointLabs supports PowerPoint 2010, 2013, and 2016 on Windows.

**Comment by LIUJIAHAOCS** [comment]
<img width="1048" alt="screen shot 2015-12-11 at 2 49 44 pm" src="https://cloud.githubusercontent.com/assets/14244291/11737868/5c8853be-a018-11e5-886a-e048f883c793.png">
<img width="1222" alt="screen shot 2015-12-11 at 3 02 17 pm" src="https://cloud.githubusercontent.com/assets/14244291/11737873/647f115c-a018-11e5-85ba-2612873ce488.png">
Content Added. By the way, in the real pptlabs website i do find duplicate 'Frequently Asked Questions' sections. but at my updated version, no duplications. See the above pictures

**Comment by damithc** [comment]
Someone updated website without updating the repo.
