### ISSUE TITLE
Show a users count in the home page

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#825]
e.g.
150,000 benefited from PowerPointLabs so far... 
May be right above the testimonials?
JS code can be reused from TEAMMATES.

**Comment by LIUJIAHAOCS** [comment]
Does this user count is hardcoded or it is dynamic?

**Comment by LIUJIAHAOCS** [comment]
Understood. Working on it.

**Comment by LIUJIAHAOCS** [comment]
May I know which day to put as base date (150,000 users). and the increase rate per hour? for the teammates, they are using "October 30, 2015 00:00:00" and 27 per hour.

**Comment by damithc** [comment]
150,000 as at Nov 30th, and 21 per hour

**Comment by damithc** [comment]
Correction: 'benefited' changed to 'have benefited'

**Comment by LIUJIAHAOCS** [comment]
<img width="1207" alt="screen shot 2015-12-06 at 3 12 53 pm" src="https://cloud.githubusercontent.com/assets/14244291/11612203/e6470b68-9c2b-11e5-8c6c-9af2d650b508.png">

**Comment by damithc** [comment]
Looks good.

**Comment by LIUJIAHAOCS** [comment]
Ok. I will send PR after #798 merged.
