### ISSUE TITLE
Add installation troubleshoot to FAQ of documentation

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#828]
Q: Does PowerPointLabs support Mac Office?
A: It does not work for Mac Office at the moment.

Q: When I install PowerPointLabs, This message box shows up:
> “A corrupted system file is detected. 
> In order to install our add-in, you may need to rename the file [VSTOInstaller.exe.Config] in the folder ... to the new filename [VSTOInstaller.exe.Config.backup]. 
> However, in some PCs, the corrupted system file won't affect the installation. 
> Click OK button to continue.”. 

What should I do?
A: You can click the OK button to proceed. If installation fails and installer shows any error message, you will need to install again, follow the instruction in the message box to rename the file [VSTOInstaller.exe.Config], and then continue installation. 

Q: After install, no PowerPointLabs ribbon appears?
A: Restart PowerPoint, see if it appears. If not, follow these steps to re-activate PowerPointLabs:
1  In the PowerPoint application, click the ***File tab*** at the top left corner.
2  Click the ***Options*** button.
3  In the categories pane, click ***Add-ins***.
4  In the ***Manage box***, click ***Go***.
5  ***Tick the checkbox*** for PowerPointLabs to enable it, click ***OK*** and restart PowerPoint.

If it still does not work, follow these steps:
6  Open PowerPoint ***Options***.
7  Click ***Trust Center*** (the last tab).
8  Click ***Trust Center Settings...*** button in the Trust Center tab. A Trust Center window will be open.
9  Click ***Add-ins tab*** in the ***Trust Center*** window
10  ***Uncheck all*** checkboxes in it.
11  After that, repeat step 1~5 to enable PowerPointLabs

**Comment by LIUJIAHAOCS** [comment]
<img width="1159" alt="screen shot 2015-12-11 at 4 50 55 pm" src="https://cloud.githubusercontent.com/assets/14244291/11739565/725b3468-a027-11e5-8248-ba9b1a14a7a5.png">
<img width="1185" alt="screen shot 2015-12-11 at 4 51 06 pm" src="https://cloud.githubusercontent.com/assets/14244291/11739569/75ea0a3c-a027-11e5-8dc2-3c814dea8e7f.png">

Will this do the job? or should i remove the Blockquotes?
