### ISSUE TITLE
Some sections repeated in the Documentation page

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#830]
e.g. documentation of the 'make transparent' feature

**Comment by LIUJIAHAOCS** [comment]
The duplication only appears in the real website, in my local repo, it appears no duplication. I guess last time someone update the website wrongly but luckily without touching the repo.

**Comment by LIUJIAHAOCS** [comment]
<img width="1131" alt="screen shot 2015-12-11 at 6 02 07 pm" src="https://cloud.githubusercontent.com/assets/14244291/11741024/59992b4c-a031-11e5-86c9-0b7a04a598bf.png">
when i search for  "Make Transparent", in our website it shows 6, which is duplicate.
<img width="1123" alt="screen shot 2015-12-11 at 6 01 57 pm" src="https://cloud.githubusercontent.com/assets/14244291/11741045/77318532-a031-11e5-8cbc-c32831ce8872.png">
but when i search for it at my copy, it shows 3, which is correctly shown once.

**Comment by damithc** [comment]
@LIUJIAHAOCS Can fix?

**Comment by LIUJIAHAOCS** [comment]
http://www.comp.nus.edu.sg/~pptlabs/dev
It is fixed. Oh help me to upload the updated version to the dev website, and there is no duplications. Can verify if the website is ok? then we will update the actual website.
