### ISSUE TITLE
Support syncing of object across slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#833]
Requested by a user.
There should be a way to sync properties of an object across slides, if that object appears in multiple slides.

**Comment by damithc** [comment]
@Ohohcakester can this be parked under the drawing lab? This is one way the feature can be designed.
There is a way to designate an object as belonging to a 'sync group'.
User can modify an object, and propagate the modification to others in the same sync group.

**Comment by damithc** [comment]
Or may be a separate *Sync Lab* :-)

**Comment by kai33** [comment]
sounds like slide master

**Comment by damithc** [comment]
Slide master is suitable when something should appear in all (or a large number of) slides. This features is when you need an object or a bunch of objects in a few consecutive slides. 

Furthermore, users think in terms of 'synchronize' rather than 'slide master'. Another example of Microsoft providing just mechanisms and letting users figure out the connection between intention and mechanism.

**Comment by Ohohcakester** [comment]
Yes, I had originally thought of including that feature as part of the drawing lab. But I decided not to because it's a rather complex feature and drawing lab is already pretty jam-packed with features.
I have plans to include this feature at some point, but I haven't decided whether it should be placed under the drawing lab or somewhere else.

**Comment by damithc** [comment]
Now that I think about it, I think it should be a separate feature. Not only it is complicated enough on its own, it is a stand alone feature that can be sold on its own, to users whose drawing needs may not be heavy enough for drawings lab. It is ok if there is some overlap between the two features. My feeling is most users pick just a few of our features to use and ignore the rest. So we can have users who sync stuff a lot but do not use drawing lab at all.

**Comment by damithc** [comment]
Covered by SyncLab
