### ISSUE TITLE
Allow having extra agenda slides in the middle of a section

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#841]
Some users may want to show the agenda slide in the middle of a section

**Comment by Skaty** [comment]
Can I work on this?

**Comment by damithc** [comment]
@Skaty 

> Can I work on this?

Can, but prefer higher priority issues.

**Comment by damithc** [comment]
Actually, I'm not sure if this one is worth doing.  The utility is low and it's hard to provide the feature in a clean way.

**Comment by damithc** [comment]
> Actually, I'm not sure if this one is worth doing. The utility is low and it's hard to provide the feature in a clean way.

Closing
