### ISSUE TITLE
Doc for Picture Slides Lab

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#845]
Some notes:
1. What should be the final name for Images Lab? Images Lab/Design Lab/Canvas Lab...? If it's to rename, I should rename the class name and namespace also. Many class names and namespaces are not sync with their features names, e.g. Shapes Lab vs CustomShapePane.cs, which will confuse new developers (just another issue).
2. In Dec 2015, Images Lab has been updated with more styles and refactored to be able to integrate with unit test (CI can run this) and functional test (UI/integration test). It should be dev-released soon.

These doc will be required for Images Lab's public release:
1. A gif image for the index page.
2. Doc for the docs page.
3. A part of doc in the tutorial (I can help this).

**Comment by damithc** [comment]
`Picture Slides Lab`? Is it short enough to show in two lines on the ribbon icon?

**Comment by kai33** [comment]
yes it is. so final name will be `Picture Slides Lab`.
![picture1](https://cloud.githubusercontent.com/assets/3591355/12020231/0d570d26-adb5-11e5-9552-354fc8a98968.png)
