### ISSUE TITLE
Cultural settings fail Auto Zoom and Zoom to Area

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#846]
Background: some European users use comma to represent the float number instead of dot.

Cause: parsing a string like "1.23" into float will throw exception because it's not in the correct format for some European users.

Related to #771, which was caused by parsing float into string (the other way around).

**Comment by kai33** [comment]
This time, functional test is ready to use and it passes all test cases with the special cultural settings.

A hot-fix release 2.6.5.1 can be made, by cheery-picking this commit onto the commit with tag release-2.6.4.0.
Or it can wait for version 2.7, but may be too late.

**Comment by damithc** [comment]
I don't mind a hotfix.
On a related note, can we do a scan of other places this problem might occur and also ways to prevent it creeping back to code. e.g. may be hide this complication behind a layer of abstraction?
