### ISSUE TITLE
Set default cultural settings to en-us

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/powerpointlabs#850]
This will prevent potential bugs like #846 #771 

ref: 
http://stackoverflow.com/a/7536117
http://blog.rastating.com/setting-default-currentculture-in-all-versions-of-net/

**Comment by damithc** [comment]
This won't affect the user? We should avoid changing preferences that goes beyond our own features.

**Comment by kai33** [comment]
It should only works for our add-in
