### ISSUE TITLE
Use a check box for toggling hotkeys

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#858]
A checkbox seems more intuitive? When I first saw the button I thought it is enabled, but turned out it was disabled.
![image](https://cloud.githubusercontent.com/assets/1673303/12071090/c89064c2-b0d3-11e5-944f-c76439d99aa6.png)

Another enhancement would be to disable all buttons when the check box is unchecked.

**Comment by damithc** [comment]
The same applies for toggle buttons in format and position tabs. Either use checkboxes or a proper toggle button. Disabling the relevant controls when the functionality is toggled off can make the UX more intuitive.

**Comment by Ohohcakester** [comment]
The controls in the format and position tabs will be disabled when the functionality is toggled off. It is not working on your end?

**Comment by damithc** [comment]
Yes, the disabling is working for format and position. I didn't notice it before.

**Comment by Ohohcakester** [comment]
Also the initial state of the hotkeys should be enabled. I'm not sure why it seems to be the reverse for your case. I am using a proper toggle button.
It seems the appearance of the buttons is also different for either different OS's or different versions of powerpoint. The buttons look a little different on my PC.

**Comment by damithc** [comment]
In my comp, for that particular button, `on` is light blue and `off` is dark blue.
![image](https://cloud.githubusercontent.com/assets/1673303/12072871/60e3549e-b135-11e5-82ea-093a848c1a87.png)

**Comment by kai33** [comment]
can use this
http://mahapps.com/controls/toggle-button.html
