### ISSUE TITLE
Allow hotkeys for custom shapes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#859]
We can allow users to select their own shapes to assign to hotkeys. We can't assume users will always use the shapes we have preassigned for hotkeys.
![image](https://cloud.githubusercontent.com/assets/1673303/12071095/6130972e-b0d4-11e5-8d63-57b8e3223191.png)

**Comment by Ohohcakester** [comment]
I can't give functionality to draw shapes other than the ones given. These are the only ones I could find API for.
For example, I really wanted to give the ability to draw curved lines, but after a day of searching, I found out that Microsoft didn't provide any way to access the curved line drawing tool through code.

**Comment by damithc** [comment]
What about other shapes? I have a memory of a third party plugin that allowed drawing many different shapes (but I could be mistaken).

**Comment by Ohohcakester** [comment]
The shapes can probably be "Spawned" programatically like in the Shapes Lab, but switching to the tool that draws the shape (e.g. a tool that draws rectangles using the cursor) isn't properly supported by the API.
