### ISSUE TITLE
Give more flexibility in multiclone grid 

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#864]
Currently, the two objects are taken as adjacent objects of the grid. The user may want to use them as the two opposite corners instead.
![image](https://cloud.githubusercontent.com/assets/1673303/12071189/a65df9c2-b0d9-11e5-9ff7-8bd7f541c031.png)

**Comment by Ohohcakester** [comment]
That's what the "Mode" button is used for. Clicking it toggles between "Extend" and "Between" modes, with the "Between" mode being what you suggested.

**Comment by damithc** [comment]
I see. That's another place to look for a more intuitive UI control :-)

**Comment by Ohohcakester** [comment]
I'm not sure if it could be any more intuitive. There are only three possible controls to interact with, two of them being immediately clear, and with a bit of exploring one can easily find out that the third button switches between the two modes as the visualisation will reflect that immediately.

**Comment by damithc** [comment]
If you anticipate more modes in future, then we have a choice between n items: a drop down box?
If you think it's going to be two modes, then we have a toggle situation. A drop-down still works but has an extra click. Modern mobile UIs have kind of a slider button for toggling, but might not fit this UI. May be an option button?
| Mode : **O** `Extend`  O `Between` |

**Comment by damithc** [comment]
Toggle buttons in IVLE: 
![image](https://cloud.githubusercontent.com/assets/1673303/12074219/097460fc-b182-11e5-9d2c-653524c01168.png)
Not easy to do unless you have a built in control though.

**Comment by kai33** [comment]
can use this one:
http://mahapps.com/controls/toggle-switch.html
