### ISSUE TITLE
Hotkey not working when multiple drawing lab is open

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#866]
When multiple drawing lab is open, only one ppt with drawing lab can use hotkey and other ppt cannot.

If one drawing lab turns off the hotkey while other turns on, no ppt with drawing lab can use hotkey.

Expected behaviors:
Hotkey should work for individual ppt slides. e.g.
1. Slides A and Slides B both turn on hotkey, then hotkey should work in both slides.
2. Slides A turns on hotkey while Slides B turns off, then hotkey should still work in Slides A.

**Comment by kai33** [comment]
feedback for dev-2.8.3.2:
1. Hotkey now works with multiple drawing lab instances.
2. **BUT** If Slide A opens drawing lab with hokey turned on and Slide B doesn't open drawing lab, press any hotkey in Slide B will **throw a null ref exception** (can't detect its stacktrace) and ppt crashes.
3. If Slide A opens drawing lab with hotkey turned off and Slide B opens drawing lab with hotkey turned on, press any hotkey in Slide B will have no effect.

**Comment by kai33** [comment]
feedback for dev-2.8.3.3:
1. If Slide A opens drawing lab with hokey turned on or off and Slide B doesn't open drawing lab, press any hotkey in Slide B will throw a null ref exception and ppt crashes. Exception at https://github.com/PowerPointLabs/PowerPointLabs/blob/DrawingsLab/PowerPointLabs/PowerPointLabs/DrawingsLab/DrawingsPaneWPF.xaml.cs#L276
solution can be, bef calling it, check if it's null.
2. hotkey toggle now works as expected across multiple drawing lab instances

**Comment by kai33** [comment]
null ref exception still exists

**Comment by Ohohcakester** [comment]
Oh, I fixed it some time ago, but haven't released it in a dev build yet.
