### ISSUE TITLE
Mention dev version in contributor guide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#875]
Contributors should be asked to install the dev version of the add-in instead of the released version.

**Comment by kai33** [comment]
Contributor cannot install the add-in in their dev environment,
because it will block building the solution.

But they can get the dev version by building from the master branch.

**Comment by damithc** [comment]
Anything to update in dev docs?

**Comment by kai33** [comment]
update dogfooding part into contribution guidelines
https://github.com/PowerPointLabs/powerpointlabs/blob/master/doc/CONTRIBUTING.md#dogfooding
