### ISSUE TITLE
Allow copy/paste to import image

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#881]
We can allow drag-drop from any website, not just google image search?

**Comment by kai33** [comment]
There are 2 types of content for **dnd** (drag and drop): link and file. the followings are their availability.

link
1. link to a non-image file, or link to an image but in fact re-direct to a non-image file (CANNOT dnd)
2. link to a gif image (CANNOT dnd if animated)
3. link to a non-gif image (CAN dnd)

file
1. file is in non-image format (CANNOT dnd)
2. file is in gif format (CANNOT dnd if animated)
3. file is in an image format (CAN dnd)

Actually gg image search is a special case, it links to a non-image file but it contains info of the link to that image and that's why it can be dnd. 

But bing image search doesn't provide such info so cannot dnd directly from bing's interface and must click into the image (so it's in **file** format) and then dnd. This may apply to other websites

**Comment by damithc** [comment]
So dnd works for a regular jpg image in a regular web page?

**Comment by kai33** [comment]
yes, if it's not wrapped by a link HTML element

**Comment by damithc** [comment]
So we ask users to drag from Google image search (if getting images from web), or drag from local disk (if using local images)? Dragging from other image searches or other websites is not supported. When using Google image search, any restriction on browser.

**Comment by kai33** [comment]
Can. No restriction on browser.

But one thing to note for google image search:
![screen shot 2016-01-18 at 4 41 42 pm](https://cloud.githubusercontent.com/assets/3591355/12386788/d4803a1e-be02-11e5-9ea1-b5c9d837409a.png)

the one cannot be dnd because its link doesn't have image info

**Comment by damithc** [comment]
I see. That's a bummer. For the 2nd image, what if the user right-click, choose 'copy image' and then paste it in PSL? Can that work?

**Comment by kai33** [comment]
That "copy image and then paste into PSL" will be a new task to develop.

But also one thing to note is that, 
* if the image is not downloaded completely (a progress bar shown below it in the google image search), it cannot be pasted.
* if the image copied is the thumbnail one, the pasted one is also the thumbnail image. 

So unlike dnd -- the user only needs to dnd the thumbnails and their full-size images will be downloaded at the backend in PSL. But for this copy-paste thing, the user needs to click the image to wait for it to download completely, and then copy-paste

**Comment by damithc** [comment]
I wish we can say just one thing: e.g. just drag any image from anywhere.
But looks like that is not possible. So our situation is,
"DnD thumbnail or CnP image"
Can PSL identify when the user mix the two up and inform the user? e.g. when the user DnD image or CnP thumbnail

**Comment by kai33** [comment]
I think cannot because they're both valid images. 

Currently the way I import images is:
* DnD thumbnails (work for google only)
* Open the image alone in a new tab, and DnD that image (work for any website)
* DnD local image files (work for any local images)

**Comment by damithc** [comment]
Do Google thumbnails have a specific size? Can we use that to identify thumbnails?

**Comment by kai33** [comment]
They're just small. Okay it should be able to detect them when copy/paste.

So for copy/paste image support in PSL:
* it has an option "Paste the image to import" in the context menu of PSL main window and quick window.
* when nothing to paste, inform user about it
* when it's to paste small image (maybe thumbnail), inform user about it
* when the pasted image is corrupted (maybe not downloaded completely), inform user about it

**Comment by damithc** [comment]
Yes, so we can say something like this:
`CnP : works from any image in a webpage or hard disk. DnD: works for Google search thumbnails and local files` 
That way, CnP works for everything, so users can survive just based on that. More sophisticated users can be more productive using DnD.

Can CnP also support `Ctrl+V` for paste?

**Comment by kai33** [comment]
I'll need to check `CnP from hard disk`, usually should be ok.

`Ctrl + V` should be ok.
