### ISSUE TITLE
Error when dragging image to PSL

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#882]
Dragging this image to PSL gives an error every time https://www.google.com.sg/search?q=working&espv=2&biw=1050&bih=1551&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi2hsHCsrDKAhUMB44KHePrCW0Q_AUIBigB#imgrc=eNWrKlo61EFchM%3A

![image](https://cloud.githubusercontent.com/assets/1673303/12376597/ec23591a-bd37-11e5-87f2-3e825caef81b.png)

**Comment by kai33** [comment]
cause: no decode of the url
