### ISSUE TITLE
Corp PC with strict requirements cannot install pptlabs

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#884]
in this case,
- the corporate PC cannot install the add-in because the certificate is not trusted (we're using test certificate, not bought from CA) by the Trusted Center
- user is non-admin so cannot change settings of Trusted Center

**Comment by kai33** [comment]
likely this is the issue for the recent user feedback

**Comment by kai33** [comment]
the certificate must support Code Signing

**Comment by damithc** [comment]
Let's buy the certificate. Figure out all the details and pass those details to me so that I can find a way to cover the cost.
