### ISSUE TITLE
New ‘Copy…’ button

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#900]
It opens slide picker, with buttons ‘copy style’ (to the current slide), ‘copy picture’ (to the current slide).

Unlike `Load...` button, `Copy...` only works within the same presentation. Also, `Load...` can load the style back and customise, but `Copy...` is more like copying the style between slides

**Comment by damithc** [comment]
For consistency, let's use 'picture' instead of 'image' everywhere inside this lab.

**Comment by damithc** [comment]
Why do we need two things: `copy` and `load`? Can't we make them the same?

**Comment by damithc** [comment]
A related question: how does PSL work when there are multiple slide decks open? How does it know which slide deck we intend it to work with?

**Comment by kai33** [comment]
`Load...` supports
* load back styles to customize (with the variation stage)
* load back image (to adjust dimensions and) to use on other style (image loaded into the image selection region)
* (planning) load style from local storage

`Copy...` is mainly for quickly copying one style/image to another (e.g. the current one).
* it won't change the stage stuff and won't load the image into the image selection region)

**Comment by kai33** [comment]
PSL will work with the current active presentation and this presentation's selected slide (current slide).

**Comment by damithc** [comment]
In that case, by `copy` I meant `load`. I don't need the quick copy thing.
