### ISSUE TITLE
Load `Adjusted picture dimensions` info

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#903]
background: `Adjusted picture dimensions` is per picture, instead of per slide.

If go to a slide with a style and a picture with adjusted dimensions A, and this picture with adjusted dimensions B (a different dimensions/offset) still in the picture selection region, it will load the picture with adjusted dimensions B instead of A. It should load dimensions A (which is used by the slide) in this case.

need to update these:
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/PictureSlidesLab/View/PictureSlidesLabWindow.xaml.LoadStyle.cs#L137
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/PictureSlidesLab/View/PictureSlidesLabWindow.xaml.LoadStyle.cs#L55

example of loading dimensions info:
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/PictureSlidesLab/View/PictureSlidesLabWindow.xaml.LoadStyle.cs#L225

**Comment by damithc** [comment]
It was the 'label notification' thingy that is blocking the update. Things went back to normal after I closed it.
