### ISSUE TITLE
Message in the sidebar of Shapes Lab is out of alignment

### ISSUE THREAD

**Issue by youthinkk** [PowerPointLabs/PowerPointLabs#912]
As the image shown below, the message in gray does not display properly.

![shapes lab - bug](https://cloud.githubusercontent.com/assets/13010884/12694081/f385e366-c75b-11e5-9542-75eccca2aeaf.PNG)

**Comment by digawp** [comment]
I can't reproduce it. Is there any particular steps to reproduce it?

**Comment by youthinkk** [comment]
After clicking Shapes Lab button in the ribbon, this error occurred without any further action. Mine is PowerPoint 2013 running on Windows 8.1 Pro 64 bit with the size of items at 200%.
