### ISSUE TITLE
PowerPoint still running after create category for shapes lab

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#914]
1. open shapes lab
2. create new category
3. close ppt.

but then ppt still running, because ShapesGallery.pptx is not closed at the backend.

expected:
ppt should be closed after this.

**Comment by Dawnlord** [comment]
Is there still this problem? How can I see whether the ppt is still running?

**Comment by kai33** [comment]
task manager

**Comment by Dawnlord** [comment]
Have tested for several times. I think I have not meet this bug.
