### ISSUE TITLE
Exception related to clipboard

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#920]
stacktrace:
System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   bei Microsoft.Office.Interop.PowerPoint.Shapes.Paste()
   bei PowerPointLabs.CropToShape.MakeCopyForShapeRange(ShapeRange rangeOriginal)
   bei PowerPointLabs.CropToShape.GetShapeForSelection(ShapeRange shapeRange)
   bei PowerPointLabs.CropToShape.Crop(ShapeRange shapeRange, Double magnifyRatio, Boolean handleError)

**Comment by kai33** [comment]
strangely,
this user's ppt
1. can successfully copy/paste a shape for the first time
2. but cannot copy/paste for the second time.

may be related to #823

**Comment by kai33** [comment]
found a link:
http://answers.microsoft.com/en-us/office/forum/office_2010-powerpoint/vba-bug-copy-slide-and-paste-as-image-in-other/40bc7b6b-587c-4263-a24b-d7e50afcbee8?db=5&auth=1
> Is there anyone able to .Copy a slide and .PasteSpecial as image in other slide without producing the following error?  Runtime Error '-2147188160(80048240': Shapes (unknown member):Invalid request. Clipboard is empty or contains data which may not be pasted here.

> Solution: Oracle VirtualBox offers a setting to share the clipboard and its contents between host and guest machines. This setting was activated. Turning it off made it all work.

**Comment by kai33** [comment]
a similar case reported from a user, but it's for zoomToArea

System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.Paste()
   at PowerPointLabs.ZoomToArea.GetBestFitShape(PowerPointSlide currentSlide, Shape zoomShape)
   at PowerPointLabs.ZoomToArea.<>c__DisplayClass5_0.<GetEditedShapesForZoomToArea>b__0(Shape zoomShape)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PowerPointLabs.ZoomToArea.GetEditedShapesForZoomToArea(PowerPointSlide currentSlide, List`1 zoomRectangles)
   at PowerPointLabs.ZoomToArea.AddZoomToArea()

**Comment by kai33** [comment]
a user reported this case.
all clipboard related features cannot work on this device.

update VSTO version won't work.
not sure if anything blocks the clipboard access

**Comment by leeyh20** [comment]
I seem to have encountered a similar issue when testing CropLab on my own.

Produced on Windows 10, PowerPoint 2016.
Steps: 
1. Use Crop To Shape once on a shape
2. Undo
3. Use Crop To Shape again on the same shape.
4. Undefined error is shown as an error message.

After some debugging, the exception probably occurs at the CropToShape.cs line 97, `Shape shapeToReturn = currentSlide.Shapes.Paste()[1];`

I assume this copy and paste mechanism is done to prevent corruption? However it seems to cause other issues too, such as #1530  and #1439

**Comment by ChesterSng** [comment]
> Steps:
> 
> Use Crop To Shape once on a shape
> Undo or Drag shape around rapidly
> Use Crop To Shape again on the same shape.
> Undefined error is shown as an error message.
> However, desired result is obtained! CropToShape is successful.
> Also, when dragging shape around rapidly, it usually causes the result to be slightly displaced.

@leeyh20 can u still reproduce this error reliably?

**Comment by yuhongherald** [comment]
#1915 introduces a fix for this.

**Comment by frozenprakash** [comment]
This Clipboard issue in powerpoint vsto is pretty wild.
Occurs very frequently while trying to paste.
