### ISSUE TITLE
COMException while auto-updating addin

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#921]
This error came up during three previous updates. It happens during the auto update. It disables the addin. I usually re-enable the addin and restart powerpoint. After restart, ppltlabs seemed to have been updated in spite of the error. 
Happened in my Win7 machine, but not in my Win8. Both running PPT 2010.

Name: PowerPointLabs - PowerPointLabs
From: http://www.comp.nus.edu.sg/~pptlabs/download/dev/PowerPointLabs.vsto

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x8007001F): A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by kai33** [comment]
does updating VSTO help?
link: http://www.comp.nus.edu.sg/~pptlabs/vsto-redirect.html

**Comment by damithc** [comment]
I'll try that.

**Comment by damithc** [comment]
Installed. Have to wait till next release to find if it recurs. I'll close for now. Will reopen if it happens again.

**Comment by damithc** [comment]
Ok, the installation seems to have fixed the problem.
