### ISSUE TITLE
"image file is corrupted" error when clicking on an image

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#922]
It happens when the selected slide is an existing slide with a few shapes on it. No such problem when trying the same image on a different slide that is empty.
![image](https://cloud.githubusercontent.com/assets/1673303/12864915/cb174ac4-ccd7-11e5-8160-ebaaf901fe82.png)

**Comment by kai33** [comment]
just dev-released 2.8.5.1 that contains a fix for this
