### ISSUE TITLE
Change PSL window color to #0070C0

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#923]
here
https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/PictureSlidesLab/View/PictureSlidesLabWindow.xaml#L14

and it will look like this
![presentation1](https://cloud.githubusercontent.com/assets/3591355/12865174/88c514d6-cce0-11e5-938d-4d48426ffc02.jpg)

**Comment by damithc** [comment]
How about the blue as primary color and orange as the secondary color? It may not look as good as the original color, but consistency helps.

**Comment by kai33** [comment]
#0070C0
looks better
![image](https://cloud.githubusercontent.com/assets/3591355/12865329/e4dbecba-cce3-11e5-94a3-5ba0e5fe5ebf.png)

**Comment by damithc** [comment]
Let's go with blue then. If possible, use orange as the secondary color. e.g. for highlighting selected slide. I think the orange in the PL logo is sharper than the one on buttons.

**Comment by damithc** [comment]
BTW, we should do this soon because we need the right color for screenshots in the user guide.
