### ISSUE TITLE
Provide everyday phrases (about presentation?) when loading PSL

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#944]

**Comment by kai33** [comment]
If you can't explain it simply, you don't understand it well enough. - Albert Einstein
All the great speakers were bad speakers at first. - Ralph Waldo Emerson
Stay hungry, stay foolish. - Steve Jobs
The right word may be effective, but no word was ever as effective as a rightly timed pause. - Mark Twain

**Comment by damithc** [comment]
http://www.thepresentationskills.com/a-page-with-quotes-about-presentation-skills/

**Comment by damithc** [comment]
It would be nice to include some quotes from contemporary presentation gurus such as Garr Reynolds, Nancy Duartey, Cliff Atkinson, Dan Roam, Carmine Gallo, Jerry Weissman, Robin Williams, ...
