### ISSUE TITLE
Lossless compression for all images

### ISSUE THREAD

**Issue by alexyaoyang** [PowerPointLabs/PowerPointLabs#952]
I ran a performance check on http://www.comp.nus.edu.sg/~pptlabs/ and found out that most of the images used are not compressed. I tried compressing a couple images and realized we can save about 30% space for all images. Saves both loading time and bandwidth for the user and also nus comp server. Even GIFs can be compressed. And since the compressions are lossless, we should make use of it!

For example:
install.png: 247 KB can be losslessly compressed to 69 KB
after.gif: 4.2 MB can be losslessly compressed to 3.3 MB

This should be labelled as Performance.Website but I don't have the authority to do so.

**Comment by damithc** [comment]
@alexyaoyang What tool do you suggest we use to compress?

**Comment by alexyaoyang** [comment]
I normally use https://kraken.io. I find that is it better than https://compressor.io and a few others because it compresses the images smaller and allows lossless compression of GIFs on top of the normal jpg and png.

On Feb 21, 2016, at 8:20 PM, Damith C. Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


@alexyaoyang<https://github.com/alexyaoyang> What tool do you suggest we use to compress?

—
Reply to this email directly or view it on GitHub<https://github.com/PowerPointLabs/PowerPointLabs/issues/952#issuecomment-186814248>.


Sent from my iPhone, pardon brevity

**Comment by damithc** [comment]
If it cannot be automated, we can at least document the guidelines on how to compress images when adding a new image in a PR.

**Comment by alexyaoyang** [comment]
I will attempt to automate the process first, if not then I will add a section in the guidelines on how to compress images.
