### ISSUE TITLE
Provide a control to edit alignment for Text Position aspect

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#957]
and then provide a top position in the aspect

**Comment by damithc** [comment]
As discussed, see if this can be made into a variation.

**Comment by Dawnlord** [comment]
I am now working on this function. However, who can give me more details about it?

**Comment by damithc** [comment]
Let's KIV this for now, while we tidy up the ribbon and push the recent new features out the door.
