### ISSUE TITLE
Spotlight smaller than slide

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#968]
![image](https://cloud.githubusercontent.com/assets/1673303/13430503/49662efa-e000-11e5-9b6d-3f94807611ac.png)

**Comment by kai33** [comment]
Can be reproduced in Office 2010.
@oswell take a look

**Comment by damithc** [comment]
@oswellchan this is a bug that needs to be fixed soon.

**Comment by oswellchan** [comment]
Okay. Will submit a pull request to solve this bug soon
