### ISSUE TITLE
Support 'crop to shape' for rotated shapes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#971]
Now that the resize lab can redefine the bounding box, we should be able to support crop-to-shape for rotated shapes.

**Comment by kai33** [comment]
ref:
https://github.com/PowerPointLabs/PowerPointLabs/blob/dev-release/PowerPointLabs/PowerPointLabs/Utils/PPShape.cs#L137

by using this method, the rotated shape can be converted to upright one

**Comment by kai33** [comment]
@youthinkk this method is very creative.
Can it support group shape (msoGroupShape) also? not urgent.

**Comment by youthinkk** [comment]
@kai33, I will look into that!
