### ISSUE TITLE
Revise 'terms of use' page to make the acknowledgement slide optional

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#976]
Revise this statement:
`Slides created using PowerPointLabs may be used or distributed in any way, as long as the acknowledgement slide inserted by the plugin is included with them`
to this:
`Slides created using PowerPointLabs may be used or distributed in any way. We hope you will retain the acknowledgement slide inserted by PowerPointLabs, but it is not compulsory.`

**Comment by Dawnlord** [comment]
Fixed
