### ISSUE TITLE
Enhance PSL document

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#981]
http://www.comp.nus.edu.sg/~pptlabs/docs.html#picture-slides-lab
a.
search for "Use a Browser to search in Google Image Search" and a screenshot to demo drag and drop can be seen.
the screenshot provided is not very intuitive. It's better to have an animated gif to demo drag and drop.

this may help:
http://www.cockos.com/licecap/

b.
some screenshots don't look very attractive, better make it look fancy

**Comment by damithc** [comment]
This can be replaced too (the subheading place holder makes it untidy)
![image](https://cloud.githubusercontent.com/assets/1673303/13879975/1e44b1b2-ed55-11e5-90a0-ffe4f4c2e1ff.png)

**Comment by kai33** [comment]
also add video into PSL document:
https://www.youtube.com/watch?v=vyBUandCKZo
