### ISSUE TITLE
effects lab: support 'frosted glass' feature

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#994]
Here is an example:
![image](https://cloud.githubusercontent.com/assets/1673303/14526570/b13abdfa-0276-11e6-9e41-09445521f8cf.png)
It's already supported inside Picture Slides Lab. Just needs to provide the same feature in Effects Lab.

**Comment by Dawnlord** [comment]
Fiona will continue to do this issue and I will close my PR.

**Comment by damithc** [comment]
@fionachang is documentation for this feature done?
