### ISSUE TITLE
Support repack feature

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#999]
User can repack a bunch of objects based on the click order

![image](https://cloud.githubusercontent.com/assets/1673303/14565770/37877efa-035f-11e6-89d0-f89e01434e2c.png)

**Comment by damithc** [comment]
What's the status of this? If you are waiting for review, need to inform the reviewer.

**Comment by ChesterSng** [comment]
Hi Prof @damithc , I would like to work on this! Can I clarify what should be the behaviour if the images are not aligned at the start? 
Example:
![image](https://user-images.githubusercontent.com/39242483/51985364-a1f16b00-24d8-11e9-8591-bc90f72bfe39.png)

**Comment by damithc** [comment]
> Hi Prof @damithc , I would like to work on this! Can I clarify what should be the behaviour if the images are not aligned at the start?

On second thoughts, it's probably not worth doing this feature. :-p it's a rare use case and there are other reasonable ways to achieve the same, albeit with more steps.

**Comment by ChesterSng** [comment]
@damithc I realised that swap can do this to a certain extext haha

**Comment by damithc** [comment]
> @damithc I realised that swap can do this to a certain extent haha

Yes, but if the pictures are of different width, the final outcome will not be as expected.
